// Generated by portomatic scaffold from upstream Daqifi.Desktop/Device/IDevice.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.ComponentModel;

namespace Daqifi.Desktop.Device;

// @port: Daqifi.Desktop.Device.IDevice
public interface IDevice : INotifyPropertyChanged
{
    // @port: Daqifi.Desktop.Device.IDevice.Id
    int Id { get; set; }

    // @port: Daqifi.Desktop.Device.IDevice.Name
    string Name { get; set; }

    /// <summary>
    /// Connects to the streamingDevice.
    /// </summary>
    /// <returns>True if successfully connected</returns>
    // @port: Daqifi.Desktop.Device.IDevice.Connect
    bool Connect();

    /// <summary>
    /// Disconnects from the streamingDevice
    /// </summary>
    /// <returns>True if successfully disconnected</returns>
    // @port: Daqifi.Desktop.Device.IDevice.Disconnect
    bool Disconnect();

    /// <summary>
    /// Reboots the streamingDevice
    /// </summary>
    // @port: Daqifi.Desktop.Device.IDevice.Reboot
    void Reboot();
}