// Generated by portomatic scaffold from upstream Daqifi.Desktop/Device/IStreamingDevice.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Daqifi.Desktop.Channel;
using ChannelDirection = Daqifi.Core.Channel.ChannelDirection;
using Daqifi.Core.Device.Network;
using Daqifi.Core.Device.SdCard;
using Daqifi.Desktop.Models;
using DeviceType = Daqifi.Core.Device.DeviceType;

namespace Daqifi.Desktop.Device;

// @port: Daqifi.Desktop.Device.DeviceMode
public enum DeviceMode
{
    StreamToApp,
    LogToDevice
}

// @port: Daqifi.Desktop.Device.ConnectionType
public enum ConnectionType
{
    /// <summary>
    /// Device is connected via USB
    /// </summary>
    Usb,

    /// <summary>
    /// Device is connected via WiFi
    /// </summary>
    Wifi
}

// @port: Daqifi.Desktop.Device.IStreamingDevice
public interface IStreamingDevice : IDevice
{
    // @port: Daqifi.Desktop.Device.IStreamingDevice.Mode
    DeviceMode Mode { get; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.ConnectionType
    ConnectionType ConnectionType { get; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.IsConnected
    bool IsConnected { get; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.IsLoggingToSdCard
    bool IsLoggingToSdCard { get; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.SdCardFiles
    IReadOnlyList<SdCardFile> SdCardFiles { get; }

    /// <summary>
    /// Gets or sets the SD card logging format used when starting SD card logging.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.SdCardLogFormat
    SdCardLogFormat SdCardLogFormat { get; set; }

    // @port: Daqifi.Desktop.Device.IStreamingDevice.SwitchMode
    void SwitchMode(DeviceMode newMode);
    // @port: Daqifi.Desktop.Device.IStreamingDevice.StartSdCardLogging
    void StartSdCardLogging();
    // @port: Daqifi.Desktop.Device.IStreamingDevice.StopSdCardLogging
    void StopSdCardLogging();
    // @port: Daqifi.Desktop.Device.IStreamingDevice.RefreshSdCardFiles
    void RefreshSdCardFiles();
    // @port: Daqifi.Desktop.Device.IStreamingDevice.UpdateSdCardFiles
    void UpdateSdCardFiles(List<SdCardFile> files);
    // @port: Daqifi.Desktop.Device.IStreamingDevice.DevicePartNumber
    string DevicePartNumber { get; }

    /// <summary>
    /// Gets the device's hardware timestamp clock frequency in Hz.
    /// Used as a fallback when parsing SD card files that lack this field.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.TimestampFrequency
    uint TimestampFrequency { get; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.NetworkConfiguration
    NetworkConfiguration NetworkConfiguration { get; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.MacAddress
    string MacAddress { get; set; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.DeviceSerialNo
    string DeviceSerialNo { get; set; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.DeviceVersion
    string DeviceVersion { get; set; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.IsFirmwareOutdated
    bool IsFirmwareOutdated { get; set; }

    /// <summary>
    /// Gets the detected device type (e.g. Nyquist 1/2/3), or <see cref="DeviceType.Unknown"/>
    /// when the device has not yet been identified.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.DeviceType
    DeviceType DeviceType { get; }

    /// <summary>
    /// Gets whether this device has a separately-flashable WINC1500 WiFi module — i.e. it is
    /// part of the Nyquist family. ESP32-based and unrecognized devices integrate WiFi into the
    /// SoC and have no WINC firmware to query or flash, so the WiFi-firmware check is skipped
    /// for them.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.HasWincWifiModule
    bool HasWincWifiModule { get; }

    /// <summary>
    /// Gets or sets whether the device's WiFi module firmware needs to be flashed —
    /// either because the reported version is below the minimum supported version or
    /// because the WiFi chip-info query failed. Only meaningful for USB-connected
    /// devices with a WINC1500 module (see <see cref="HasWincWifiModule"/>).
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.IsWifiFirmwareOutdated
    bool IsWifiFirmwareOutdated { get; set; }

    /// <summary>
    /// Gets or sets the WiFi module firmware version reported by the device, or
    /// <c>"Unknown"</c> when the chip-info query could not be completed.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.WifiFirmwareVersion
    string WifiFirmwareVersion { get; set; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.IpAddress
    string IpAddress { get; set; }
    // @port: Daqifi.Desktop.Device.IStreamingDevice.StreamingFrequency
    int StreamingFrequency { get; set; }
    
    /// <summary>
    /// Gets the appropriate display identifier for this device based on connection type.
    /// Returns COM port for USB devices, IP address for WiFi devices.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.DisplayIdentifier
    string DisplayIdentifier { get; }

    /// <summary>
    /// Gets the best available human-readable name for this device.
    /// Returns the serial number when populated, otherwise falls back to DisplayIdentifier.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.DeviceDisplayName
    string DeviceDisplayName { get; }

    // @port: Daqifi.Desktop.Device.IStreamingDevice.DataChannels
    List<IChannel> DataChannels { get; set; }

    // @port: Daqifi.Desktop.Device.IStreamingDevice.InitializeStreaming
    void InitializeStreaming();
    // @port: Daqifi.Desktop.Device.IStreamingDevice.StopStreaming
    void StopStreaming();

    /// <summary>
    /// Sends a command to get any initialization data from the streamingDevice that might be needed
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.InitializeDeviceState
    void InitializeDeviceState();

    /// <summary>
    /// Sends a command to activate a channel on the streamingDevice
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.AddChannel
    void AddChannel(IChannel channel);

    /// <summary>
    /// Sends a command to deactivate a channel on the streamingDevice
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.RemoveChannel
    void RemoveChannel(IChannel channel);

    /// <summary>
    /// Enables multiple channels on the device with a single SCPI command per channel type.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.AddChannels
    void AddChannels(IEnumerable<IChannel> channels);

    /// <summary>
    /// Disables all channels on the device.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.RemoveAllChannels
    void RemoveAllChannels();

    /// <summary>
    /// Drives a digital output channel's state through the Core device (values >= 0.5 drive
    /// high). Non-digital channels are ignored. When the device is missing or disconnected the
    /// call logs and no-ops instead of throwing — it can originate from UI property setters
    /// racing a disconnect.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.SetChannelOutputValue
    void SetChannelOutputValue(IChannel channel, double value);

    /// <summary>
    /// Sets a digital channel's I/O direction through the Core device. Non-digital channels
    /// are ignored, and a missing or disconnected device logs and no-ops rather than throwing
    /// (same rationale as <see cref="SetChannelOutputValue"/>).
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.SetChannelDirection
    void SetChannelDirection(IChannel channel, ChannelDirection direction);

    /// <summary>
    /// Starts or stops PWM output on a digital channel through the Core device. Enabling
    /// resends the channel's duty cycle and the device-wide frequency first (Core's
    /// documented duty → frequency → enable order), so the device always runs exactly what
    /// the UI shows. Non-digital channels are ignored, and a missing or disconnected device
    /// logs and no-ops rather than throwing (same rationale as
    /// <see cref="SetChannelOutputValue"/>).
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.SetChannelPwmEnabled
    void SetChannelPwmEnabled(IChannel channel, bool enabled);

    /// <summary>
    /// Sets a digital channel's PWM duty cycle (1-100 percent) through the Core device;
    /// takes effect immediately while the channel's PWM output is enabled. Non-digital
    /// channels are ignored, and a missing or disconnected device logs and no-ops rather
    /// than throwing (same rationale as <see cref="SetChannelOutputValue"/>).
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.SetChannelPwmDutyCycle
    void SetChannelPwmDutyCycle(IChannel channel, int dutyCyclePercent);

    /// <summary>
    /// Gets or sets the device-wide PWM frequency in hertz (6-50000, coerced). All PWM
    /// channels share one hardware timer, so there is exactly one frequency per device.
    /// Setting it commands the device immediately (a live change rescales every enabled
    /// PWM channel), and the value is also resent whenever a channel's PWM output is
    /// enabled.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.PwmFrequencyHz
    int PwmFrequencyHz { get; set; }

    // @port: Daqifi.Desktop.Device.IStreamingDevice.UpdateNetworkConfiguration
    Task UpdateNetworkConfiguration();

    /// <summary>
    /// Downloads a file from the device's SD card over USB to a temporary file.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.DownloadSdCardFileAsync
    Task<SdCardDownloadResult> DownloadSdCardFileAsync(
        string fileName,
        IProgress<SdCardTransferProgress>? progress = null,
        CancellationToken ct = default);

    /// <summary>
    /// Deletes a file from the device's SD card.
    /// </summary>
    // @port: Daqifi.Desktop.Device.IStreamingDevice.DeleteSdCardFileAsync
    Task DeleteSdCardFileAsync(string fileName, CancellationToken ct = default);
}
