#!/usr/bin/env bash
#
# Regenerate every committed packages.lock.json in this repo.
#
# WHY THIS EXISTS
#
# Dependabot cannot do it. Its NuGet updater rewrites the lock file only in the
# directory whose manifest it edited, and every head's lock file records the SHARED
# library's full transitive closure — Sentry, NLog, EF Core, Daqifi.Core and the rest
# all appear as `Transitive` entries in Desktop, Android, iOS, AvaloniaCapture and the
# test project. So a one-line bump in Daqifi.Avalonia/Daqifi.Avalonia.csproj invalidates
# SIX lock files and Dependabot refreshes one, leaving five stale. Locked mode then fails
# the other five with:
#
#     error NU1004: The project references daqifi.avalonia whose dependencies has
#     changed. The packages lock file is inconsistent with the project dependencies
#     so restore can't be run in locked mode.
#
# That is not hypothetical: it is what PR #130 and #96 are failing with right now, on
# the Android and iOS heads both. Any Dependabot PR touching /Daqifi.Avalonia — 23 of
# the 28 packages managed here — needs a commit from this script before it can go
# green. See "Why a Dependabot PR that touches /Daqifi.Avalonia needs a lock-file
# commit" in .github/dependency-updates/README.md.
#
# TWO FLAGS ARE LOAD-BEARING, AND ONE IS FORBIDDEN
#
#   --force-evaluate   Required. Without it a restore that finds a consistent lock file
#                      leaves it alone, so a stale entry survives the refresh.
#   -r <rid>           NEVER. An explicit RID restore REWRITES the lock file to hold
#                      only that RID and drops the others (#85, and the warning at the
#                      top of Directory.Build.props). Daqifi.Avalonia declares six and
#                      the iOS head two; pruning them breaks the next CI run.
#
# ON LOCKED MODE
#
# --force-evaluate is what overrides RestoreLockedMode, so this works unchanged with
# CI=true set (which Directory.Build.props turns locked mode on for). NuGet's own
# NU1004 text says as much — "Disable the RestoreLockedMode MSBuild property or pass an
# explicit --force-evaluate option to run restore to update the lock file" — and it is
# verified: with CI=true and RestoreLockedMode evaluating true, a plain restore of a
# stale head fails NU1004 while the same restore with --force-evaluate regenerates it.
#
# EXIT CODES, matching .github/scripts/check_avalonia_versions.py
#
#   0  every lock file was regenerated
#   1  a restore failed — the graph itself does not resolve (an NU1605 downgrade, say).
#      Every lock file is rolled back to its pre-run state first; fix the conflict and
#      re-run.
#   2  the refresh could not run — wrong SDK, or a missing workload.
#
# NOTHING IS LEFT HALF-WRITTEN in either failure case, deliberately. A partial refresh
# is worse than none: it looks like the job was done, reads as an ordinary refresh diff,
# and leaves the head it never reached failing NU1004 anyway.
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

# Every project that carries a committed packages.lock.json. Restore walks
# ProjectReferences, so the vendored OxyPlot is reached from the others — but it is
# listed anyway, because "something else will have covered it" is exactly how a lock
# file goes stale unnoticed. Neither AvaloniaCapture nor HeadlessBench is in
# Daqifi.Avalonia.slnx, so a solution-level restore misses them; that is why this
# iterates projects, not the slnx.
# tools/parity-audit/WpfCapture is absent on purpose — it opts out of the lock-file
# policy entirely (see its csproj), since it ProjectReferences the sibling
# daqifi-desktop repo and no PR here could ever refresh such a lock file.
PROJECTS=(
  Daqifi.Avalonia/Daqifi.Avalonia.csproj
  Daqifi.Avalonia.Desktop/Daqifi.Avalonia.Desktop.csproj
  Daqifi.Avalonia.Android/Daqifi.Avalonia.Android.csproj
  Daqifi.Avalonia.iOS/Daqifi.Avalonia.iOS.csproj
  Daqifi.Avalonia.Tests/Daqifi.Avalonia.Tests.csproj
  tools/parity-audit/AvaloniaCapture/AvaloniaCapture.csproj
  tools/system-test/HeadlessBench/HeadlessBench.csproj
  third_party/oxyplot-avalonia/OxyPlot.Avalonia/OxyPlot.Avalonia.csproj
)

# Resolve the SDK before doing anything. global.json pins 10.0.302 with
# rollForward: disable, and a Homebrew `dotnet` on PATH commonly carries a different
# band and fails with "A compatible .NET SDK was not found".
#
# $DOTNET, if set, is AUTHORITATIVE — a mismatch there is an error, never a reason to
# quietly fall back to some other dotnet. Silently running a different SDK than the one
# the caller named is how a lock file gets regenerated by the wrong toolchain and the
# diff blamed on something else.
pinned=$(python3 -c 'import json;print(json.load(open("global.json"))["sdk"]["version"])')
if [ -n "${DOTNET:-}" ]; then
  candidates=("${DOTNET}")
else
  candidates=(dotnet "$HOME/.dotnet/dotnet" /usr/local/share/dotnet/dotnet)
fi
for candidate in "${candidates[@]}"; do
  command -v "${candidate}" >/dev/null 2>&1 || [ -x "${candidate}" ] || continue
  if [ "$("${candidate}" --version 2>/dev/null)" = "${pinned}" ]; then
    DOTNET_BIN="${candidate}"
    break
  fi
done
if [ -z "${DOTNET_BIN:-}" ]; then
  if [ -n "${DOTNET:-}" ]; then
    echo "FAIL: DOTNET=${DOTNET} does not report the pinned SDK ${pinned}." >&2
    echo "      Refusing to fall back to another dotnet — you named this one." >&2
  else
    echo "FAIL: no dotnet on this machine reports the pinned SDK ${pinned}." >&2
    echo "      Install ${pinned}, or set DOTNET=/path/to/dotnet and re-run." >&2
  fi
  echo "      global.json sets rollForward: disable, so a near miss is still a miss." >&2
  exit 2
fi
echo "SDK ${pinned} via ${DOTNET_BIN}"

# Restoring a net10.0-android36.0 or net10.0-ios project needs its workload, and
# WITHOUT it restore fails NETSDK1147 rather than degrading — so the lock file simply
# cannot be regenerated. This is also the reason Dependabot's own updater cannot
# refresh the Android head's lock file: its image installs SDKs and no workloads.
# Assert both up front so the failure names the missing workload instead of surfacing
# 200 lines into a restore.
missing=()
installed=$("${DOTNET_BIN}" workload list 2>/dev/null || true)
for workload in android ios; do
  if ! printf '%s\n' "${installed}" | awk -v w="${workload}" '$1 == w { found = 1 } END { exit !found }'; then
    missing+=("${workload}")
  fi
done
if [ "${#missing[@]}" -ne 0 ]; then
  echo "FAIL: missing workload(s): ${missing[*]}" >&2
  echo "      Install with: ${DOTNET_BIN} workload install ${missing[*]}" >&2
  echo "      Refusing to refresh anything — a partial refresh leaves the skipped" >&2
  echo "      head failing NU1004 while looking like the job was done." >&2
  exit 2
fi
echo "workloads present: android, ios"

# Snapshot every lock file before the first restore. Restores run one project at a
# time, so a failure on the fourth leaves the first three already rewritten — the exact
# partial refresh the preflight above refuses to produce, arriving by a different door
# and looking like an ordinary refresh diff on the way out.
#
# The snapshot is of the WORKING TREE, not of HEAD. On a Dependabot branch the shared
# library's lock file is already legitimately modified; rolling back to HEAD would
# discard Dependabot's own work along with ours.
snapshot=$(mktemp -d)
trap 'rm -rf "${snapshot}"' EXIT

lock_of() { echo "$(dirname "$1")/packages.lock.json"; }

index=0
for project in "${PROJECTS[@]}"; do
  lock=$(lock_of "${project}")
  [ -f "${lock}" ] && cp "${lock}" "${snapshot}/${index}"
  index=$((index + 1))
done

rollback() {
  local index=0 project lock
  for project in "${PROJECTS[@]}"; do
    lock=$(lock_of "${project}")
    if [ -f "${snapshot}/${index}" ]; then
      cp "${snapshot}/${index}" "${lock}"
    elif [ -f "${lock}" ]; then
      # No snapshot means the file did not exist before this run, so a rollback has to
      # remove it rather than leave a lock file nobody committed.
      rm -f "${lock}"
    fi
    index=$((index + 1))
  done
}

for project in "${PROJECTS[@]}"; do
  echo "==> ${project}"
  if ! "${DOTNET_BIN}" restore "${project}" --force-evaluate; then
    rollback
    echo >&2
    echo "FAIL: restore of ${project} failed. Every lock file has been rolled back to" >&2
    echo "      its pre-run state, so nothing here is half-refreshed." >&2
    echo "      This is a real dependency problem, not a toolchain one — read the NU" >&2
    echo "      error above, fix the pin, and re-run." >&2
    exit 1
  fi
done

echo
echo "Lock files after refresh:"
if git diff --quiet -- '**/packages.lock.json'; then
  echo "  (no change — they were already current)"
else
  git diff --stat -- '**/packages.lock.json'
  echo
  echo "Commit these alongside the manifest change. Do NOT commit a lock file from a"
  echo "'-r <rid>' build; re-run this script instead."
fi
