#!/usr/bin/env bash
#
# Regenerate every committed packages.lock.json in this repo.
#
# WHY THIS EXISTS
#
# Dependabot cannot do it. Its NuGet updater rewrites the lock file only in the
# directory whose manifest it edited, and every head's lock file records the SHARED
# library's full transitive closure — Sentry, NLog, EF Core, Daqifi.Core and the rest
# all appear as `Transitive` entries in Desktop, Android, iOS and AvaloniaCapture. So a
# one-line bump in Daqifi.Avalonia/Daqifi.Avalonia.csproj invalidates FIVE lock files
# and Dependabot refreshes one, leaving four stale. Locked mode then fails the other
# four heads with:
#
#     error NU1004: The project references daqifi.avalonia whose dependencies has
#     changed. The packages lock file is inconsistent with the project dependencies
#     so restore can't be run in locked mode.
#
# That is not hypothetical: it is what PR #130 and #96 are failing with right now, on
# the Android and iOS heads both. Any Dependabot PR touching /Daqifi.Avalonia — 23 of
# the 28 packages managed here — needs a commit from this script before it can go
# green. See "Why a Dependabot PR that touches /Daqifi.Avalonia needs a lock-file
# commit" in .github/dependency-updates/README.md.
#
# TWO FLAGS ARE LOAD-BEARING, AND ONE IS FORBIDDEN
#
#   --force-evaluate   Required. Without it a restore that finds a consistent lock file
#                      leaves it alone, so a stale entry survives the refresh.
#   -r <rid>           NEVER. An explicit RID restore REWRITES the lock file to hold
#                      only that RID and drops the others (#85, and the warning at the
#                      top of Directory.Build.props). Daqifi.Avalonia declares six and
#                      the iOS head two; pruning them breaks the next CI run.
#
# EXIT CODES, matching .github/scripts/check_avalonia_versions.py
#
#   0  every lock file was regenerated
#   2  the refresh could not run — wrong SDK, or a missing workload. Nothing is
#      written in that case, because a PARTIAL refresh is worse than none: it looks
#      like the job was done and leaves the untouched head failing NU1004 anyway.
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

# Every project that carries a committed packages.lock.json. Restore walks
# ProjectReferences, so the vendored OxyPlot is reached from the others — but it is
# listed anyway, because "something else will have covered it" is exactly how a lock
# file goes stale unnoticed. AvaloniaCapture is NOT in Daqifi.Avalonia.slnx, so a
# solution-level restore misses it; that is why this iterates projects, not the slnx.
# tools/parity-audit/WpfCapture is absent on purpose — it opts out of the lock-file
# policy entirely (see its csproj), since it ProjectReferences the sibling
# daqifi-desktop repo and no PR here could ever refresh such a lock file.
PROJECTS=(
  Daqifi.Avalonia/Daqifi.Avalonia.csproj
  Daqifi.Avalonia.Desktop/Daqifi.Avalonia.Desktop.csproj
  Daqifi.Avalonia.Android/Daqifi.Avalonia.Android.csproj
  Daqifi.Avalonia.iOS/Daqifi.Avalonia.iOS.csproj
  tools/parity-audit/AvaloniaCapture/AvaloniaCapture.csproj
  third_party/oxyplot-avalonia/OxyPlot.Avalonia/OxyPlot.Avalonia.csproj
)

# Resolve the SDK before doing anything. global.json pins 10.0.302 with
# rollForward: disable, and a Homebrew `dotnet` on PATH commonly carries a different
# band and fails with "A compatible .NET SDK was not found".
#
# $DOTNET, if set, is AUTHORITATIVE — a mismatch there is an error, never a reason to
# quietly fall back to some other dotnet. Silently running a different SDK than the one
# the caller named is how a lock file gets regenerated by the wrong toolchain and the
# diff blamed on something else.
pinned=$(python3 -c 'import json;print(json.load(open("global.json"))["sdk"]["version"])')
if [ -n "${DOTNET:-}" ]; then
  candidates=("${DOTNET}")
else
  candidates=(dotnet "$HOME/.dotnet/dotnet" /usr/local/share/dotnet/dotnet)
fi
for candidate in "${candidates[@]}"; do
  command -v "${candidate}" >/dev/null 2>&1 || [ -x "${candidate}" ] || continue
  if [ "$("${candidate}" --version 2>/dev/null)" = "${pinned}" ]; then
    DOTNET_BIN="${candidate}"
    break
  fi
done
if [ -z "${DOTNET_BIN:-}" ]; then
  if [ -n "${DOTNET:-}" ]; then
    echo "FAIL: DOTNET=${DOTNET} does not report the pinned SDK ${pinned}." >&2
    echo "      Refusing to fall back to another dotnet — you named this one." >&2
  else
    echo "FAIL: no dotnet on this machine reports the pinned SDK ${pinned}." >&2
    echo "      Install ${pinned}, or set DOTNET=/path/to/dotnet and re-run." >&2
  fi
  echo "      global.json sets rollForward: disable, so a near miss is still a miss." >&2
  exit 2
fi
echo "SDK ${pinned} via ${DOTNET_BIN}"

# Restoring a net10.0-android36.0 or net10.0-ios project needs its workload, and
# WITHOUT it restore fails NETSDK1147 rather than degrading — so the lock file simply
# cannot be regenerated. This is also the reason Dependabot's own updater cannot
# refresh the Android head's lock file: its image installs SDKs and no workloads.
# Assert both up front so the failure names the missing workload instead of surfacing
# 200 lines into a restore.
missing=()
installed=$("${DOTNET_BIN}" workload list 2>/dev/null || true)
for workload in android ios; do
  if ! printf '%s\n' "${installed}" | awk -v w="${workload}" '$1 == w { found = 1 } END { exit !found }'; then
    missing+=("${workload}")
  fi
done
if [ "${#missing[@]}" -ne 0 ]; then
  echo "FAIL: missing workload(s): ${missing[*]}" >&2
  echo "      Install with: ${DOTNET_BIN} workload install ${missing[*]}" >&2
  echo "      Refusing to refresh anything — a partial refresh leaves the skipped" >&2
  echo "      head failing NU1004 while looking like the job was done." >&2
  exit 2
fi
echo "workloads present: android, ios"

for project in "${PROJECTS[@]}"; do
  echo "==> ${project}"
  "${DOTNET_BIN}" restore "${project}" --force-evaluate
done

echo
echo "Lock files after refresh:"
if git diff --quiet -- '**/packages.lock.json'; then
  echo "  (no change — they were already current)"
else
  git diff --stat -- '**/packages.lock.json'
  echo
  echo "Commit these alongside the manifest change. Do NOT commit a lock file from a"
  echo "'-r <rid>' build; re-run this script instead."
fi
