// Generated by portomatic scaffold from upstream Daqifi.Desktop/Exporter/OptimizedLoggingSessionExporter.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.IO;
using System.Text;
using Daqifi.Core.Logging.Export;
using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.Logger;
using Daqifi.Desktop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Daqifi.Desktop.Exporter;

/// <summary>
/// Thin desktop adapter around <see cref="CsvExporter"/>: builds an
/// <see cref="ISampleSource"/> from a <see cref="LoggingSession"/>, maps
/// desktop options into <see cref="CsvExportOptions"/>, and folds per-session
/// progress into the multi-session percentage the dialog expects.
/// </summary>
// @port: Daqifi.Desktop.Exporter.OptimizedLoggingSessionExporter
public class OptimizedLoggingSessionExporter
{
    #region Constants
    private const int BUFFER_SIZE = 1024 * 1024; // 1MB buffer for file writes

    /// <summary>
    /// Marks the file an export is written to before it is moved into place; a random suffix is
    /// appended to it, so the full name is <c>readings.csv.exporting-u3wp2sza.3vz</c>.
    /// <para>A sibling of the destination, not a temp-directory file:
    /// <see cref="File.Move(string, string, bool)"/> is only a rename — atomic, and no second copy of
    /// a large CSV — when both paths are on the same volume, which the system temp directory does not
    /// guarantee.</para>
    /// <para>Random rather than derived from the destination, because this method both TRUNCATES and
    /// DELETES that path: a predictable name would let an export destroy a file the app did not
    /// write, and would let two exports of the same destination clobber each other's staged rows —
    /// the very failure staging exists to prevent. The marker is there so a human who finds one can
    /// tell what it is.</para>
    /// </summary>
    private const string StagingMarker = ".exporting-";
    #endregion

    #region Static State
    // CsvExporter is stateless and ships from a sibling library that isn't registered with our DI
    // container. Caching one instance avoids re-allocating per export without forcing every caller
    // to inject it.
    private static readonly CsvExporter SharedCsvExporter = new();
    #endregion

    #region Private Fields
    private readonly AppLogger _appLogger = AppLogger.Instance;
    private readonly string _delimiter = DaqifiSettings.Instance.CsvDelimiter;
    private readonly IDbContextFactory<LoggingContext> _loggingContext;
    #endregion

    #region Constructors
    /// <summary>
    /// Creates an exporter that resolves its <see cref="LoggingContext"/> factory from
    /// <see cref="App.ServiceProvider"/>. Used in production where DI is wired up.
    /// </summary>
    public OptimizedLoggingSessionExporter()
    {
        if (App.ServiceProvider != null)
        {
            _loggingContext = App.ServiceProvider.GetRequiredService<IDbContextFactory<LoggingContext>>();
        }
    }

    /// <summary>
    /// Creates an exporter with an explicit <see cref="LoggingContext"/> factory. Used in tests
    /// that spin up a temp SQLite database.
    /// </summary>
    public OptimizedLoggingSessionExporter(IDbContextFactory<LoggingContext> loggingContext)
    {
        _loggingContext = loggingContext;
    }
    #endregion

    #region Public Methods
    /// <summary>
    /// Exports every sample in <paramref name="loggingSession"/> as one CSV row per timestamp.
    /// </summary>
    /// <param name="loggingSession">Session to export. May carry an in-memory <c>DataSamples</c>
    /// collection (test path) or just an <c>ID</c> the EF context will look up (production path).</param>
    /// <param name="filepath">Absolute path to the output CSV file.</param>
    /// <param name="exportRelativeTime">When true, the time column is seconds-since-first-sample; otherwise ISO 8601.</param>
    /// <param name="progress">Optional progress sink reporting overall percentage across all sessions.</param>
    /// <param name="cancellationToken">Token that aborts the export.</param>
    /// <param name="sessionIndex">Zero-based index of this session within a multi-session export.</param>
    /// <param name="totalSessions">Total number of sessions in this export run.</param>
    // @port: Daqifi.Desktop.Exporter.OptimizedLoggingSessionExporter.ExportLoggingSession
    public void ExportLoggingSession(LoggingSession loggingSession, string filepath, bool exportRelativeTime,
        IProgress<int> progress, CancellationToken cancellationToken, int sessionIndex, int totalSessions)
    {
        try
        {
            var source = TryBuildSource(loggingSession);
            if (source == null)
            {
                return;
            }

            var options = new CsvExportOptions
            {
                Delimiter = _delimiter,
                UseRelativeTime = exportRelativeTime,
            };

            RunExport(source, filepath, options, progress, cancellationToken, sessionIndex, totalSessions);
        }
        catch (OperationCanceledException)
        {
            // Let the viewmodel's cancellation handler record the breadcrumb.
            throw;
        }
        catch (Exception ex)
        {
            // Propagate after logging: this void overload is the desktop export path, and its sole
            // caller (ExportDialogViewModel) needs the failure to surface a truthful result instead of
            // a false "Export complete". The Try* overload keeps swallowing (returns false) for mobile.
            _appLogger.Error(ex,
                $"Exception in OptimizedExportLoggingSession (sessionId={loggingSession?.ID}, filepath={filepath}, relativeTime={exportRelativeTime})");
            throw;
        }
    }

    /// <summary>
    /// As <see cref="ExportLoggingSession"/>, but RETURNS whether the export completed
    /// successfully instead of throwing. Downstream addition (not in the upstream @port): the
    /// mobile export reports a per-session count to the user, so it needs a truthful signal for a
    /// mid-export failure (disk full, a transient DB/IO error after rows have already flushed)
    /// rather than an exception to catch around every session. The destination is safe either way —
    /// <see cref="RunExport"/> stages the CSV and moves it into place only on success — so false
    /// means "the destination still holds whatever it held before", never "the destination is now
    /// half a file". Returns false on any failure (logged);
    /// <see cref="OperationCanceledException"/> still propagates.
    /// </summary>
    public bool TryExportLoggingSession(LoggingSession loggingSession, string filepath, bool exportRelativeTime,
        IProgress<int> progress, CancellationToken cancellationToken, int sessionIndex, int totalSessions)
    {
        try
        {
            var source = TryBuildSource(loggingSession);
            if (source == null)
            {
                return false;
            }

            var options = new CsvExportOptions
            {
                Delimiter = _delimiter,
                UseRelativeTime = exportRelativeTime,
            };

            RunExport(source, filepath, options, progress, cancellationToken, sessionIndex, totalSessions);
            return true;
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            _appLogger.Error(ex,
                $"Exception in TryExportLoggingSession (sessionId={loggingSession?.ID}, filepath={filepath}, relativeTime={exportRelativeTime})");
            return false;
        }
    }

    /// <summary>
    /// Exports samples grouped into rolling windows of <paramref name="averageQuantity"/> samples,
    /// writing one averaged row per window. Trailing partial windows are flushed (a behavior change
    /// vs the legacy implementation, which silently dropped them).
    /// </summary>
    /// <param name="session">Session to export.</param>
    /// <param name="filepath">Absolute path to the output CSV file.</param>
    /// <param name="averageQuantity">Window size in samples. Must be positive; non-positive values short-circuit with a warning log.</param>
    /// <param name="exportRelativeTime">When true, the time column is seconds-since-first-sample; otherwise ISO 8601.</param>
    /// <param name="progress">Optional progress sink reporting overall percentage across all sessions.</param>
    /// <param name="cancellationToken">Token that aborts the export.</param>
    /// <param name="sessionIndex">Zero-based index of this session within a multi-session export.</param>
    /// <param name="totalSessions">Total number of sessions in this export run.</param>
    // @port: Daqifi.Desktop.Exporter.OptimizedLoggingSessionExporter.ExportAverageSamples
    public void ExportAverageSamples(LoggingSession session, string filepath, double averageQuantity,
        bool exportRelativeTime, IProgress<int> progress, CancellationToken cancellationToken, int sessionIndex, int totalSessions)
    {
        try
        {
            var window = (int)averageQuantity;
            if (window <= 0)
            {
                _appLogger.Warning(
                    $"Skipping average export: AverageWindow must be positive (was {averageQuantity}, sessionId={session?.ID}, filepath={filepath}).");
                return;
            }

            var source = TryBuildSource(session);
            if (source == null)
            {
                return;
            }

            var options = new CsvExportOptions
            {
                Delimiter = _delimiter,
                UseRelativeTime = exportRelativeTime,
                AverageWindow = window,
            };

            RunExport(source, filepath, options, progress, cancellationToken, sessionIndex, totalSessions);
        }
        catch (OperationCanceledException)
        {
            // Let the viewmodel's cancellation handler record the breadcrumb.
            throw;
        }
        catch (Exception ex)
        {
            // Propagate after logging (see ExportLoggingSession): the desktop VM needs the failure so it
            // never reports a false success on a locked or otherwise unwritable destination.
            _appLogger.Error(ex,
                $"Failed in OptimizedExportAverageSamples (sessionId={session?.ID}, filepath={filepath}, averageWindow={averageQuantity}, relativeTime={exportRelativeTime})");
            throw;
        }
    }
    #endregion

    #region Private Helpers
    /// <summary>
    /// Builds the appropriate <see cref="ISampleSource"/> for this session, or
    /// returns null if there is no usable data source. Mirrors the legacy
    /// "no file when there are no channels" behavior so empty sessions don't
    /// produce empty CSVs.
    /// </summary>
    // @port: Daqifi.Desktop.Exporter.OptimizedLoggingSessionExporter.TryBuildSource
    private ISampleSource TryBuildSource(LoggingSession loggingSession)
    {
        ISampleSource source;
        if (loggingSession.DataSamples?.Any() == true)
        {
            source = new LoggingSessionSampleSource(loggingSession, loggingSession.DataSamples);
        }
        else if (_loggingContext != null)
        {
            source = new LoggingSessionSampleSource(loggingSession, _loggingContext);
        }
        else
        {
            _appLogger.Warning("No data source available for export");
            return null;
        }

        if (source.GetChannels().Count == 0)
        {
            return null;
        }

        return source;
    }

    // @port: Daqifi.Desktop.Exporter.OptimizedLoggingSessionExporter.RunExport
    private static void RunExport(ISampleSource source, string filepath, CsvExportOptions options,
        IProgress<int> progress, CancellationToken cancellationToken, int sessionIndex, int totalSessions)
    {
        // Fold the [0..100] per-session progress that core reports into the
        // overall (sessionIndex + p/100) * (100/totalSessions) shape the dialog
        // already binds to. Match the legacy ceiling so we never exceed 100.
        IProgress<int> wrappedProgress = null;
        if (progress != null && totalSessions > 0)
        {
            wrappedProgress = new Progress<int>(p =>
            {
                var bounded = Math.Min(100, Math.Max(0, p));
                var overall = (int)((sessionIndex + bounded / 100.0) * (100.0 / totalSessions));
                progress.Report(overall);
            });
        }

        // Write-rename, NOT a write in place: stage the CSV beside the destination and move it over
        // only once the export has finished. Opening the destination itself (append: false) truncates
        // it the instant the stream is created — before the first row, and before the first
        // cancellation checkpoint — so a Cancel click destroyed the complete CSV the user had exported
        // earlier, and the dialog says nothing at all about a cancel (issue #236). The rename also
        // covers a mid-write failure and a crash: until it runs, the destination is the user's file.
        var stagingPath = filepath + StagingMarker + Path.GetRandomFileName();

        // Opened OUTSIDE the cleanup below, and with CreateNew rather than Create: the staging file
        // has to be one this call brought into existence, so that truncating it and deleting it can
        // never reach a file the app did not write. If this open fails, nothing of ours is on disk
        // and there is correspondingly nothing to clean up.
        var staging = File.Open(stagingPath, FileMode.CreateNew, FileAccess.Write, FileShare.Read);
        try
        {
            using (var writer = new StreamWriter(staging, Encoding.UTF8, BUFFER_SIZE))
            {
                SharedCsvExporter.ExportAsync(source, writer, options, wrappedProgress, cancellationToken)
                    .GetAwaiter()
                    .GetResult();
            }

            File.Move(stagingPath, filepath, overwrite: true);
        }
        catch
        {
            // Release the handle before unlinking — Windows refuses to delete an open file, and the
            // writer above has not closed the stream if constructing the writer is what failed.
            // Stream.Dispose is idempotent, so the ordinary path double-disposing is a no-op.
            staging.Dispose();
            DiscardStagedExport(stagingPath);
            throw;
        }
    }

    /// <summary>
    /// Removes the staging file this export created. Best effort on purpose: this runs while the real
    /// failure — or the user's cancellation — is unwinding, and the caller must see THAT, not whatever
    /// the cleanup hit. Hence the deliberately unfiltered catch: a narrower one lets an unexpected
    /// exception type escape and REPLACE the exception being reported.
    /// <para>Nothing sweeps up a staging file orphaned by a hard crash, which is the one case no
    /// <c>catch</c> reaches. That is deliberate: a sweep could not tell a dead file from another
    /// export's in-flight one, and deleting a path this call did not create is exactly what the
    /// random name exists to rule out. An orphan is inert and named so a human can recognise it.</para>
    /// </summary>
    private static void DiscardStagedExport(string stagingPath)
    {
        try
        {
            // File.Delete is a no-op when the file was never created (e.g. the staging open itself
            // failed), so there is nothing to check first.
            File.Delete(stagingPath);
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Warning(ex, $"Could not remove the partial export file '{stagingPath}'.");
        }
    }
    #endregion
}
