// Generated by portomatic scaffold from upstream Daqifi.Desktop/View/Flyouts/SummaryFlyout.xaml.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Avalonia.Controls;

namespace Daqifi.Desktop.View.Flyouts;

/// <summary>
/// Interaction logic for the summary flyout page
/// </summary>
// @port: Daqifi.Desktop.View.Flyouts.SummaryFlyout
public partial class SummaryFlyout : UserControl
{
    public SummaryFlyout()
    {
        InitializeComponent();
    }
}
