// Generated by portomatic scaffold from upstream Daqifi.Desktop/Device/WiFiDevice/DaqifiStreamingDevice.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.Device.WiFiDevice;

/// <summary>
/// WiFi streaming device that uses Core's DaqifiStreamingDevice directly for communication.
/// Unlike USB devices, WiFi devices don't need consumer swapping because SD card operations
/// are only available over USB.
/// </summary>
// @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice
public class DaqifiStreamingDevice : AbstractStreamingDevice
{
    // @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice.Port
    public int Port
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice.IsPowerOn
    public bool IsPowerOn
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice.ConnectionType
    public ConnectionType ConnectionType
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice.CreateCoreDevice
    protected CoreStreamingDevice? CreateCoreDevice() => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice.LogConnectFailure
    protected void LogConnectFailure(Exception ex) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice.Write
    public bool Write(string command) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice.SendMessage
    protected void SendMessage(IOutboundMessage<string> message) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice.ToString
    public string ToString() => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Device.WiFiDevice.DaqifiStreamingDevice.Equals
    public bool Equals(object obj) => throw new NotImplementedException();
}
