// Generated by portomatic scaffold from upstream Daqifi.Desktop/Helpers/BooleanToInverseBoolConverter.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.Globalization;
using Avalonia.Data.Converters;

namespace Daqifi.Desktop.Helpers;

// @port: Daqifi.Desktop.Helpers.BooleanToInverseBoolConverter
public class BooleanToInverseBoolConverter : IValueConverter
{
    // @port: Daqifi.Desktop.Helpers.BooleanToInverseBoolConverter.Convert
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return value is bool boolValue ? !boolValue : false;
    }

    // @port: Daqifi.Desktop.Helpers.BooleanToInverseBoolConverter.ConvertBack
    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return value is bool boolValue ? !boolValue : false;
    }
}
