// Generated by portomatic scaffold from upstream Daqifi.Desktop/Helpers/BooleanConverter.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.Helpers;

// @port: Daqifi.Desktop.Helpers.BooleanConverter<T>
public class BooleanConverter<T> : IValueConverter
{
    // @port: Daqifi.Desktop.Helpers.BooleanConverter<T>.True
    public T True
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Helpers.BooleanConverter<T>.False
    public T False
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Helpers.BooleanConverter<T>.Convert
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Helpers.BooleanConverter<T>.ConvertBack
    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) => throw new NotImplementedException();
}
