// Generated by portomatic scaffold from upstream Daqifi.Desktop/Helpers/MinMaxDownsampler.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using OxyPlot;

namespace Daqifi.Desktop.Helpers;

/// <summary>
/// Provides efficient min/max downsampling for large time-series datasets.
/// </summary>
// @port: Daqifi.Desktop.Helpers.MinMaxDownsampler
public class MinMaxDownsampler
{
    // @port: Daqifi.Desktop.Helpers.MinMaxDownsampler.Downsample
    public static List<DataPoint> Downsample(IReadOnlyList<DataPoint> points, int bucketCount) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Helpers.MinMaxDownsampler.Downsample
    public static List<DataPoint> Downsample(IReadOnlyList<DataPoint> points, int startIndex, int endIndex, int bucketCount) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Helpers.MinMaxDownsampler.FindVisibleRange
    public static (int startIndex, int endIndex) FindVisibleRange(IReadOnlyList<DataPoint> sortedPoints, double xMin, double xMax) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Helpers.MinMaxDownsampler.BinarySearchLower
    private static int BinarySearchLower(IReadOnlyList<DataPoint> points, double value) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Helpers.MinMaxDownsampler.BinarySearchUpper
    private static int BinarySearchUpper(IReadOnlyList<DataPoint> points, double value) => throw new NotImplementedException();
}
