// Generated by portomatic scaffold from upstream Daqifi.Desktop/ViewModels/ConnectionDialogViewModel.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Daqifi.Desktop.Device;
using Daqifi.Desktop.Device.Firmware;
using Daqifi.Desktop.Device.SerialDevice;
using Daqifi.Desktop.Device.WiFiDevice;
using Daqifi.Desktop.DialogService;
using Daqifi.Desktop.View;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Threading;
using System.Collections;
using System.Collections.ObjectModel;
using System.IO.Ports;
using System.Net;
using System.Net.Sockets;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.DependencyInjection;
using Daqifi.Core.Device.Discovery;
using CoreDeviceInfo = Daqifi.Core.Device.Discovery.IDeviceInfo;

namespace Daqifi.Desktop.ViewModels;

// @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel
public partial class ConnectionDialogViewModel : ObservableObject
{
    #region Private Variables
    private WiFiDeviceFinder? _wifiFinder;
    private Daqifi.Core.Device.Discovery.SerialDeviceFinder? _serialFinder;
    private CancellationTokenSource? _wifiDiscoveryCts;
    private CancellationTokenSource? _serialDiscoveryCts;
    private Task? _wifiDiscoveryTask;
    private Task? _serialDiscoveryTask;
    private readonly IDialogService _dialogService;

    /// <summary>
    /// App-global watcher that discovers and holds every sitting HID bootloader (keep-alive read pending)
    /// so Windows USB selective-suspend can't wedge one before the user flashes (daqifi-nyquist-firmware#568).
    /// The dialog binds its firmware list to <see cref="IBootloaderWatcher.Bootloaders"/> and opens the
    /// firmware dialog for the chosen device. Null only in unit tests that construct the view model
    /// without the DI container.
    /// </summary>
    private readonly IBootloaderWatcher? _watcher;

    /// <summary>
    /// True from the moment <see cref="ConnectHid"/> starts quiescing discovery until the HID firmware
    /// dialog it opened has closed. The watcher's own <see cref="IBootloaderWatcher.IsFlashInProgress"/>
    /// only covers the write itself (<c>PrepareFlashAsync</c> → lease disposal), so this covers the rest
    /// of the window <see cref="ConnectHid"/> deliberately quiesced — most importantly the time the user
    /// spends picking a .hex before the write starts, during which an auto-update ending would otherwise
    /// restart discovery and leave it running when they hit Upload (issue #777).
    /// <para>
    /// Volatile: the quiesce window spans awaits, so the write that clears it can land on a thread-pool
    /// thread when no dispatcher is present (unit tests), while a restart continuation reads it.
    /// </para>
    /// </summary>
    private volatile bool _hidFirmwareDialogOpen;

    /// <summary>
    /// How this view model marshals onto the UI thread. Nothing in the app ever reassigns it — it is an
    /// instance field rather than a direct call to <see cref="InvokeOnUiThread"/> only so a test can
    /// replace it by reflection (not <c>readonly</c>, because reflection may refuse an init-only field).
    /// <para>
    /// The seam is not cosmetic. Outside a running Avalonia application <c>Dispatcher.UIThread</c> binds
    /// itself to whichever thread touches it first and nothing ever pumps it, so
    /// <see cref="InvokeOnUiThread"/>'s blocking <c>Invoke</c> never returns when it is reached from any
    /// other thread — and xUnit gives no thread affinity across tests. Without this, the firmware-pause
    /// tests would deadlock the test host instead of failing.
    /// </para>
    /// </summary>
    private Action<Action> _marshalToUiThread = InvokeOnUiThread;

    [ObservableProperty]
    private bool _hasNoWiFiDevices = true;

    [ObservableProperty]
    private bool _hasNoSerialDevices = true;

    [ObservableProperty]
    private bool _hasNoHidDevices = true;

    private bool _closed;
    #endregion

    #region Events
    /// <summary>
    /// Raised when a connect command has completed successfully and the dialog should close.
    /// The view subscribes and closes itself. Not raised on empty input or failed connect.
    /// </summary>
    public event EventHandler? CloseRequested;
    #endregion

    #region Properties
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.AvailableWiFiDevices
    public ObservableCollection<DaqifiStreamingDevice> AvailableWiFiDevices { get; } = [];
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.AvailableSerialDevices
    public ObservableCollection<SerialStreamingDevice> AvailableSerialDevices { get; } = [];

    /// <summary>
    /// The sitting HID bootloaders the app-global watcher is holding, bound to the Firmware tab. The user
    /// picks one to flash. Falls back to an empty collection when no watcher is present (unit tests).
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.AvailableHidDevices
    public ReadOnlyObservableCollection<HeldBootloader> AvailableHidDevices => _watcher?.Bootloaders ?? _emptyHidDevices;

    private readonly ReadOnlyObservableCollection<HeldBootloader> _emptyHidDevices =
        new(new ObservableCollection<HeldBootloader>());

    [ObservableProperty]
    private string? _manualPortName;

    /// <summary>
    /// User-facing validation message for the Manual USB tab. Non-null when the entered
    /// COM port failed pre-flight validation (e.g. port not present on the system).
    /// Cleared automatically when the user edits <see cref="ManualPortName"/>.
    /// </summary>
    [ObservableProperty]
    private string? _manualPortError;

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ManualSerialDevice
    public SerialStreamingDevice ManualSerialDevice { get; set; }

    [ObservableProperty]
    private string? _manualIpAddress;

    /// <summary>
    /// User-facing validation message for the Manual WiFi tab. Non-null when the entered
    /// endpoint failed to resolve or the device did not respond (issue #517).
    /// Cleared automatically when the user edits <see cref="ManualIpAddress"/>.
    /// </summary>
    [ObservableProperty]
    private string? _manualWifiError;
    #endregion

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.OnManualPortNameChanged
    partial void OnManualPortNameChanged(string? value)
    {
        // Clear stale validation error as soon as the user starts editing the port name.
        if (!string.IsNullOrEmpty(ManualPortError))
        {
            ManualPortError = null;
        }
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.OnManualIpAddressChanged
    partial void OnManualIpAddressChanged(string? value)
    {
        // Clear stale validation error as soon as the user starts editing the address.
        if (!string.IsNullOrEmpty(ManualWifiError))
        {
            ManualWifiError = null;
        }
    }

    #region Constructor
    /// <summary>Creates the connection dialog view model using services resolved from the app container.</summary>
    public ConnectionDialogViewModel()
        : this(App.ServiceProvider.GetRequiredService<IDialogService>(), App.ServiceProvider?.GetService<IBootloaderWatcher>()) { }

    /// <summary>Creates the connection dialog view model.</summary>
    /// <param name="dialogService">Dialog service used to display modal dialogs.</param>
    /// <param name="watcher">Optional app-global bootloader watcher (null in unit tests without the DI container).</param>
    public ConnectionDialogViewModel(
        IDialogService dialogService,
        IBootloaderWatcher? watcher = null)
    {
        _dialogService = dialogService;
        _watcher = watcher;
        ConnectCommand = new AsyncRelayCommand<object>(ConnectAsync);
        ConnectSerialCommand = new AsyncRelayCommand<object>(ConnectSerialAsync);
        ConnectManualSerialCommand = new AsyncRelayCommand(ConnectManualSerialAsync);
        ConnectManualWifiCommand = new AsyncRelayCommand(ConnectManualWifiAsync);

        // The watcher holds bootloaders app-wide, so its list may already be populated before the dialog
        // opens. Reflect its current count and track changes so the "scanning…" overlay is accurate.
        // (Bootloaders is a ReadOnlyObservableCollection — its CollectionChanged is an explicit interface
        // member, so reach it via INotifyCollectionChanged.)
        if (_watcher != null)
        {
            HasNoHidDevices = _watcher.Bootloaders.Count == 0;
            ((System.Collections.Specialized.INotifyCollectionChanged)_watcher.Bootloaders).CollectionChanged
                += OnHidDevicesChanged;

            // A HID bootloader write can outlive the modal firmware dialog (closing it mid-flash only
            // cancels; the watcher's flash lease is released asynchronously afterwards). Subscribe so the
            // end of the write is a restart trigger of its own — without it, a resume refused while the
            // write was still running would never be retried (issue #777).
            _watcher.FlashInProgressChanged += OnBootloaderFlashInProgressChanged;
        }

        // Set up the duplicate device handler
        ConnectionManager.Instance.DuplicateDeviceHandler = HandleDuplicateDevice;

        // React to a firmware update starting/ending while this dialog is open: pause serial + WiFi
        // discovery for the duration so a per-cycle port probe can't steal the COM port during Core's
        // post-flash reconnect window (issue #738). The Start*Discovery guards below cover a dialog
        // opened mid-flash; this event covers a dialog already open when the flash starts.
        ConnectionManager.Instance.FirmwareUpdateInProgressChanged += OnFirmwareUpdateInProgressChanged;
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.OnFirmwareUpdateInProgressChanged
    private void OnFirmwareUpdateInProgressChanged(object? sender, EventArgs e)
    {
        // Marshal onto the UI thread: the event is raised from the firmware coordinator's async flow,
        // and the discovery start/stop paths mutate bound collections.
        _marshalToUiThread(() =>
        {
            if (_closed) { return; }

            if (ConnectionManager.Instance.IsFirmwareUpdateInProgress)
            {
                StopWiFiDiscovery();
                _ = StopSerialDiscoveryAsync();
            }
            else
            {
                // Auto-update finished — bring discovery back so the dialog keeps listing devices. The
                // restart carries the IsDiscoveryPausedForFirmware guard, so it is correctly refused when
                // a concurrent HID bootloader flash still needs the bus quiet (issue #777); that flash's
                // own release path calls the restart again.
                RestartDiscoveryAfterFirmwarePause();
            }
        });
    }

    /// <summary>
    /// Reacts to a HID bootloader write starting or finishing on the app-global watcher. Only the falling
    /// edge needs work: <see cref="ConnectHid"/> already drained both transports before the write could
    /// start, and <see cref="IsDiscoveryPausedForFirmware"/> keeps them from restarting while it runs.
    /// When it ends, retry the restart — the firmware dialog may already have closed (and had its own
    /// restart refused) while the write was still unwinding (issue #777).
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.OnBootloaderFlashInProgressChanged
    private void OnBootloaderFlashInProgressChanged(object? sender, EventArgs e)
    {
        _marshalToUiThread(() =>
        {
            if (_closed || _watcher == null || _watcher.IsFlashInProgress) { return; }

            RestartDiscoveryAfterFirmwarePause();
        });
    }

    /// <summary>
    /// Brings serial + WiFi discovery back after one of the firmware pause reasons cleared. Both starts
    /// re-check <see cref="IsDiscoveryPausedForFirmware"/>, so calling this while another reason is still
    /// active is a harmless no-op — and because every reason calls this when it clears, whichever one
    /// clears last performs the actual restart. That is what stops a guard from leaving discovery paused
    /// for the rest of the dialog's life.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.RestartDiscoveryAfterFirmwarePause
    private void RestartDiscoveryAfterFirmwarePause()
    {
        // The stop issued when the pause began may still be draining (a wedged port can hold the
        // discovery loop task past its cancellation, leaving _*DiscoveryTask incomplete), and
        // Start*Discovery refuses to start while that drain is in flight. So retry the start once the
        // drain completes rather than dropping it — otherwise discovery could stay stopped for the rest
        // of the dialog (issue #738).
        RestartDiscoveryWhenDrained(_wifiDiscoveryTask, StartWiFiDiscovery);
        RestartDiscoveryWhenDrained(_serialDiscoveryTask, StartSerialDiscovery);
    }

    /// <summary>
    /// True while some firmware operation needs this dialog's serial + WiFi discovery quiesced: a
    /// coordinator auto-update (<see cref="ConnectionManager.IsFirmwareUpdateInProgress"/>), an open HID
    /// firmware dialog, or a HID bootloader write still in flight on the app-global watcher. The last two
    /// are invisible to the connection manager — a manual flash never sets <c>DeviceBeingUpdated</c> — so
    /// gating on the connection manager alone let one device's auto-update ending re-open COM ports and
    /// resume WiFi broadcasts in the middle of another device's HID flash (issue #777).
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.IsDiscoveryPausedForFirmware
    private bool IsDiscoveryPausedForFirmware =>
        ConnectionManager.Instance.IsFirmwareUpdateInProgress
        || _hidFirmwareDialogOpen
        || _watcher?.IsFlashInProgress == true;

    /// <summary>
    /// Starts a discovery transport, deferring the start until any in-flight stop/drain for that
    /// transport completes. The drain signal is the port's discovery-loop task (nulled by its own
    /// completion continuation), so a non-completed task means "still winding down". <paramref name="start"/>
    /// carries its own idempotency + firmware-in-progress guards, so a redundant or now-invalid call is a
    /// harmless no-op.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.RestartDiscoveryWhenDrained
    private void RestartDiscoveryWhenDrained(Task? drainTask, Action start)
    {
        if (drainTask is { IsCompleted: false })
        {
            drainTask.ContinueWith(
                _ => _marshalToUiThread(start),
                CancellationToken.None,
                TaskContinuationOptions.None,
                TaskScheduler.Default);
            return;
        }

        start();
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.OnHidDevicesChanged
    private void OnHidDevicesChanged(object? sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
    {
        HasNoHidDevices = AvailableHidDevices.Count == 0;
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.StartConnectionFinders
    public void StartConnectionFinders()
    {
        Common.Loggers.AppLogger.Instance.AddBreadcrumb("discovery", "Device discovery started");

        StartWiFiDiscovery();
        StartSerialDiscovery();
        // HID bootloader discovery + holding is the app-global watcher's job (started at app startup),
        // not the dialog's — the dialog only binds to AvailableHidDevices.
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.StartWiFiDiscovery
    private void StartWiFiDiscovery()
    {
        // Idempotent while actually running; allow a restart once the prior loop has completed (e.g.
        // it was drained around a firmware flash), otherwise a stale task reference blocks discovery.
        if (_closed || _wifiDiscoveryTask is { IsCompleted: false }) { return; }

        // Don't run discovery during any firmware operation: its per-cycle bus probing can starve the
        // flash / steal the reconnecting COM port (issue #738) and can starve a HID bootloader's I/O
        // mid-write (issue #777). Covers a dialog opened mid-flash; the release path of whichever pause
        // reason clears last restarts discovery.
        if (IsDiscoveryPausedForFirmware) { return; }

        // Restart-after-drain: dispose the prior finder/CTS before replacing them so we never leak a
        // subscribed finder or an undisposed CancellationTokenSource.
        if (_wifiFinder != null) { _wifiFinder.DeviceDiscovered -= HandleCoreWifiDeviceDiscovered; _wifiFinder.Dispose(); }
        _wifiDiscoveryCts?.Dispose();

        // Drop stale devices from the previous discovery session when the finder is torn down and
        // recreated (the dialog-open / firmware-flash resume path): the bound list otherwise outlives
        // the finder that populated it and keeps devices that are no longer answering. The per-add MAC
        // dedup guard in HandleWifiDeviceFound is RETAINED for the case this clear does not cover —
        // RunContinuousWiFiDiscoveryAsync reuses this one finder across many DiscoverAsync sweeps and
        // Core's dedup set is per-sweep, so a device already listed can re-fire on a later sweep (e.g.
        // after a transient receive-socket error ends a sweep early), and this clear, which runs only
        // on finder recreate, would not stop that duplicate. (issue #621)
        // Routed through the UI marshal like every other AvailableWiFiDevices mutation.
        _marshalToUiThread(() =>
        {
            AvailableWiFiDevices.Clear();
            HasNoWiFiDevices = true;
        });

        _wifiFinder = new WiFiDeviceFinder(30303);
        _wifiDiscoveryCts = new CancellationTokenSource();
        _wifiFinder.DeviceDiscovered += HandleCoreWifiDeviceDiscovered;

        var wifiTask = RunContinuousWiFiDiscoveryAsync(_wifiDiscoveryCts.Token);
        _wifiDiscoveryTask = wifiTask;
        // Clear the tracked task only once it has actually finished — not merely after
        // StopWiFiDiscoveryAsync's drain timeout — so a cycle still blocked in the finder's
        // synchronous prefix (issue #685) can't be raced by a subsequent StartWiFiDiscovery
        // while it may still be using the finder/socket.
        _ = wifiTask.ContinueWith(_ =>
        {
            if (ReferenceEquals(_wifiDiscoveryTask, wifiTask)) { _wifiDiscoveryTask = null; }
        }, TaskScheduler.Default);
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.StartSerialDiscovery
    private void StartSerialDiscovery()
    {
        if (_closed || _serialDiscoveryTask is { IsCompleted: false }) { return; }

        // Don't probe COM ports during a firmware update: Core opens/reconnects the device's port
        // itself across the flash, and the SerialDeviceFinder opens every DAQiFi VID/PID port each
        // cycle — a probe landing in Core's JumpingToApp reconnect window steals the port and strands
        // the update in a timeout (issue #738), and the same probing can starve a HID bootloader's I/O
        // mid-write on another device (issue #777). Covers a dialog opened mid-flash; the release path
        // of whichever pause reason clears last restarts discovery.
        if (IsDiscoveryPausedForFirmware) { return; }

        if (_serialFinder != null) { _serialFinder.DeviceDiscovered -= HandleCoreSerialDeviceDiscovered; _serialFinder.Dispose(); }
        _serialDiscoveryCts?.Dispose();

        _serialFinder = new Daqifi.Core.Device.Discovery.SerialDeviceFinder();
        _serialDiscoveryCts = new CancellationTokenSource();
        _serialFinder.DeviceDiscovered += HandleCoreSerialDeviceDiscovered;

        var serialTask = RunContinuousSerialDiscoveryAsync(_serialDiscoveryCts.Token);
        _serialDiscoveryTask = serialTask;
        // Same reasoning as StartWiFiDiscovery above: only the task's own completion clears the
        // tracked reference, so a discovery cycle still blocked on a wedged COM port can't be
        // raced by a subsequent StartSerialDiscovery (e.g. the firmware flash resume path) while
        // it may still hold the port.
        _ = serialTask.ContinueWith(_ =>
        {
            if (ReferenceEquals(_serialDiscoveryTask, serialTask)) { _serialDiscoveryTask = null; }
        }, TaskScheduler.Default);
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.RunContinuousWiFiDiscoveryAsync
    private async Task RunContinuousWiFiDiscoveryAsync(CancellationToken cancellationToken)
    {
        try
        {
            while (!cancellationToken.IsCancellationRequested && _wifiFinder != null)
            {
                // Task.Run for the same reason as the serial loop below: keep any
                // synchronous-before-first-await work inside Core's finder off the UI thread.
                var finder = _wifiFinder;
                await Task.Run(() => finder.DiscoverAsync(cancellationToken), cancellationToken);
                // Brief pause before next discovery cycle
                await Task.Delay(3000, cancellationToken);
            }
        }
        catch (OperationCanceledException)
        {
            // Expected when cancelled
        }
        catch (ObjectDisposedException)
        {
            // Expected when finder is disposed during discovery
        }
        catch (Exception ex)
        {
            Common.Loggers.AppLogger.Instance.Error(ex, "Error in WiFi discovery loop");
        }
    }

    // Watchdog bounds (serial loop only): with Daqifi.Core 1.0.0 a wedged CDC device hangs
    // DiscoverAsync forever (core#294 — SerialPort.Open() stuck in native GetCommState, no
    // per-port timeout, and DeviceDiscovered gated behind Task.WhenAll, so one zombie port
    // silences every healthy device). Remove once the app consumes a core release with the
    // #294 fix (PR daqifi-core#295).
    private const int SerialSweepWatchdogMs = 10_000;
    private const int MaxConsecutiveWatchdogTrips = 3;

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.RunContinuousSerialDiscoveryAsync
    private async Task RunContinuousSerialDiscoveryAsync(CancellationToken cancellationToken)
    {
        var consecutiveTrips = 0;
        try
        {
            while (!cancellationToken.IsCancellationRequested && _serialFinder != null)
            {
                // Task.Run: Core's SerialDeviceFinder.DiscoverAsync is async-in-name-only up to its
                // first await — it synchronously SerialPort.Open()s every candidate port on the
                // CALLING thread. Called bare after the Task.Delay resume, that thread is the UI
                // thread, and a wedged CDC device (Open() stuck in native GetCommState — observed
                // live 2026-07-13) freezes the whole app. Upstream WPF has the same latent bug.
                var finder = _serialFinder;
                var sweep = Task.Run(() => finder.DiscoverAsync(cancellationToken), cancellationToken);

                var winner = await Task.WhenAny(sweep, Task.Delay(SerialSweepWatchdogMs, cancellationToken));
                if (winner != sweep)
                {
                    if (cancellationToken.IsCancellationRequested)
                    {
                        // Stop path (step-3.5 port audit): the cancelled Task.Delay wins
                        // this WhenAny synchronously inside Cancel(), which used to exit
                        // the loop while the sweep still HELD the COM port (its probe's
                        // port-closing finally takes up to ~1s) — so StopSerialDiscovery's
                        // "port fully released" contract broke and Connect raced the
                        // abandoned probe into a false port-in-use failure. Drain the
                        // sweep (bounded) before surfacing cancellation; observe its
                        // outcome either way so an abandoned fault can't go unobserved.
                        _ = sweep.ContinueWith(
                            static t => _ = t.Exception,
                            CancellationToken.None,
                            TaskContinuationOptions.NotOnRanToCompletion | TaskContinuationOptions.ExecuteSynchronously,
                            TaskScheduler.Default);
                        try { await sweep.WaitAsync(TimeSpan.FromSeconds(3), CancellationToken.None); }
                        catch (TimeoutException) { /* wedged probe — proceed; Connect on OTHER ports is unaffected */ }
                        catch (OperationCanceledException) { /* sweep observed the same token — drained */ }
                        catch { /* probe faults are probe-misses, not stop failures */ }
                        cancellationToken.ThrowIfCancellationRequested();
                    }

                    consecutiveTrips++;
                    Common.Loggers.AppLogger.Instance.Warning(
                        $"Serial discovery sweep exceeded {SerialSweepWatchdogMs / 1000}s " +
                        $"(trip {consecutiveTrips}/{MaxConsecutiveWatchdogTrips}) — a serial port is " +
                        "likely wedged; USB discovery may be incomplete.");
                    // Observe the abandoned sweep's eventual fault so it can't surface as an
                    // UnobservedTaskException. Its stuck probe thread is uncancellable; the
                    // abandoned finder leaks with it (bounded by MaxConsecutiveWatchdogTrips,
                    // and intentionally NOT disposed — disposing its in-use semaphore would
                    // just add an ObjectDisposedException to the abandoned task).
                    _ = sweep.ContinueWith(
                        static t => _ = t.Exception,
                        CancellationToken.None,
                        TaskContinuationOptions.NotOnRanToCompletion | TaskContinuationOptions.ExecuteSynchronously,
                        TaskScheduler.Default);

                    if (consecutiveTrips >= MaxConsecutiveWatchdogTrips)
                    {
                        Common.Loggers.AppLogger.Instance.Error(
                            "Serial discovery stopped after repeated wedged sweeps. Power-cycle the " +
                            "unresponsive USB device and reopen the connection dialog.");
                        return;
                    }

                    // Rebuild the finder so healthy ports get fresh sweeps on the next iteration.
                    finder.DeviceDiscovered -= HandleCoreSerialDeviceDiscovered;
                    _serialFinder = new Daqifi.Core.Device.Discovery.SerialDeviceFinder();
                    _serialFinder.DeviceDiscovered += HandleCoreSerialDeviceDiscovered;
                    continue;
                }

                consecutiveTrips = 0;
                await sweep; // propagate faults/cancellation exactly like the bare await did
                // Serial discovery is quick, pause longer between scans
                await Task.Delay(2000, cancellationToken);
            }
        }
        catch (OperationCanceledException)
        {
            // Expected when cancelled
        }
        catch (ObjectDisposedException)
        {
            // Expected when finder is disposed during discovery
        }
        catch (Exception ex)
        {
            Common.Loggers.AppLogger.Instance.Error(ex, "Error in Serial discovery loop");
        }
    }

    #endregion

    #region Commands

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ConnectCommand
    public IAsyncRelayCommand ConnectCommand { get; }
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ConnectSerialCommand
    public IAsyncRelayCommand ConnectSerialCommand { get; }
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ConnectManualSerialCommand
    public IAsyncRelayCommand ConnectManualSerialCommand { get; }
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ConnectManualWifiCommand
    public IAsyncRelayCommand ConnectManualWifiCommand { get; }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ConnectAsync
    private async Task ConnectAsync(object? selectedItems)
    {
        var selectedDevices = ToStreamingDevices(selectedItems);
        if (selectedDevices.Count == 0) { return; }

        StopWiFiDiscovery();

        foreach (var device in selectedDevices)
        {
            await ConnectionManager.Instance.Connect(device);
        }

        RaiseCloseRequested();
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ConnectSerialAsync
    private async Task ConnectSerialAsync(object? selectedItems)
    {
        var selectedDevices = ToStreamingDevices(selectedItems);
        if (selectedDevices.Count == 0) { return; }

        await StopSerialDiscoveryAsync();

        foreach (var device in selectedDevices)
        {
            await ConnectionManager.Instance.Connect(device);
        }

        RaiseCloseRequested();
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ConnectManualSerialAsync
    private async Task ConnectManualSerialAsync()
    {
        ManualPortError = null;

        if (string.IsNullOrWhiteSpace(ManualPortName)) { return; }

        var portName = ManualPortName.Trim();

        // Port enumeration reads the registry; keep it off the UI thread per the
        // app's async/UI-responsiveness standards (this runs before the first await).
        if (!await Task.Run(() => IsPortAvailable(portName)))
        {
            // Avoid the FileNotFoundException round-trip from SerialPort.Open by
            // pre-checking against the system's enumerated ports. Surface a friendly
            // message in the dialog instead of silently closing.
            ManualPortError =
                $"Port '{portName}' is not available. " +
                "Plug in the device or check Device Manager for the correct port name.";
            Common.Loggers.AppLogger.Instance.Warning(
                $"Manual serial connect rejected: port '{portName}' is not present on the system.");
            return;
        }

        // Drain serial discovery before opening the port — same exclusive-access guarantee the
        // discovered-device path (ConnectSerialAsync) already takes. The continuous SerialDeviceFinder
        // loop opens/probes every DAQiFi-VID/PID COM port each cycle (and a probe on a port that never
        // answers the identify sits there holding the handle), so without this the app races ITSELF for
        // the port and the open fails "in use by another process". This is the common path for a device
        // stranded in transparent mode: it isn't auto-discovered, so the user connects to it by port
        // here while discovery is still hammering it.
        await StopSerialDiscoveryAsync();

        ManualSerialDevice = new SerialStreamingDevice(portName);
        await ConnectionManager.Instance.Connect(ManualSerialDevice);

        // Post-connect status check covers failures the pre-flight enumeration cannot
        // catch — most notably "port exists but is held by another process", which
        // SerialStreamingDevice.Connect now classifies as a Warning (no Sentry capture).
        // Without this, the dialog would close silently and the user would have no idea
        // the connection failed.
        if (ConnectionManager.Instance.ConnectionStatus == DAQiFiConnectionStatus.Error)
        {
            ManualPortError =
                $"Could not connect to '{portName}'. " +
                "The port may be in use by another application or the device is not responding.";
            // Restart discovery so the dialog keeps finding devices after a failed manual attempt.
            StartSerialDiscovery();
            return;
        }

        RaiseCloseRequested();
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.IsPortAvailable
    private static bool IsPortAvailable(string portName)
    {
        try
        {
            return SerialPort.GetPortNames()
                .Any(p => string.Equals(p, portName, StringComparison.OrdinalIgnoreCase));
        }
        catch (Exception ex)
        {
            // If port enumeration itself fails, fall back to the connect attempt rather
            // than blocking the user — Connect() will surface its own error path.
            Common.Loggers.AppLogger.Instance.Warning(ex,
                "Failed to enumerate serial ports during manual-connect validation.");
            return true;
        }
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ConnectManualWifiAsync
    private async Task ConnectManualWifiAsync()
    {
        ManualWifiError = null;

        if (string.IsNullOrWhiteSpace(ManualIpAddress)) { return; }

        var endpointInput = ManualIpAddress.Trim();
        IPAddress? ipAddress;
        try
        {
            ipAddress = await ResolveManualWifiEndpointAsync(endpointInput);
        }
        catch (ArgumentException ex)
        {
            ManualWifiError = $"'{endpointInput}' is not a valid IP address or host name.";
            Common.Loggers.AppLogger.Instance.Warning(ex,
                $"Manual WiFi connection requires a valid IP address or host name. " +
                $"Received '{ManualIpAddress}'");
            return;
        }
        catch (SocketException ex)
        {
            ManualWifiError = $"Could not resolve '{endpointInput}'. Check the address and try again.";
            Common.Loggers.AppLogger.Instance.Warning(ex,
                $"Failed to resolve manual WiFi endpoint '{ManualIpAddress}'");
            return;
        }
        catch (Exception ex)
        {
            Common.Loggers.AppLogger.Instance.Error(
                ex,
                $"Unexpected error while resolving manual WiFi endpoint '{ManualIpAddress}'.");
            throw;
        }

        if (ipAddress == null)
        {
            ManualWifiError = $"Could not resolve '{endpointInput}'. Check the address and try again.";
            Common.Loggers.AppLogger.Instance.Warning(
                $"Manual WiFi endpoint '{ManualIpAddress}' did not resolve to an IP address.");
            return;
        }

        // Connect directly with the resolved endpoint instead of fabricating a discovery-shaped
        // IDeviceInfo — the device wrapper drives the connection through Core's DaqifiDeviceFactory
        // (issue #620). The hardcoded 9760 data port is tracked separately in issue #615.
        const int MANUAL_WIFI_DATA_PORT = 9760;
        var device = new DaqifiStreamingDevice(ipAddress, MANUAL_WIFI_DATA_PORT, "Manual IP Device");
        await ConnectionManager.Instance.Connect(device);

        // Post-connect status check mirrors the manual-serial path: an unreachable device
        // (connect timeout — issue #517) must keep the dialog open with an inline message
        // instead of closing silently.
        if (ConnectionManager.Instance.ConnectionStatus == DAQiFiConnectionStatus.Error)
        {
            ManualWifiError =
                $"Could not connect to '{endpointInput}'. " +
                "Verify the device is powered on and reachable on this network.";
            return;
        }

        RaiseCloseRequested();
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ToStreamingDevices
    private static List<IStreamingDevice> ToStreamingDevices(object? selectedItems)
    {
        if (selectedItems is not IEnumerable enumerable) { return []; }
        return enumerable.Cast<IStreamingDevice>().ToList();
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.RaiseCloseRequested
    private void RaiseCloseRequested()
    {
        CloseRequested?.Invoke(this, EventArgs.Empty);
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ResolveManualWifiEndpointAsync
    private static async Task<IPAddress?> ResolveManualWifiEndpointAsync(string endpointInput)
    {
        if (IPAddress.TryParse(endpointInput, out var parsedIpAddress))
        {
            return parsedIpAddress;
        }

        var resolvedAddresses = await Dns.GetHostAddressesAsync(endpointInput);
        return resolvedAddresses.FirstOrDefault(
            address => address.AddressFamily == AddressFamily.InterNetwork)
            ?? resolvedAddresses.FirstOrDefault();
    }

    [RelayCommand]
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.ConnectHid
    private async Task ConnectHid(object selectedItems)
    {
        if (selectedItems is not IEnumerable enumerable) { return; }

        var bootloader = enumerable.Cast<HeldBootloader>().FirstOrDefault();
        if (bootloader == null) { return; }

        await RunWithHidFlashQuiescedAsync(() =>
        {
            var firmwareDialogViewModel = new FirmwareDialogViewModel(bootloader.DisplayName, bootloader.DevicePath);
            return _dialogService.ShowDialogAsync<FirmwareDialog>(this, firmwareDialogViewModel);
        });
    }

    /// <summary>
    /// Runs the (modal) HID firmware dialog with WiFi + serial discovery quiesced for the whole window,
    /// then restores discovery.
    /// </summary>
    /// <param name="showFirmwareDialogAsync">
    /// Shows the modal firmware dialog; the returned task completes once it has closed. Upstream takes a
    /// plain <c>Action</c> because WPF's <c>ShowDialog</c> blocks — Avalonia's dialogs are async-only, so
    /// the same "run this while quiesced" contract needs a <see cref="Func{Task}"/> here.
    /// </param>
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.RunWithHidFlashQuiescedAsync
    private async Task RunWithHidFlashQuiescedAsync(Func<Task> showFirmwareDialogAsync)
    {
        // Pause WiFi + serial discovery while the firmware dialog is open: their per-cycle bus probing
        // (serial opens/probes every COM port; WiFi UDP-broadcasts) can starve the bootloader's HID I/O
        // mid-flash. HID discovery and the per-device holds belong to the app-global watcher — it pauses
        // HID discovery and releases the target's hold itself when the flash starts
        // (FirmwareDialogViewModel → BootloaderWatcher.PrepareFlashAsync), while every OTHER held
        // bootloader stays wedge-proof. Awaiting the drains matters: cancel/dispose does NOT abort an
        // in-flight DiscoverAsync cycle, so a still-running probe could otherwise hold a handle when the
        // flasher fires.
        //
        // The flag goes up BEFORE the drains: a coordinator auto-update of a different device can finish
        // while we are awaiting them, and its FirmwareUpdateInProgressChanged handler would otherwise
        // restart the very discovery we are tearing down (issue #777).
        _hidFirmwareDialogOpen = true;
        try
        {
            await StopWiFiDiscoveryAsync();
            await StopSerialDiscoveryAsync();

            await showFirmwareDialogAsync();
        }
        finally
        {
            // Resume discovery once the flash dialog closes so the device list stays live. The watcher
            // keeps holding the bootloader (or drops it if the flash succeeded) on its own. If an
            // auto-update or a still-unwinding bootloader write is holding the bus, this restart is
            // refused and that operation's own release path retries it.
            _hidFirmwareDialogOpen = false;
            RestartDiscoveryAfterFirmwarePause();
        }
    }
    #endregion

    #region Core Device Discovery Event Handlers

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.HandleCoreWifiDeviceDiscovered
    internal void HandleCoreWifiDeviceDiscovered(object? sender, DeviceDiscoveredEventArgs e)
    {
        try
        {
            Common.Loggers.AppLogger.Instance.AddBreadcrumb("discovery", $"WiFi device found: {e.DeviceInfo.Name}");
            var wifiDevice = new DaqifiStreamingDevice(e.DeviceInfo);
            HandleWifiDeviceFound(sender, wifiDevice);
        }
        catch (Exception ex)
        {
            Common.Loggers.AppLogger.Instance.Error(ex, "Error handling WiFi device discovery");
        }
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.HandleCoreSerialDeviceDiscovered
    private void HandleCoreSerialDeviceDiscovered(object? sender, DeviceDiscoveredEventArgs e)
    {
        try
        {
            Common.Loggers.AppLogger.Instance.AddBreadcrumb("discovery", $"Serial device found: {e.DeviceInfo.Name}");
            AddSerialDeviceFromDiscovery(e.DeviceInfo);
        }
        catch (Exception ex)
        {
            Common.Loggers.AppLogger.Instance.Error(ex, "Error handling Serial device discovery");
        }
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.AddSerialDeviceFromDiscovery
    private void AddSerialDeviceFromDiscovery(CoreDeviceInfo deviceInfo)
    {
        var portName = deviceInfo.PortName?.Trim();
        if (string.IsNullOrWhiteSpace(portName))
        {
            return;
        }

        _marshalToUiThread(() =>
        {
            var existing = FindSerialDeviceByPortName(portName);
            if (existing == null)
            {
                var serialDevice = new SerialStreamingDevice(
                    portName,
                    deviceInfo.Name,
                    deviceInfo.SerialNumber,
                    deviceInfo.FirmwareVersion)
                {
                    LocationKey = deviceInfo.LocationKey
                };
                AvailableSerialDevices.Add(serialDevice);
                if (HasNoSerialDevices) { HasNoSerialDevices = false; }
                Common.Loggers.AppLogger.Instance.Information(
                    $"Added DAQiFi device on {portName}: {serialDevice.Name} (S/N: {serialDevice.DeviceSerialNo})");
                return;
            }

            UpdateSerialDeviceMetadata(existing, portName, deviceInfo);
        });
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.FindSerialDeviceByPortName
    private SerialStreamingDevice? FindSerialDeviceByPortName(string portName)
    {
        return AvailableSerialDevices.FirstOrDefault(d =>
            d.Port?.PortName.Equals(portName, StringComparison.OrdinalIgnoreCase) == true);
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.UpdateSerialDeviceMetadata
    private static void UpdateSerialDeviceMetadata(
        SerialStreamingDevice serialDevice,
        string portName,
        CoreDeviceInfo deviceInfo)
    {
        serialDevice.Name = !string.IsNullOrWhiteSpace(deviceInfo.Name)
            ? deviceInfo.Name
            : portName;
        serialDevice.DeviceSerialNo = deviceInfo.SerialNumber;
        serialDevice.DeviceVersion = deviceInfo.FirmwareVersion;

        // Only overwrite with a resolved value: a refresh pass that couldn't resolve a location
        // (deviceInfo.LocationKey null) must not erase a previously-captured one, or an auto-update
        // triggered afterward would lose its firmware-targeting key.
        if (!string.IsNullOrWhiteSpace(deviceInfo.LocationKey))
        {
            serialDevice.LocationKey = deviceInfo.LocationKey;
        }
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.InvokeOnUiThread
    private static void InvokeOnUiThread(Action action)
    {
        if (Dispatcher.UIThread.CheckAccess())
        {
            action();
            return;
        }

        Dispatcher.UIThread.Invoke(action);
    }

    #endregion

    #region Desktop Device Event Handlers

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.HandleWifiDeviceFound
    private void HandleWifiDeviceFound(object sender, IDevice device)
    {
        if (device is not DaqifiStreamingDevice wifiDevice)
        {
            return;
        }

        _marshalToUiThread(() =>
        {
            // Dedup by MAC: Core's WiFiDeviceFinder dedups only within a single DiscoverAsync sweep
            // (its discovered set is per-call), but RunContinuousWiFiDiscoveryAsync reuses this finder
            // across sweeps while AvailableWiFiDevices persists — StartWiFiDiscovery's clear fires only
            // on finder recreate, not per sweep — so a device already listed can re-fire on a later
            // sweep and would be added twice without this guard. (issue #621)
            if (AvailableWiFiDevices.Any(d => d.MacAddress == wifiDevice.MacAddress)) return;
            AvailableWiFiDevices.Add(wifiDevice);
            if (HasNoWiFiDevices) { HasNoWiFiDevices = false; }
        });
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.Close
    public void Close()
    {
        // Guards against concurrent/double dispose when the window closes while
        // a connect command is still in flight (either path may call this).
        if (_closed) { return; }
        _closed = true;

        StopWiFiDiscovery();
        // Fire-and-forget: cancel discovery and clean up without waiting for task completion
        _ = StopSerialDiscoveryAsync();

        ConnectionManager.Instance.FirmwareUpdateInProgressChanged -= OnFirmwareUpdateInProgressChanged;

        // HID bootloader holds are owned by the app-global watcher and intentionally persist after the
        // dialog closes (so a sitting bootloader stays wedge-proof). Only unsubscribe this dialog from
        // the watcher's list.
        if (_watcher != null)
        {
            ((System.Collections.Specialized.INotifyCollectionChanged)_watcher.Bootloaders).CollectionChanged
                -= OnHidDevicesChanged;
            _watcher.FlashInProgressChanged -= OnBootloaderFlashInProgressChanged;
        }
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.StopWiFiDiscovery
    private void StopWiFiDiscovery()
    {
        _wifiDiscoveryCts?.Cancel();

        if (_wifiFinder != null)
        {
            _wifiFinder.DeviceDiscovered -= HandleCoreWifiDeviceDiscovered;
            _wifiFinder.Dispose();
            _wifiFinder = null;
        }

        _wifiDiscoveryCts?.Dispose();
        _wifiDiscoveryCts = null;
    }

    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.StopSerialDiscoveryAsync
    private async Task StopSerialDiscoveryAsync()
    {
        _serialDiscoveryCts?.Cancel();

        // Wait for the discovery task to complete so that the serial port is fully released
        if (_serialDiscoveryTask != null)
        {
            try
            {
                await _serialDiscoveryTask.WaitAsync(TimeSpan.FromSeconds(5));
            }
            catch (TimeoutException)
            {
                // The loop's Task.Run may still be blocked in the finder's synchronous prefix (a
                // wedged COM port, issue #685). Leave _serialDiscoveryTask set — its own
                // continuation (see StartSerialDiscovery) clears it once it truly finishes — so
                // Start*Discovery's guard keeps refusing a competing discovery generation against
                // the same port, and skip disposing the finder/CTS below since the still-running
                // call may be using them.
                Common.Loggers.AppLogger.Instance.Warning("Serial discovery task did not complete within timeout");
                return;
            }
            catch (OperationCanceledException)
            {
                // Expected on cancellation
            }
            catch (ObjectDisposedException)
            {
                // Expected during shutdown
            }
            catch (Exception ex)
            {
                Common.Loggers.AppLogger.Instance.Error(ex, "Unexpected error while stopping serial discovery");
            }
        }

        if (_serialFinder != null)
        {
            _serialFinder.DeviceDiscovered -= HandleCoreSerialDeviceDiscovered;
            _serialFinder.Dispose();
            _serialFinder = null;
        }

        _serialDiscoveryCts?.Dispose();
        _serialDiscoveryCts = null;

    }

    /// <summary>
    /// Stops WiFi discovery and waits for the in-flight discovery cycle to drain before returning —
    /// the async counterpart to <see cref="StopWiFiDiscovery"/>, used before a bootloader flash so a
    /// running UDP discovery cycle isn't still live when the flash begins. Mirrors
    /// <see cref="StopSerialDiscoveryAsync"/>.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.StopWiFiDiscoveryAsync
    private async Task StopWiFiDiscoveryAsync()
    {
        _wifiDiscoveryCts?.Cancel();

        if (_wifiDiscoveryTask != null)
        {
            try
            {
                await _wifiDiscoveryTask.WaitAsync(TimeSpan.FromSeconds(5));
            }
            catch (TimeoutException)
            {
                // Same reasoning as StopSerialDiscoveryAsync above: leave _wifiDiscoveryTask set
                // (its StartWiFiDiscovery continuation clears it once it truly finishes) and skip
                // disposing the finder/CTS below, since the still-running Task.Run may be using them.
                Common.Loggers.AppLogger.Instance.Warning("WiFi discovery task did not complete within timeout");
                return;
            }
            catch (OperationCanceledException) { }
            catch (ObjectDisposedException) { }
            catch (Exception ex)
            {
                Common.Loggers.AppLogger.Instance.Error(ex, "Unexpected error while stopping WiFi discovery");
            }
        }

        if (_wifiFinder != null)
        {
            _wifiFinder.DeviceDiscovered -= HandleCoreWifiDeviceDiscovered;
            _wifiFinder.Dispose();
            _wifiFinder = null;
        }

        _wifiDiscoveryCts?.Dispose();
        _wifiDiscoveryCts = null;
    }

    /// <summary>
    /// Handles duplicate device detection by showing a dialog to the user
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.ConnectionDialogViewModel.HandleDuplicateDevice
    // Async divergence: Avalonia ShowDialog is async-only; ConnectionManager awaits the
    // Task-returning handler (see DuplicateDeviceHandler dialect note there).
    private async Task<DuplicateDeviceAction> HandleDuplicateDevice(DuplicateDeviceCheckResult duplicateResult)
    {
        try
        {
            // Create dialog manually since we need access to the Result property
            var duplicateDialogViewModel = new DuplicateDeviceDialogViewModel(
                duplicateResult.ExistingDevice,
                duplicateResult.NewDevice,
                duplicateResult.ExistingDeviceInterface,
                duplicateResult.NewDeviceInterface);

            var dialog = new DuplicateDeviceDialog();
            dialog.DataContext = duplicateDialogViewModel;
            
            // Find the owner window — Avalonia dialogs require an owner; fall back to the
            // main window when this VM isn't a window's DataContext.
            if (Application.Current?.ApplicationLifetime is not IClassicDesktopStyleApplicationLifetime desktop)
            {
                return DuplicateDeviceAction.Cancel;
            }

            var ownerWindow = desktop.Windows.FirstOrDefault(w => w.DataContext == this)
                ?? desktop.MainWindow;
            if (ownerWindow == null)
            {
                return DuplicateDeviceAction.Cancel;
            }

            dialog.WindowStartupLocation = WindowStartupLocation.CenterOwner;

            var dialogResult = await dialog.ShowDialog<bool?>(ownerWindow);
            
            if (dialogResult == true)
            {
                return dialog.Result switch
                {
                    DuplicateDeviceDialog.DuplicateDeviceDialogResult.KeepExisting => DuplicateDeviceAction.KeepExisting,
                    DuplicateDeviceDialog.DuplicateDeviceDialogResult.SwitchToNew => DuplicateDeviceAction.SwitchToNew,
                    _ => DuplicateDeviceAction.Cancel
                };
            }

            return DuplicateDeviceAction.Cancel;
        }
        catch (Exception ex)
        {
            // Log error and default to cancel - this should rarely happen
            Daqifi.Desktop.Common.Loggers.AppLogger.Instance.Error(ex, "Failed to show duplicate device dialog");
            return DuplicateDeviceAction.Cancel;
        }
    }
    #endregion
}
