// Generated by portomatic scaffold from upstream Daqifi.Desktop/ViewModels/DeviceLogsViewModel.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Text;
using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Input.Platform; // Avalonia 12: IClipboard.SetTextAsync is an extension method
using Avalonia.Threading;
using Daqifi.Desktop.Services;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.Device;
using Daqifi.Desktop.Logger;
using Daqifi.Desktop.Loggers;
using Daqifi.Desktop.Models;
using Daqifi.Core.Device.SdCard;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Daqifi.Desktop.ViewModels;

/// <summary>
/// Represents the current state of the SD card in the connected device.
/// </summary>
// @port: Daqifi.Desktop.ViewModels.SdCardState
public enum SdCardState
{
    /// <summary>SD card state has not yet been determined.</summary>
    Unknown,
    /// <summary>SD card is present and accessible.</summary>
    Ok,
    /// <summary>No SD card is installed in the device.</summary>
    NotPresent,
    /// <summary>SD card is present but an error occurred accessing it.</summary>
    Error
}

// @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel
public partial class DeviceLogsViewModel : ObservableObject
{
    private readonly IAppLogger _logger;
    private readonly ISdCardSessionImporter? _importerOverride;

    /// <summary>
    /// The device whose <c>IsConnected</c> notifications are currently subscribed. Held separately
    /// from <see cref="SelectedDevice"/> so the old device can be detached after the property has
    /// already moved on — see <see cref="WatchSelectedDeviceConnectivity"/>.
    /// </summary>
    private IStreamingDevice? _connectivityWatchedDevice;

    [ObservableProperty]
    private bool _isBusy;

    [ObservableProperty]
    private string _busyMessage;

    [ObservableProperty]
    private ObservableCollection<IStreamingDevice> _connectedDevices;

    [ObservableProperty]
    private IStreamingDevice _selectedDevice;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasNoFiles))]
    [NotifyPropertyChangedFor(nameof(HasFiles))]
    [NotifyPropertyChangedFor(nameof(HasSdCardNotPresent))]
    [NotifyPropertyChangedFor(nameof(HasSdCardError))]
    [NotifyPropertyChangedFor(nameof(SdCardStatusLine))]
    private SdCardState _sdCardState = SdCardState.Unknown;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(HasSdCardError))]
    [NotifyPropertyChangedFor(nameof(SdCardStatusLine))]
    private string _sdCardErrorMessage = string.Empty;

    /// <summary>
    /// Actionable guidance for the current SD card error, set by <see cref="SdCardFailureClassifier"/>
    /// and shown in the error panel. Defaults to the generic card guidance.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.SdCardErrorGuidance
    [ObservableProperty]
    private string _sdCardErrorGuidance = SdCardFailureClassifier.GENERIC_CARD_GUIDANCE;

    private ObservableCollection<SdCardFile> _deviceFiles;

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.DeviceFiles
    public ObservableCollection<SdCardFile> DeviceFiles
    {
        get => _deviceFiles;
        set
        {
            if (Equals(_deviceFiles, value)) return;

            if (_deviceFiles != null)
            {
                _deviceFiles.CollectionChanged -= OnDeviceFilesCollectionChanged;
            }

            if (SetProperty(ref _deviceFiles, value))
            {
                if (_deviceFiles != null)
                {
                    _deviceFiles.CollectionChanged += OnDeviceFilesCollectionChanged;
                }
                OnPropertyChanged(nameof(HasNoFiles));
                OnPropertyChanged(nameof(HasFiles));
            }
        }
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.CanAccessSdCard
    // SD file access (LIST / download) is transport-agnostic (issue #1): the firmware routes SD
    // replies to the requesting link (USB or WiFi/TCP — daqifi-nyquist-firmware #598/#599) and
    // Core's SD path drives its consumer swap against the transport stream regardless of type.
    // Gate on "device supports SD + connected" (issue #1's own prescription), NOT connection type
    // alone: IsConnected must be checked because a device can drop mid-session (silently over
    // WiFi) while still selected — a non-null-but-disconnected Core would otherwise pass the
    // GetConnectedCoreDevice null-guard and run SD ops against a dead transport.
    // Capture SelectedDevice into the pattern local `device` so it is read exactly once — the
    // observable property is nullable and could flip to null between two reads under
    // selection/disconnect reentrancy (Qodo "SelectedDevice double-read race").
    public bool CanAccessSdCard =>
        SelectedDevice is { IsConnected: true } device &&
        device.ConnectionType is ConnectionType.Usb or ConnectionType.Wifi;

    /// <summary>True when the device has an OK SD card but no log files on it.</summary>
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.HasNoFiles
    public bool HasNoFiles => (DeviceFiles?.Any() != true) && CanAccessSdCard && SdCardState == SdCardState.Ok;

    /// <summary>True when the device has an OK SD card with at least one log file.</summary>
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.HasFiles
    public bool HasFiles => CanAccessSdCard && (DeviceFiles?.Any() == true) && SdCardState == SdCardState.Ok;

    /// <summary>True when the device reports that no SD card is installed.</summary>
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.HasSdCardNotPresent
    public bool HasSdCardNotPresent => CanAccessSdCard && SdCardState == SdCardState.NotPresent;

    /// <summary>True when the device reports an SD card error.</summary>
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.HasSdCardError
    public bool HasSdCardError => CanAccessSdCard && SdCardState == SdCardState.Error;

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.ConnectionTypeMessage
    // Kept consistent with CanAccessSdCard: a selected-but-disconnected device reports the drop
    // rather than a misleading "SD Card Access Available" (Qodo "Report disconnected devices
    // accurately"). The switch reads SelectedDevice exactly once (no double-read race).
    public string ConnectionTypeMessage => SelectedDevice switch
    {
        null => string.Empty,
        { IsConnected: false } => "Device disconnected - reconnect to access the SD card",
        { ConnectionType: ConnectionType.Usb } => "USB Connected - SD Card Access Available",
        _ => "WiFi Connected - SD Card Access Available",
    };

    /// <summary>
    /// Short status string appended to the connection status bar. Empty when the SD card state is
    /// unknown, and also when SD is not accessible at all (no device selected, the selected device
    /// has disconnected, or its transport does not carry SD) — otherwise a disconnected device
    /// would keep advertising a stale "SD card OK · N files" beside its disconnect message.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.SdCardStatusLine
    public string SdCardStatusLine => !CanAccessSdCard ? string.Empty : SdCardState switch
    {
        SdCardState.Ok =>
            $" · SD card OK · {DeviceFiles?.Count ?? 0} {(DeviceFiles?.Count == 1 ? "file" : "files")}",
        SdCardState.NotPresent => " · No SD card installed",
        SdCardState.Error =>
            $" · SD card error{(!string.IsNullOrEmpty(SdCardErrorMessage) ? $": {SdCardErrorMessage}" : string.Empty)}",
        _ => string.Empty
    };

    /// <summary>Refreshes the SD card file list from the selected device.</summary>
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.RefreshFilesCommand
    public IAsyncRelayCommand RefreshFilesCommand { get; }

    /// <summary>
    /// The first refresh kicked off when a device becomes selected. Exposed so a test can await the
    /// initial load; production code fires it and forgets it.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.InitialRefreshTask
    internal Task? InitialRefreshTask { get; private set; }

    public DeviceLogsViewModel() : this(null, null) { }

    /// <summary>
    /// Test seam: injects the logger and SD card importer. Production uses the parameterless ctor,
    /// which passes null so the defaults (<see cref="AppLogger.Instance"/> and a real
    /// <see cref="SdCardSessionImporter"/>) are used.
    /// </summary>
    internal DeviceLogsViewModel(IAppLogger? logger, ISdCardSessionImporter? importer)
    {
        _logger = logger ?? AppLogger.Instance;
        _importerOverride = importer;

        ConnectedDevices = new ObservableCollection<IStreamingDevice>();
        DeviceFiles = new ObservableCollection<SdCardFile>();
        DeviceFiles.CollectionChanged += OnDeviceFilesCollectionChanged;

        RefreshFilesCommand = new AsyncRelayCommand(RefreshFilesAsync, () => CanAccessSdCard);

        ConnectionManager.Instance.PropertyChanged += (s, e) =>
        {
            if (e.PropertyName == "ConnectedDevices")
            {
                UpdateConnectedDevices();
            }
        };

        UpdateConnectedDevices();
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.OnDeviceFilesCollectionChanged
    private void OnDeviceFilesCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
    {
        OnPropertyChanged(nameof(HasNoFiles));
        OnPropertyChanged(nameof(HasFiles));
        OnPropertyChanged(nameof(SdCardStatusLine));
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.UpdateConnectedDevices
    private void UpdateConnectedDevices()
    {
        void Update()
        {
            ConnectedDevices.Clear();
            foreach (var device in ConnectionManager.Instance.ConnectedDevices)
            {
                ConnectedDevices.Add(device);
            }

            if (SelectedDevice == null && ConnectedDevices.Any())
            {
                SelectedDevice = ConnectedDevices.First();
            }

            // Recompute the SD gate on every connected-set change. CanAccessSdCard now depends on
            // the selected device's IsConnected (issue #1), and an explicit Disconnect() or a USB
            // removal fires ConnectionManager's "ConnectedDevices" even when the SelectedDevice
            // *reference* is unchanged — so the gate must recompute here, not only on selection
            // change (Qodo "SD access state stale").
            RaiseSdGateChanged();
        }

        if (!Dispatcher.UIThread.CheckAccess())
        {
            Dispatcher.UIThread.Invoke(Update);
        }
        else
        {
            Update();
        }
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.OnSelectedDeviceChanged
    partial void OnSelectedDeviceChanged(IStreamingDevice value)
    {
        // Follow the selection with the IsConnected subscription so a drop on the *currently
        // selected* device reaches the gate. Unsubscribe the previous device first — selection
        // changes freely, and re-subscribing without this would leak handlers and multiply
        // RaiseSdGateChanged calls per event.
        WatchSelectedDeviceConnectivity(value);

        SdCardState = SdCardState.Unknown;
        SdCardErrorMessage = string.Empty;

        if (value != null)
        {
            if (CanAccessSdCard)
            {
                InitialRefreshTask = RefreshFilesAsync();
            }
            else
            {
                DeviceFiles.Clear();
            }
        }
        else
        {
            DeviceFiles.Clear();
        }

        RaiseSdGateChanged();
    }

    /// <summary>
    /// Re-raises the SD-access gate — <see cref="CanAccessSdCard"/>, its dependent visibility
    /// flags, the connection message, and the refresh command's CanExecute. Invoked on selection
    /// change and on any connected-set change (issue #1 / Qodo "SD access state stale").
    /// </summary>
    /// <remarks>
    /// A <em>reported</em> disconnect now reaches the gate promptly: the device layer signals
    /// <c>IsConnected</c> off Core's <c>StatusChanged</c> (issue #3) and
    /// <see cref="WatchSelectedDeviceConnectivity"/> subscribes the selected device, so an explicit
    /// disconnect, a USB removal, or a Core-detected transport loss updates this without waiting for
    /// the next connected-set change.
    /// <para>
    /// A fully <em>silent</em> TCP death still does not: Core's <c>TcpStreamTransport</c> raises
    /// <c>StatusChanged</c> only from its connect-failure and <c>DisconnectAsync</c> paths — there is
    /// no read-error hook or keepalive — so <c>IsConnected</c> stays true until something else
    /// notices. Filed upstream as daqifi-core#394. Until then the gate can read stale in that case,
    /// which is a cosmetic staleness only: every SD operation re-checks <c>IsConnected</c> at
    /// operation time and the download stall watchdog bounds any request issued against a dead link.
    /// </para>
    /// </remarks>
    /// <summary>
    /// Points the <c>IsConnected</c> subscription at <paramref name="device"/>, detaching it from
    /// the previously selected device.
    /// </summary>
    /// <remarks>
    /// Tracks the subscribed instance in its own field rather than re-deriving it from
    /// <c>SelectedDevice</c>: by the time this runs the property has already been updated, so
    /// unsubscribing via <c>SelectedDevice</c> would detach from the *new* device and leak the old
    /// one's handler. Devices outlive this view-model (they live in <c>ConnectionManager</c>), so a
    /// leaked handler would keep the view-model alive and multiply gate updates.
    /// </remarks>
    /// <param name="device">The newly selected device, or null when the selection is cleared.</param>
    private void WatchSelectedDeviceConnectivity(IStreamingDevice? device)
    {
        if (ReferenceEquals(_connectivityWatchedDevice, device))
        {
            return;
        }

        if (_connectivityWatchedDevice is INotifyPropertyChanged previous)
        {
            previous.PropertyChanged -= OnSelectedDeviceConnectivityChanged;
        }

        _connectivityWatchedDevice = device;

        if (device is INotifyPropertyChanged current)
        {
            current.PropertyChanged += OnSelectedDeviceConnectivityChanged;
        }
    }

    /// <summary>
    /// Recomputes the SD gate when the selected device reports a connectivity change.
    /// </summary>
    /// <remarks>
    /// The device raises this from Core's transport thread on a silent drop, so marshal before
    /// touching view-model state. An empty/null property name is the
    /// <see cref="INotifyPropertyChanged"/> "everything changed" convention and must be treated as
    /// a possible <c>IsConnected</c> change.
    /// </remarks>
    private void OnSelectedDeviceConnectivityChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (!string.IsNullOrEmpty(e.PropertyName) &&
            e.PropertyName != nameof(IStreamingDevice.IsConnected))
        {
            return;
        }

        // Ignore a late event from a device that is no longer the subscribed one.
        if (!ReferenceEquals(sender, _connectivityWatchedDevice))
        {
            return;
        }

        if (Dispatcher.UIThread.CheckAccess())
        {
            RaiseSdGateChanged();
            return;
        }

        // Non-throwing, for the same reason AbstractStreamingDevice.RaiseIsConnectedChanged and
        // BootloaderWatcher guard theirs: this runs on Core's transport thread, and the disconnect
        // that triggers it is exactly what app shutdown produces — so Post can be called as the
        // dispatcher goes away. An escape here would propagate into Core's callback.
        try
        {
            Dispatcher.UIThread.Post(RaiseSdGateChanged);
        }
        catch (Exception)
        {
            // Dispatcher unavailable / shutting down — drop the gate refresh; nothing is bound.
        }
    }

    private void RaiseSdGateChanged()
    {
        OnPropertyChanged(nameof(CanAccessSdCard));
        OnPropertyChanged(nameof(HasNoFiles));
        OnPropertyChanged(nameof(HasSdCardNotPresent));
        OnPropertyChanged(nameof(HasSdCardError));
        OnPropertyChanged(nameof(HasFiles));
        OnPropertyChanged(nameof(ConnectionTypeMessage));
        // SdCardStatusLine is now gated on CanAccessSdCard too, so re-raise it when the gate
        // flips (on close via the state reset below it also re-raises through SdCardState;
        // this covers the gate OPENING on reconnect, where no state change occurs).
        OnPropertyChanged(nameof(SdCardStatusLine));
        RefreshFilesCommand.NotifyCanExecuteChanged();

        // When SD is no longer accessible (e.g. the selected device disconnected), drop the now-stale
        // SD state + file list so SdCardStatusLine doesn't keep showing a phantom "SD card OK · N
        // files" next to a "Device disconnected" message (Qodo "Stale SD status line"). Setting
        // SdCardState and clearing DeviceFiles each re-raise SdCardStatusLine / Has* on their own.
        if (!CanAccessSdCard)
        {
            SdCardState = SdCardState.Unknown;
            SdCardErrorMessage = string.Empty;
            DeviceFiles.Clear();
        }
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.RefreshFilesAsync
    internal async Task RefreshFilesAsync()
    {
        var device = SelectedDevice;
        if (device is not { IsConnected: true } ||
            device.ConnectionType is not (ConnectionType.Usb or ConnectionType.Wifi))
        {
            return;
        }

        try
        {
            IsBusy = true;
            BusyMessage = "Refreshing files...";
            SdCardState = SdCardState.Unknown;
            SdCardErrorMessage = string.Empty;

            DeviceFiles.Clear();

            await Task.Run(() => device.RefreshSdCardFiles());

            // Re-validate after the await: the selection can change AND the device can disconnect
            // while RefreshSdCardFiles ran. Bail without repopulating in either case so a completing
            // refresh can't overwrite a disconnect reset (RaiseSdGateChanged) with a stale
            // "SD card OK · N files" that contradicts the disconnect UX (Qodo "Refresh overwrites
            // disconnect reset"). Both this continuation and the reset run on the UI thread, so the
            // check-then-set below is atomic w.r.t. the reset — no lock needed.
            if (SelectedDevice != device || !device.IsConnected)
            {
                return;
            }

            foreach (var file in device.SdCardFiles)
            {
                DeviceFiles.Add(file);
            }

            SdCardState = SdCardState.Ok;
        }
        catch (Exception ex)
        {
            // Route every failure through the classifier: typed Core SD conditions (no card, wedged
            // subsystem, filesystem error) become expected device conditions (Warning, no Sentry) with
            // actionable guidance; anything else keeps the Error path.
            var failure = SdCardFailureClassifier.Classify(ex);
            // Only paint the SD surface if this refresh's device is still the selected one AND is
            // still connected. The selection half mirrors the success path's post-await check and
            // HandleImportFailure, so a stale failure can't overwrite the current device's panel.
            // The IsConnected half matters now that SD runs over WiFi (issue #1): a silent drop
            // closes the gate via RaiseSdGateChanged, which resets the SD state — and the failing
            // refresh's own exception would otherwise land right after and repaint an error over
            // that reset, contradicting the "Device disconnected" UX.
            if (ReferenceEquals(SelectedDevice, device) && device.IsConnected)
            {
                ApplyFailureState(failure);
            }

            // Log unconditionally and let the classifier set the severity. A disconnect that kills an
            // in-flight refresh throws a typed transport error, which the classifier already treats
            // as an expected device condition (Warning, no Sentry) — so the false-positive case is
            // handled by TYPE. Downgrading here based on "is the device still current" instead would
            // also silence a genuine defect that merely coincided with a device switch.
            LogFailure(ex, failure, $"Failed to refresh SD card files on device {device.DeviceSerialNo}");
        }
        finally
        {
            IsBusy = false;
            BusyMessage = string.Empty;
        }
    }

    [RelayCommand]
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.CopyDiagnosticInfo
    private async Task CopyDiagnosticInfoAsync()
    {
        var sb = new StringBuilder();
        sb.AppendLine($"Device Serial: {SelectedDevice?.DeviceSerialNo ?? "N/A"}");
        sb.AppendLine($"Firmware Version: {SelectedDevice?.DeviceVersion ?? "N/A"}");
        sb.AppendLine($"Connection Type: {SelectedDevice?.ConnectionType}");
        sb.AppendLine($"SD Card State: {SdCardState}");
        if (!string.IsNullOrEmpty(SdCardErrorMessage))
        {
            sb.AppendLine($"Error: {SdCardErrorMessage}");
        }

        try
        {
            // WPF Clipboard.SetText → async TopLevel clipboard owned by the app main window.
            if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime { MainWindow: { } main }
                && main.Clipboard is { } clipboard)
            {
                await clipboard.SetTextAsync(sb.ToString());
            }
        }
        catch (Exception ex)
        {
            _logger.Warning($"Failed to copy diagnostic info to clipboard: {ex.Message}");
        }
    }

    [RelayCommand]
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.ImportFile
    private async Task ImportFile(SdCardFile? file)
    {
        // Snapshot the device up front so a selection change during the async import can't retarget
        // it or misattribute a failure to a different device's drawer.
        var device = SelectedDevice;
        if (file == null || device == null || !CanAccessSdCard) return;

        try
        {
            IsBusy = true;
            BusyMessage = $"Downloading {file.FileName}...";

            var importer = ResolveImporter();

            var progress = new Progress<ImportProgress>(p =>
            {
                BusyMessage = $"Importing {file.FileName}... {p.SamplesProcessed:N0} samples";
            });

            var result = await Task.Run(() =>
                importer.ImportFromDeviceAsync(device, file.FileName, null, progress, CancellationToken.None));

            AddImportedSession(result.Session);

            var message = $"Successfully imported {file.FileName}";
            var timestampWarning = result.TimestampQuality.BuildUserWarning();
            if (timestampWarning != null)
            {
                message += $"\n\nWarning: {timestampWarning}";
            }

            await ShowMessage("Import Complete", message, MessageBoxButton.OK);
        }
        catch (OperationCanceledException)
        {
            // User cancelled
        }
        catch (Exception ex)
        {
            var failure = HandleImportFailure(ex, file.FileName, device);
            await ShowMessage("Import Failed",
                $"Could not import {file.FileName}.\n\n{failure.Guidance}",
                MessageBoxButton.OK);
        }
        finally
        {
            IsBusy = false;
            BusyMessage = string.Empty;
        }
    }

    [RelayCommand]
    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.ImportAllFiles
    private async Task ImportAllFiles()
    {
        // Snapshot the device up front (see ImportFile).
        var device = SelectedDevice;
        if (device == null || !CanAccessSdCard || DeviceFiles == null || !DeviceFiles.Any()) return;

        var filesToImport = DeviceFiles.ToList();
        var successCount = 0;
        var failCount = 0;
        var timestampWarningCount = 0;
        SdCardFailure? abortingFailure = null;
        SdCardFailure? lastExpectedFailure = null;
        var disconnectedMidBatch = false;

        try
        {
            IsBusy = true;

            var importer = ResolveImporter();

            for (var i = 0; i < filesToImport.Count; i++)
            {
                // Re-check connectivity every iteration, not just once before the loop: the device
                // can go away mid-batch, and CoreDevice stays non-null, so the downstream null-guard
                // still passes and each remaining file would be issued against a dead transport.
                //
                // Covers a disconnect Core actually reports — an explicit Disconnect(), a USB
                // removal, or a transport-signalled loss (Core's ConnectionStatus.Lost). It does NOT
                // cover a fully silent TCP death: Core's TcpStreamTransport raises StatusChanged
                // only from its connect-failure and DisconnectAsync paths (no read-error hook or
                // keepalive), so IsConnected stays true and this check cannot see it. That case is
                // caught instead by the download stall watchdog, whose SdCardDownloadStalledException
                // classifies card-unavailable and breaks below — costing one stall timeout for the
                // batch rather than one per remaining file.
                if (!device.IsConnected)
                {
                    disconnectedMidBatch = true;
                    break;
                }

                var file = filesToImport[i];
                BusyMessage = $"Importing file {i + 1} of {filesToImport.Count}: {file.FileName}...";

                try
                {
                    var progress = new Progress<ImportProgress>(p =>
                    {
                        BusyMessage = $"Importing {file.FileName} ({i + 1}/{filesToImport.Count})... {p.SamplesProcessed:N0} samples";
                    });

                    var result = await Task.Run(() =>
                        importer.ImportFromDeviceAsync(device, file.FileName, null, progress, CancellationToken.None));

                    AddImportedSession(result.Session);

                    if (result.TimestampQuality.HasDegenerateTimeAxis)
                    {
                        timestampWarningCount++;
                    }

                    successCount++;
                }
                catch (Exception ex)
                {
                    var failure = HandleImportFailure(ex, file.FileName, device);
                    failCount++;
                    // Remember the last EXPECTED device condition (not just the last failure), so a later
                    // unexpected app error doesn't drop the actionable guidance an earlier card condition
                    // carried.
                    if (failure.IsExpectedDeviceCondition)
                    {
                        lastExpectedFailure = failure;
                    }

                    // The SD subsystem is unusable, not just this one file — every remaining file
                    // would fail the same multi-second way, so stop rather than grinding through them.
                    if (failure.IsCardUnavailable)
                    {
                        abortingFailure = failure;
                        break;
                    }
                }
            }

            var message = $"Imported {successCount} of {filesToImport.Count} files.";
            if (failCount > 0)
            {
                message += $"\n{failCount} file(s) failed to import.";
            }

            if (timestampWarningCount > 0)
            {
                message += $"\nWarning: {timestampWarningCount} file(s) have missing or unusable per-sample " +
                           "timestamps; their sessions' time axes may be flat or partially collapsed.";
            }

            if (disconnectedMidBatch)
            {
                // Say so explicitly: without this a batch cut short by a disconnect reports the same
                // "Import Complete" summary as a finished one, and the user has no way to tell that
                // the untouched files were skipped rather than imported.
                message += "\n\nImport stopped early: the device disconnected. Reconnect and run " +
                           "Import All again to pick up the remaining files.";
            }
            else if (abortingFailure != null)
            {
                message += $"\n\nImport stopped early: {abortingFailure.Guidance}";
            }
            else if (successCount == 0 && lastExpectedFailure != null)
            {
                // Surface actionable guidance when we didn't abort but NOTHING imported — i.e. every file
                // failed with a device condition, which over Windows USB serial is how a wedged SD
                // subsystem presents (Core's ~500ms per-read timeout beats the sustained watchdog, so the
                // device-wide abort path is unreachable and every file fails per-file). Without this the
                // batch summary would report only a failure count and never tell the user to power-cycle
                // (issue #754). The successCount==0 guard is deliberate: if some files imported, the
                // device is demonstrably working, so a lone empty/corrupt/hiccup file must NOT trigger a
                // misleading "power-cycle the device" — its failure is already in the count.
                message += $"\n\n{lastExpectedFailure.Guidance}";
            }

            await ShowMessage("Import Complete", message, MessageBoxButton.OK);
        }
        catch (Exception ex)
        {
            _logger.Error(ex, "Error importing all files");
            await ShowMessage("Import Failed",
                "Import failed. Please check the device connection and try again.",
                MessageBoxButton.OK);
        }
        finally
        {
            IsBusy = false;
            BusyMessage = string.Empty;
        }
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.ResolveImporter
    private ISdCardSessionImporter ResolveImporter()
    {
        if (_importerOverride != null)
        {
            return _importerOverride;
        }

        var loggingContext = App.ServiceProvider.GetRequiredService<IDbContextFactory<LoggingContext>>();
        return new SdCardSessionImporter(loggingContext);
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.AddImportedSession
    private static void AddImportedSession(LoggingSession session)
    {
        if (!Dispatcher.UIThread.CheckAccess())
        {
            Dispatcher.UIThread.Invoke(() => LoggingManager.Instance.LoggingSessions.Add(session));
        }
        else
        {
            LoggingManager.Instance.LoggingSessions.Add(session);
        }
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.HandleImportFailure
    private SdCardFailure HandleImportFailure(Exception ex, string fileName, IStreamingDevice device)
    {
        var failure = SdCardFailureClassifier.Classify(ex);
        // Only paint the card-wide SD panel for a DEVICE-WIDE failure (IsCardUnavailable) that is still
        // the selected device. A per-file failure (empty file, one corrupt file, a momentary stall) is
        // surfaced by the import summary dialog instead — painting the card-wide Error panel for it
        // would hide the whole file list (HasFiles requires SdCardState==Ok) even though the batch keeps
        // going and later files import fine, leaving a sticky panel that contradicts the actual outcome.
        if (failure.IsExpectedDeviceCondition && failure.IsCardUnavailable && ReferenceEquals(SelectedDevice, device))
        {
            ApplyFailureState(failure);
        }
        LogFailure(ex, failure, $"Error importing {fileName} from device {device.DeviceSerialNo}");
        return failure;
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.ApplyFailureState
    private void ApplyFailureState(SdCardFailure failure)
    {
        SdCardState = failure.State;
        SdCardErrorMessage = failure.StatusMessage;
        SdCardErrorGuidance = failure.Guidance;
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.LogFailure
    private void LogFailure(Exception ex, SdCardFailure failure, string context)
    {
        // Expected device conditions (no card, wedged subsystem, filesystem error) log at Warning so
        // they do not raise Sentry issues; a genuine defect keeps the Error path.
        if (failure.IsExpectedDeviceCondition)
        {
            _logger.Warning(ex, $"{context}: {failure.Guidance}");
        }
        else
        {
            _logger.Error(ex, context);
        }
    }

    // @port: Daqifi.Desktop.ViewModels.DeviceLogsViewModel.ShowMessage
    // MahApps ShowMessageAsync on the MetroWindow → IMessageBoxService (dialog_service
    // mechanism); MessageDialogStyle.Affirmative maps to MessageBoxButton.OK.
    private async Task ShowMessage(string title, string message, MessageBoxButton button)
    {
        await _messageBoxService.ShowAsync(message, title, button, MessageBoxImage.Information);
    }

    private static readonly IMessageBoxService _messageBoxService = new AvaloniaMessageBoxService();
}
