// Generated by portomatic scaffold from upstream Daqifi.Desktop/ViewModels/DevicesPaneViewModel.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.Collections.ObjectModel;
using System.ComponentModel;
using Avalonia.Threading;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Daqifi.Desktop.Device;

namespace Daqifi.Desktop.ViewModels;

/// <summary>
/// Backs the unified Devices pane. Aggregates connected devices into a tile
/// grid and owns the inline settings drawer state. Delegates side-effecting
/// commands (connect, disconnect, reboot, firmware, network) to the shell
/// view-model so the existing service wiring is reused unchanged.
/// </summary>
// @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel
public partial class DevicesPaneViewModel : ObservableObject, IDisposable
{
    private readonly DaqifiViewModel? _shell;
    private readonly Dispatcher _dispatcher;
    private bool _disposed;

    /// <summary>Device tiles in the order ConnectionManager returns them.</summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.Devices
    public ObservableCollection<DeviceTileViewModel> Devices { get; } = [];

    /// <summary>
    /// The shell view-model, exposed so the drawer can bind directly to shell-owned
    /// state (firmware path/progress, logging mode, SD format) and commands
    /// (firmware upload, network apply) without a second DataContext hop.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.Shell
    public DaqifiViewModel? Shell => _shell;

    [ObservableProperty] private bool _hasConnectedDevice;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(SelectedDevice))]
    [NotifyPropertyChangedFor(nameof(SelectedDeviceSupportsFirmwareUpdate))]
    // MaxFrequencyHz is announced before FrequencyHz on purpose — the generator raises these in
    // declaration order, and the slider bound to both would otherwise briefly see the incoming
    // rate against the outgoing ceiling. See MaxFrequencyHz.
    [NotifyPropertyChangedFor(nameof(MaxFrequencyHz))]
    [NotifyPropertyChangedFor(nameof(FrequencyHz))]
    private DeviceTileViewModel? _selectedTile;

    [ObservableProperty] private bool _isSettingsOpen;

    /// <summary>The underlying device of the tile shown in the settings drawer.</summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.SelectedDevice
    public IStreamingDevice? SelectedDevice => SelectedTile?.Device;

    /// <summary>True when the selected device is USB-connected (firmware update path).</summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.SelectedDeviceSupportsFirmwareUpdate
    public bool SelectedDeviceSupportsFirmwareUpdate =>
        SelectedDevice?.ConnectionType == ConnectionType.Usb;

    /// <summary>
    /// Sampling frequency shown on the drawer's FREQUENCY slider.
    /// Reads straight off the device so the slider reflects the real value,
    /// but writes go through the shell's guarded <c>SelectedStreamingFrequency</c>
    /// setter — which blocks changes and shows an error dialog while a
    /// logging session is active.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.FrequencyHz
    public int FrequencyHz
    {
        get => SelectedDevice?.StreamingFrequency ?? 0;
        set
        {
            if (_shell == null || SelectedDevice == null) return;
            // A Slider writes its Value back when a falling Maximum coerces it, so this setter can
            // be reached carrying the rate the device already holds. That is not a change the user
            // asked for, and pushing it through the shell would answer it with "Cannot change
            // sampling frequency while logging."
            if (value == SelectedDevice.StreamingFrequency) return;
            _shell.SelectedStreamingFrequency = value;
            OnPropertyChanged();
        }
    }

    /// <summary>
    /// Upper bound of the drawer's FREQUENCY slider: the rate the selected device advertises as
    /// its maximum, so the control offers exactly what the hardware will accept.
    /// </summary>
    /// <remarks>
    /// Read from the device rather than written down here. Core seeds
    /// <c>MaxSamplingRate</c> from its board table and the capability document read during connect
    /// replaces it with the device's own figure — 22000 Hz on the bench Nq1 (fw 3.7.2), against a
    /// board-table 1000. Both the wrapper's rate guard and Core's own validator bound against the
    /// same property, so a rate this slider can reach is one the device will take.
    /// <para>
    /// <see cref="SelectedTile"/> is a sufficient trigger: <c>ConnectionManager</c> only publishes a
    /// device once <c>Connect()</c> has returned, and that call hydrates the capability document
    /// before it returns — so no tile ever exists while the ceiling is still the bootstrap value,
    /// and a reconnect rebuilds the tile and re-selects it.
    /// </para>
    /// </remarks>
    // Downstream-only: no upstream counterpart.
    public int MaxFrequencyHz => SelectedDevice?.MaxStreamingFrequency ?? 1;

    /// <summary>Opens the inline settings drawer for a device tile.</summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.OpenSettingsCommand
    public IRelayCommand<DeviceTileViewModel> OpenSettingsCommand { get; }

    /// <summary>Closes the inline settings drawer.</summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.CloseSettingsCommand
    public IRelayCommand CloseSettingsCommand { get; }

    /// <summary>Shows the Add-Device dialog via the shell view-model.</summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.AddDeviceCommand
    public IRelayCommand AddDeviceCommand { get; }

    /// <summary>Disconnects the currently selected device and closes the drawer.</summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.DisconnectSelectedCommand
    public IRelayCommand DisconnectSelectedCommand { get; }

    /// <summary>Reboots the currently selected device.</summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.RebootSelectedCommand
    public IRelayCommand RebootSelectedCommand { get; }

    /// <summary>
    /// Writes the chosen logging-mode label ("Stream to App" or "Log to
    /// Device") to the shell. Parameterized so the XAML can wire both
    /// segmented-toggle RadioButtons to the same command.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.SetLoggingModeCommand
    public IRelayCommand<string> SetLoggingModeCommand { get; }

    /// <summary>Creates the view-model bound to the shell view-model.</summary>
    public DevicesPaneViewModel(DaqifiViewModel? shell)
    {
        _shell = shell;
        // WPF Dispatcher.CurrentDispatcher → the ONE Avalonia UI dispatcher (VMs are
        // constructed on the UI thread, same assumption as upstream).
        _dispatcher = Dispatcher.UIThread;

        OpenSettingsCommand = new RelayCommand<DeviceTileViewModel>(OpenSettings);
        CloseSettingsCommand = new RelayCommand(CloseSettings);
        AddDeviceCommand = new RelayCommand(AddDevice);
        DisconnectSelectedCommand = new RelayCommand(DisconnectSelected, () => SelectedDevice != null);
        RebootSelectedCommand = new RelayCommand(RebootSelected, () => SelectedDevice != null);
        SetLoggingModeCommand = new RelayCommand<string>(SetLoggingMode);

        ConnectionManager.Instance.PropertyChanged += OnConnectionManagerPropertyChanged;
        Rebuild();
    }

    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.OnSelectedTileChanged
    partial void OnSelectedTileChanged(DeviceTileViewModel? value)
    {
        // Derived-property change notifications are declared via
        // [NotifyPropertyChangedFor] attributes above; the partial is only
        // for imperative work the source generator can't do.
        DisconnectSelectedCommand.NotifyCanExecuteChanged();
        RebootSelectedCommand.NotifyCanExecuteChanged();
    }

    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.OnConnectionManagerPropertyChanged
    private void OnConnectionManagerPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName != nameof(ConnectionManager.ConnectedDevices)) return;

        if (_dispatcher.CheckAccess())
        {
            Rebuild();
        }
        else
        {
            _dispatcher.Post(Rebuild);
        }
    }

    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.Rebuild
    private void Rebuild()
    {
        if (_disposed) return;

        var openSerial = SelectedDevice?.DeviceSerialNo;

        foreach (var tile in Devices) tile.Dispose();
        Devices.Clear();

        foreach (var device in ConnectionManager.Instance.ConnectedDevices)
        {
            Devices.Add(new DeviceTileViewModel(device));
        }

        HasConnectedDevice = Devices.Count > 0;

        // Preserve drawer state across a rebuild if the device is still there;
        // otherwise close the drawer so it doesn't point at a removed device.
        if (IsSettingsOpen && openSerial != null)
        {
            var match = Devices.FirstOrDefault(d => d.Device.DeviceSerialNo == openSerial);
            if (match != null)
            {
                SelectedTile = match;
            }
            else
            {
                CloseSettings();
            }
        }
    }

    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.OpenSettings
    private void OpenSettings(DeviceTileViewModel? tile)
    {
        if (tile == null) return;
        SelectedTile = tile;
        // Keep the shell's SelectedDevice in sync so existing commands
        // (UploadFirmware, UpdateNetworkConfiguration) operate on the
        // device the drawer is showing.
        if (_shell != null)
        {
            _shell.SelectedDevice = tile.Device;
            _shell.SelectedDeviceSupportsFirmwareUpdate =
                tile.Device.ConnectionType == ConnectionType.Usb;
            // Seed the drawer's NAME edit buffer from the device's current friendly name and clear
            // any stale validation error from a previous drawer session.
            _shell.SeedPendingFriendlyName(tile.Device.FriendlyName);
            _shell.FriendlyNameError = null;
        }
        IsSettingsOpen = true;
    }

    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.CloseSettings
    private void CloseSettings()
    {
        IsSettingsOpen = false;
        SelectedTile = null;
    }

    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.AddDevice
    private void AddDevice()
    {
        if (_shell?.ShowConnectionDialogCommand.CanExecute(null) == true)
        {
            _shell.ShowConnectionDialogCommand.Execute(null);
        }
    }

    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.DisconnectSelected
    private void DisconnectSelected()
    {
        var device = SelectedDevice;
        if (device == null || _shell == null) return;
        if (_shell.DisconnectDeviceCommand.CanExecute(device))
        {
            _shell.DisconnectDeviceCommand.Execute(device);
        }
        CloseSettings();
    }

    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.SetLoggingMode
    private void SetLoggingMode(string? mode)
    {
        // The shell setter takes the label, drives device SwitchMode, and
        // refuses changes mid-session — we just forward the click.
        if (string.IsNullOrEmpty(mode) || _shell == null) return;
        _shell.SelectedLoggingMode = mode;
    }

    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.RebootSelected
    private void RebootSelected()
    {
        var device = SelectedDevice;
        if (device == null || _shell == null) return;
        if (_shell.RebootDeviceCommand.CanExecute(device))
        {
            _shell.RebootDeviceCommand.Execute(device);
        }
    }

    /// <summary>Detaches the singleton subscription and disposes tiles.</summary>
    // @port: Daqifi.Desktop.ViewModels.DevicesPaneViewModel.Dispose
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;

        ConnectionManager.Instance.PropertyChanged -= OnConnectionManagerPropertyChanged;

        foreach (var tile in Devices) tile.Dispose();
        Devices.Clear();

        GC.SuppressFinalize(this);
    }
}
