// Generated by portomatic scaffold from upstream Daqifi.Desktop/ViewModels/ExportDialogViewModel.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.Exporter;
using Daqifi.Desktop.Logger;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System.Diagnostics;
using System.IO;
using System.Windows.Input;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Platform.Storage;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace Daqifi.Desktop.ViewModels;

// @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel
public partial class ExportDialogViewModel : ObservableObject
{
    #region Private Variables
    private readonly List<int> _sessionsIds;
    private string _exportFilePath;
    private CancellationTokenSource _cts;

    // When true, every session is written as a separate "{session}.csv" file inside the
    // directory named by <see cref="ExportFilePath"/>, regardless of how many sessions are
    // being exported. Set only by the UI-test export hook (<see cref="ExportToDirectoryAsync"/>)
    // so a single-session export through the hook still lands in a directory the harness owns;
    // the interactive dialog leaves this false and keeps the file/directory-per-count behaviour.
    private bool _forceDirectoryLayout;

    [ObservableProperty]
    private bool _exportAllSelected = true;
    [ObservableProperty]
    private bool _exportAverageSelected;
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsConfiguring))]
    private bool _isExporting;
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsConfiguring))]
    private bool _isExportComplete;
    [ObservableProperty]
    private bool _exportSucceeded;
    [ObservableProperty]
    private string _exportResultMessage;
    [ObservableProperty]
    private int _averageQuantity = 2;
    [ObservableProperty]
    private string _exportProgressText;
    [ObservableProperty]
    private bool _exportRelativeTime;
    private int _exportProgress;
    #endregion

    #region Properties
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.ExportFilePath
    public string ExportFilePath
    {
        get => _exportFilePath;
        set
        {
            _exportFilePath = value;
            OnPropertyChanged();
            // WPF CommandManager.InvalidateRequerySuggested() has no Avalonia analog;
            // toolkit commands re-query via NotifyCanExecuteChanged() above.
            ExportLoggingSessionsCommand.NotifyCanExecuteChanged();
        }
    }

    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.ExportProgress
    public int ExportProgress
    {
        get => _exportProgress;
        set
        {
            _exportProgress = value;
            OnPropertyChanged();
            ExportProgressText = $"Exporting progress: {ExportProgress}% completed";
        }
    }

    /// <summary>
    /// True while the dialog is showing its configuration form — i.e. not mid-export and not
    /// showing the completion result. Selects which of the dialog's three states is visible.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.IsConfiguring
    public bool IsConfiguring => !IsExporting && !IsExportComplete;
    #endregion

    #region Commands
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.BrowseCommand
    public ICommand BrowseCommand { get; private set; }
    #endregion

    #region Constructor

    private readonly IDbContextFactory<LoggingContext> _loggingContext;
    public ExportDialogViewModel(int sessionId)
    {
        _loggingContext = App.ServiceProvider.GetRequiredService<IDbContextFactory<LoggingContext>>();
        _sessionsIds = [sessionId];
        BrowseCommand = BrowseExportPathCommand;
    }

    public ExportDialogViewModel(IEnumerable<LoggingSession> sessions)
    {
        _loggingContext = App.ServiceProvider.GetRequiredService<IDbContextFactory<LoggingContext>>();
        _sessionsIds = sessions.Select(s => s.ID).ToList();
        BrowseCommand = BrowseExportDirectoryCommand;
    }

    /// <summary>
    /// Test seam: supplies the logging-context factory directly so unit tests can exercise the
    /// dialog's state machine and export flow without booting the App/DI container.
    /// </summary>
    internal ExportDialogViewModel(IDbContextFactory<LoggingContext> loggingContext, int sessionId)
    {
        _loggingContext = loggingContext;
        _sessionsIds = [sessionId];
        BrowseCommand = BrowseExportPathCommand;
    }
    #endregion

    #region Private Methods

    [RelayCommand]
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.BrowseExportPath
    private async Task BrowseExportPathAsync()
    {
        // Win32 SaveFileDialog → StorageProvider save picker (hal: file_pickers), owned by
        // this dialog's window (fallback: main window).
        var owner = FindOwnerWindowForPicker();
        if (owner == null) { return; }

        var file = await owner.StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions
        {
            DefaultExtension = "csv",
            FileTypeChoices = new[] { new FilePickerFileType("Log File") { Patterns = new[] { "*.csv" } } }
        });

        var path = file?.TryGetLocalPath();
        if (path == null) { return; }

        ExportFilePath = path;
    }

    [RelayCommand]
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.BrowseExportDirectory
    private async Task BrowseExportDirectoryAsync()
    {
        // WinForms FolderBrowserDialog → StorageProvider folder picker (hal: file_pickers).
        var owner = FindOwnerWindowForPicker();
        if (owner == null) { return; }

        var folders = await owner.StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions
        {
            AllowMultiple = false
        });

        var path = folders.Count > 0 ? folders[0].TryGetLocalPath() : null;
        if (path == null) { return; }

        ExportFilePath = path;
    }

    private Window? FindOwnerWindowForPicker()
    {
        if (Application.Current?.ApplicationLifetime is not IClassicDesktopStyleApplicationLifetime desktop)
        {
            return null;
        }

        return desktop.Windows.FirstOrDefault(w => w.DataContext == this) ?? desktop.MainWindow;
    }

    [RelayCommand]
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.CancelExport
    private void CancelExport()
    {
        _cts?.Cancel();
    }

    [RelayCommand(CanExecute = nameof(CanExport))]
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.ExportLoggingSessions
    private async Task ExportLoggingSessions()
    {
        if (string.IsNullOrWhiteSpace(ExportFilePath)) { return; }

        IsExporting = true;
        IsExportComplete = false;
        _cts = new CancellationTokenSource();
        var cancellationToken = _cts.Token;
        var progress = new Progress<int>(progressValue => ExportProgress = progressValue);
        AppLogger.Instance.AddBreadcrumb("export", $"Data export started ({_sessionsIds.Count} session(s))");

        var cancelled = false;
        var failed = false;
        var failureMessage = "Export failed. Please try again.";
        try
        {
            await Task.Run(async () =>
            {
                var totalSessions = _sessionsIds.Count;
                for (var i = 0; i < totalSessions; i++)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    var sessionId = _sessionsIds[i];
                    var loggingSession = await GetLoggingSessionFromId(sessionId);
                    if (loggingSession == null)
                    {
                        AppLogger.Instance.Warning(
                            $"Skipping export for session {sessionId}: it was not found in the database.");
                        continue;
                    }

                    // Per-session file naming only applies when writing into a directory (multi-session
                    // export, or the directory-layout test hook). Resolve the display name lazily so a
                    // plain single-file export doesn't depend on LoggingManager — falling back to the
                    // default "Session_{id}" form when the session is no longer in the in-memory list.
                    string filepath;
                    if (_forceDirectoryLayout || totalSessions > 1)
                    {
                        var sessionName = LoggingManager.Instance.LoggingSessions
                            .FirstOrDefault(s => s.ID == sessionId)?.Name ?? $"Session_{sessionId}";
                        filepath = Path.Combine(ExportFilePath, $"{MakeSafeFileName(sessionName)}.csv");
                    }
                    else
                    {
                        filepath = ExportFilePath;
                    }

                    if (ExportAllSelected)
                    {
                        ExportAllSamples(loggingSession, filepath, progress, cancellationToken, i, totalSessions);
                    }
                    else if (ExportAverageSelected)
                    {
                        ExportAverageSamples(loggingSession, filepath, progress, cancellationToken, i, totalSessions);
                    }
                }
            }, cancellationToken);

            // Reaching here means the loop ran to completion without a cancellation being
            // observed at a checkpoint — a Cancel click that lands after the work is done no
            // longer suppresses the result state. Cancellation is signalled only by the
            // OperationCanceledException path below.
            AppLogger.Instance.AddBreadcrumb("export", "Data export completed");
        }
        catch (OperationCanceledException)
        {
            cancelled = true;
            AppLogger.Instance.Information("Export operation was cancelled by user.");
            AppLogger.Instance.AddBreadcrumb("export", "Data export cancelled", Common.Loggers.BreadcrumbLevel.Warning);
        }
        catch (Exception ex)
        {
            failed = true;
            // Any write-side failure to the chosen destination surfaces as IOException — or a subtype:
            // DirectoryNotFoundException for a removed drive / unreachable share, a bare disk-full
            // IOException, PathTooLongException for a long session name. The exporter's void methods now
            // propagate it instead of swallowing it as a false success; give an actionable hint that
            // covers the plausible causes without over-claiming any single one (issue #747).
            failureMessage = ex is IOException
                ? "Export failed — could not write to the destination. It may be open in another program, on a disconnected drive, or the disk may be full. Check the destination and try again."
                : "Export failed. Please try again.";
            AppLogger.Instance.Error(ex, "Problem Exporting Data");
            AppLogger.Instance.AddBreadcrumb("export", "Data export failed", Common.Loggers.BreadcrumbLevel.Error);
        }
        finally
        {
            _cts.Dispose();
            _cts = null;

            // A cancel returns to the configuration form; a success or failure shows the
            // result state (set complete before clearing IsExporting so IsConfiguring never
            // flips true in between).
            if (!cancelled)
            {
                ExportSucceeded = !failed;
                ExportResultMessage = failed ? failureMessage : "Export complete";
                IsExportComplete = true;
            }

            IsExporting = false;
        }
    }

    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.CanExport
    private bool CanExport => !string.IsNullOrWhiteSpace(ExportFilePath);

    /// <summary>
    /// Opens the export destination in File Explorer: the folder itself for a directory export,
    /// or the containing folder with the file selected for a single-file export.
    /// </summary>
    [RelayCommand]
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.OpenExportLocation
    private void OpenExportLocation()
    {
        try
        {
            if (string.IsNullOrWhiteSpace(ExportFilePath)) { return; }

            if (Directory.Exists(ExportFilePath))
            {
                Process.Start(new ProcessStartInfo("explorer.exe", $"\"{ExportFilePath}\"") { UseShellExecute = true });
            }
            else if (File.Exists(ExportFilePath))
            {
                Process.Start(new ProcessStartInfo("explorer.exe", $"/select,\"{ExportFilePath}\"") { UseShellExecute = true });
            }
            else
            {
                var directory = Path.GetDirectoryName(ExportFilePath);
                if (!string.IsNullOrEmpty(directory) && Directory.Exists(directory))
                {
                    Process.Start(new ProcessStartInfo("explorer.exe", $"\"{directory}\"") { UseShellExecute = true });
                }
            }
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Warning(ex, $"Could not open export location '{ExportFilePath}'.");
        }
    }

    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.ExportAllSamples
    private void ExportAllSamples(LoggingSession session, string filepath, IProgress<int> progress, CancellationToken cancellationToken, int sessionIndex, int totalSessions)
    {
        var loggingSessionExporter = new OptimizedLoggingSessionExporter(_loggingContext);
        loggingSessionExporter.ExportLoggingSession(session, filepath, ExportRelativeTime, progress, cancellationToken, sessionIndex, totalSessions);
    }

    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.ExportAverageSamples
    private void ExportAverageSamples(LoggingSession session, string filepath, IProgress<int> progress, CancellationToken cancellationToken, int sessionIndex, int totalSessions)
    {
        var loggingSessionExporter = new OptimizedLoggingSessionExporter(_loggingContext);
        loggingSessionExporter.ExportAverageSamples(session, filepath, AverageQuantity, ExportRelativeTime, progress, cancellationToken, sessionIndex, totalSessions);
    }

    /// <summary>
    /// Replaces characters that are invalid in a file name (a session can be renamed to arbitrary
    /// text) with '_', so per-session export to <c>{name}.csv</c> never throws on a bad path.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.MakeSafeFileName
    private static string MakeSafeFileName(string name)
    {
        foreach (var invalid in Path.GetInvalidFileNameChars())
        {
            name = name.Replace(invalid, '_');
        }

        return name;
    }

    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.GetLoggingSessionFromId
    private async Task<LoggingSession> GetLoggingSessionFromId(int sessionId)
    {
        await using var context = _loggingContext.CreateDbContext();
        var loggingSession = await context.Sessions
            .AsNoTracking()
            .Where(s => s.ID == sessionId)
            .Select(s => new LoggingSession
            {
                ID = s.ID
            }).FirstOrDefaultAsync();
        return loggingSession;
    }
    #endregion

    #region Test Hook
    /// <summary>
    /// UI-test entry point: exports the configured session(s) straight into
    /// <paramref name="directory"/> — one <c>{session}.csv</c> per session — using the same
    /// exporter and the dialog's default options (all samples, absolute time), with no
    /// <c>SaveFileDialog</c>/<c>FolderBrowserDialog</c>. Wired only through the
    /// <see cref="Daqifi.Desktop.Common.AppDataPaths.TestExportPath"/> hook, so production
    /// export behaviour is unchanged. Awaitable so the harness can know when the file is on disk.
    /// </summary>
    /// <param name="directory">Destination directory (created if missing) the harness owns.</param>
    // @port: Daqifi.Desktop.ViewModels.ExportDialogViewModel.ExportToDirectoryAsync
    internal Task ExportToDirectoryAsync(string directory)
    {
        Directory.CreateDirectory(directory);
        _forceDirectoryLayout = true;
        ExportFilePath = directory;
        return ExportLoggingSessionsCommand.ExecuteAsync(null);
    }
    #endregion
}
