// Generated by portomatic scaffold from upstream Daqifi.Desktop/ViewModels/LoggingSessionListViewModel.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.Logger;
using Microsoft.EntityFrameworkCore;

namespace Daqifi.Desktop.ViewModels;

/// <summary>
/// Owns the logged-data pane's session-list actions — displaying a session on the plot, exporting
/// one or all sessions, deleting one or all sessions, and keeping the bound session collection's
/// change notifications wired.
/// <para>
/// Extracted from <c>DaqifiViewModel</c> (issue #592). Every collaborator is constructor-injected
/// (the logging-context factory resolver, the database file path, the application logger) and all
/// plot/database, dialog, and notification side effects are reached through the
/// <see cref="ILoggingSessionListHost"/> seam — so this class has no dependency on WPF or on desktop
/// singletons (<c>LoggingManager.Instance</c>, <c>App.ServiceProvider</c>, <c>App.DatabasePath</c>)
/// and is unit-testable in isolation. The legacy <c>BackgroundWorker</c> the display and delete
/// paths used has been replaced with the file's async/await + busy-flag pattern.
/// </para>
/// </summary>
// @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel
public class LoggingSessionListViewModel
{
    #region Private Fields
    private readonly ILoggingSessionListHost _host;
    private readonly Func<IDbContextFactory<LoggingContext>> _loggingContextFactoryResolver;
    private readonly string _databasePath;
    private readonly IAppLogger _appLogger;
    private ObservableCollection<LoggingSession>? _observedLoggingSessions;
    #endregion

    #region Constructor
    /// <summary>
    /// Creates the list view model. The composition root (the view model / DI container) is
    /// responsible for resolving the production collaborators so this class never reaches into
    /// singletons.
    /// </summary>
    /// <param name="host">The host view-model surface the list reads state from and pushes effects to.</param>
    /// <param name="loggingContextFactoryResolver">
    /// Resolves the logging-context factory used by the "delete all" storage purge. A resolver
    /// (rather than the factory itself) preserves the host's lazy resolution + clear failure when no
    /// factory is available.
    /// </param>
    /// <param name="databasePath">Absolute path to the SQLite database file (and its -wal/-shm siblings).</param>
    /// <param name="appLogger">Application logger used for diagnostics.</param>
    public LoggingSessionListViewModel(
        ILoggingSessionListHost host,
        Func<IDbContextFactory<LoggingContext>> loggingContextFactoryResolver,
        string databasePath,
        IAppLogger appLogger)
    {
        _host = host ?? throw new ArgumentNullException(nameof(host));
        _loggingContextFactoryResolver = loggingContextFactoryResolver ?? throw new ArgumentNullException(nameof(loggingContextFactoryResolver));
        _databasePath = databasePath ?? throw new ArgumentNullException(nameof(databasePath));
        _appLogger = appLogger ?? throw new ArgumentNullException(nameof(appLogger));
    }
    #endregion

    #region Display
    /// <summary>
    /// Loads the selected session onto the logged-data plot. A null session clears the plot. The
    /// blocking <c>DbLogger</c> load runs off the UI thread under the busy flag (replacing the legacy
    /// <c>BackgroundWorker</c>); load failures are logged and never propagate.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel.DisplaySessionAsync
    public async Task DisplaySessionAsync(LoggingSession? session)
    {
        if (session == null)
        {
            _host.ClearPlot();
            return;
        }

        _host.SelectedLoggingSession = session;
        _host.IsLoggedDataBusy = true;
        _host.LoggedDataBusyReason = "Loading " + session.Name;
        try
        {
            await Task.Run(() =>
            {
                try
                {
                    _host.DisplaySessionOnPlot(session);
                }
                catch (Exception ex)
                {
                    _appLogger.Error(ex, $"Failed to display logging session {session.ID}.");
                }
            });
        }
        finally
        {
            _host.IsLoggedDataBusy = false;
            _host.LoggedDataBusyReason = string.Empty;
        }
    }
    #endregion

    #region Export
    /// <summary>Exports a single session via the export dialog.</summary>
    // @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel.ExportSessionAsync
    public async Task ExportSessionAsync(LoggingSession? session)
    {
        if (session == null)
        {
            _appLogger.Error("Error exporting logging session");
            return;
        }

        _host.SelectedLoggingSession = session;
        await _host.ShowExportDialogForSessionAsync(session.ID);
    }

    /// <summary>Exports every session via the export dialog.</summary>
    // @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel.ExportAllSessionsAsync
    public async Task ExportAllSessionsAsync()
    {
        if (_host.LoggingSessions.Count == 0)
        {
            _appLogger.Error("Error exporting all logging sessions");
            return;
        }

        await _host.ShowExportDialogForSessionsAsync(_host.LoggingSessions.ToList());
    }
    #endregion

    #region Delete
    /// <summary>
    /// Deletes a single session after confirmation. The blocking <c>DbLogger</c> delete runs off the
    /// UI thread under the busy flag (replacing the legacy <c>BackgroundWorker</c>); the session is
    /// removed from the bound collection only when the database delete succeeds.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel.DeleteSessionAsync
    public async Task DeleteSessionAsync(LoggingSession? session)
    {
        try
        {
            if (session == null)
            {
                _appLogger.Error("Error deleting logging session: Invalid object provided.");
                return;
            }

            _host.SelectedLoggingSession = session;

            var confirmed = await _host.ShowConfirmAsync(
                "Delete Confirmation",
                $"Are you sure you want to delete {session.Name}?",
                affirmativeLabel: "DELETE",
                isDestructive: true);
            if (!confirmed)
            {
                return;
            }

            _host.IsLoggedDataBusy = true;
            _host.LoggedDataBusyReason = $"Deleting Logging Session #{session.ID}";
            try
            {
                // Remove the bound row only when the database delete reports success — the gating is
                // preserved verbatim from the pre-extraction DaqifiViewModel. The production host
                // routes DeleteSessionFromDatabase to DatabaseLogger.DeleteLoggingSession, which since
                // the SessionDataRepository extraction (#592) rethrows on failure instead of swallowing
                // it — so this is now a live failure path: a failed delete throws, deleteSucceeded stays
                // false, and the row is kept rather than silently dropped while its data still exists.
                var deleteSucceeded = false;
                try
                {
                    await Task.Run(() => _host.DeleteSessionFromDatabase(session));
                    deleteSucceeded = true;
                }
                catch (Exception dbEx)
                {
                    _appLogger.Error(dbEx, $"Failed to delete session {session.ID} from database.");
                }

                if (deleteSucceeded)
                {
                    _host.LoggingSessions.Remove(session);
                    _host.NotifyLoggingSessionsChanged();
                }
            }
            finally
            {
                _host.IsLoggedDataBusy = false;
                _host.LoggedDataBusyReason = string.Empty;
            }
        }
        catch (Exception ex)
        {
            _appLogger.Error(ex, "Error initiating logging session deletion");
        }
    }

    /// <summary>
    /// Deletes every session. Refuses to run while logging is active, confirms the destructive
    /// action, then purges the database storage off the UI thread under the busy flag.
    /// </summary>
    /// <remarks>
    /// A purge that fails now keeps the session list and tells the user, instead of clearing the
    /// pane or leaving a log line as the only trace (#183). The two are the same decision: the
    /// storage purge either replaced the database or left it untouched, so the list is right to go
    /// on showing exactly what is still on disk.
    /// <para>
    /// There is a third outcome between those two, and it also gets said out loud: the empty
    /// database is in place (so the list is right to clear) but the old file could not be deleted,
    /// which means the destructive thing the user asked for has not actually happened yet.
    /// </para>
    /// </remarks>
    // @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel.DeleteAllSessionsAsync
    public async Task DeleteAllSessionsAsync()
    {
        // Held over the busy flag's finally so the dialog is shown after the pane stops saying it is
        // deleting, rather than behind a spinner that never clears.
        (string Title, string Message)? dialog = null;

        try
        {
            if (_host.LoggingSessions.Count == 0)
            {
                return;
            }

            if (_host.IsLoggingActive)
            {
                await _host.ShowMessageAsync(
                    "Cannot Delete",
                    "Please stop logging before deleting all sessions.");
                return;
            }

            var confirmed = await _host.ShowConfirmAsync(
                "Delete Confirmation",
                "Are you sure you want to delete all logging sessions? This cannot be undone.",
                affirmativeLabel: "DELETE ALL",
                isDestructive: true);
            if (!confirmed)
            {
                return;
            }

            _host.IsLoggedDataBusy = true;
            _host.LoggedDataBusyReason = "Deleting All Logging Sessions";

            try
            {
                var contextFactory = _loggingContextFactoryResolver();
                var leftOnDisk = await Task.Run(() => DeleteAllLoggingSessionsFromStorage(contextFactory));

                // Only past the purge. Clearing here on a failed purge is what left the pane showing
                // sessions whose data was already gone — or, worse, hiding sessions that are still
                // there because the purge put them back.
                _host.LoggingSessions.Clear();
                _host.NotifyLoggingSessionsChanged();
                _host.ClearPlot();

                // The empty database is live, so the list above is right to be empty — but the old
                // file is still on disk, and a user deleting their sessions is entitled to know the
                // deletion did not finish.
                if (leftOnDisk != null)
                {
                    _appLogger.Warning(leftOnDisk);
                    dialog = ("Delete Incomplete", leftOnDisk);
                }
            }
            catch (Exception ex)
            {
                _appLogger.Error(ex, "Failed to delete all logging sessions");

                // The migrator's own message is already written for a user and says what became of
                // their data, so it is shown verbatim.
                dialog = ("Delete Failed", ex is DatabaseReplacementException replacement
                    ? replacement.Message
                    : "The logging sessions could not be deleted. See the application log for details.");
            }
        }
        catch (Exception ex)
        {
            _appLogger.Error(ex, "Error during deletion of all logging sessions");
        }
        finally
        {
            _host.IsLoggedDataBusy = false;
            _host.LoggedDataBusyReason = string.Empty;
        }

        if (dialog is { } toShow)
        {
            try
            {
                await _host.ShowMessageAsync(toShow.Title, toShow.Message);
            }
            catch (Exception ex)
            {
                // Outside the guard above, so its own failure would otherwise escape this method and
                // reach the command that invoked it — which is the shape of crash #183 is about.
                _appLogger.Error(ex, "Failed to show the delete-all result dialog");
            }
        }
    }

    /// <summary>
    /// Purges the database storage. Runs off the UI thread.
    /// </summary>
    /// <returns>
    /// <c>null</c> when everything went, or a sentence for the user when the empty database is in
    /// place but the old file could not be removed. Throws when nothing was deleted at all.
    /// </returns>
    // @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel.DeleteAllLoggingSessionsFromStorage
    private string? DeleteAllLoggingSessionsFromStorage(IDbContextFactory<LoggingContext> contextFactory)
    {
        _host.SuspendConsumer();
        var purgeSucceeded = false;
        try
        {
            _host.ClearBuffer();

            // Move the old database and every journal sidecar aside, build the empty replacement,
            // and only then delete what was moved. Deleting first — which is what this did, and it
            // missed "-journal" while it was at it — left a table-less database behind whenever
            // anything after the first delete failed, and the next logging toggle died on it (#183).
            // Throws when the database is untouched or was preserved, with a message for the user.
            var leftOnDisk = DatabaseMigrator.ReplaceWithEmptyDatabase(contextFactory, _databasePath);
            purgeSucceeded = true;
            return leftOnDisk;
        }
        finally
        {
            // Discard any batch the consumer retained after a failed commit — but ONLY when the wipe
            // actually succeeded. ClearBuffer empties just the producer buffer; a stranded batch lives
            // in the consumer's local list and would otherwise repopulate the recreated database on
            // resume. If the purge failed (e.g. the file was locked), the database is still intact and
            // the sessions remain, so dropping the batch would silently lose unflushed samples —
            // leaving it lets the consumer commit them to the surviving database instead. Requested
            // before ResumeConsumer so the consumer honors it before its next insert.
            if (purgeSucceeded)
            {
                _host.DiscardPendingBatch();
            }

            _host.ResumeConsumer();
        }
    }

    #endregion

    #region Collection plumbing
    /// <summary>
    /// Subscribes to the supplied session collection's change notifications, replacing any prior
    /// subscription. The host re-supplies the collection whenever the logging manager swaps it out.
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel.AttachCollection
    public void AttachCollection(ObservableCollection<LoggingSession> loggingSessions)
    {
        if (ReferenceEquals(_observedLoggingSessions, loggingSessions))
        {
            return;
        }

        if (_observedLoggingSessions != null)
        {
            _observedLoggingSessions.CollectionChanged -= OnLoggingSessionsCollectionChanged;
        }

        _observedLoggingSessions = loggingSessions;
        _observedLoggingSessions.CollectionChanged += OnLoggingSessionsCollectionChanged;
    }

    /// <summary>
    /// Unsubscribes from the currently-observed session collection, if any. Called by the host on
    /// teardown so the long-lived <c>LoggingManager.Instance.LoggingSessions</c> collection does not
    /// keep this view model (and, through it, the host) alive (issue #592).
    /// </summary>
    // @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel.DetachCollection
    public void DetachCollection()
    {
        if (_observedLoggingSessions == null)
        {
            return;
        }

        _observedLoggingSessions.CollectionChanged -= OnLoggingSessionsCollectionChanged;
        _observedLoggingSessions = null;
    }

    // @port: Daqifi.Desktop.ViewModels.LoggingSessionListViewModel.OnLoggingSessionsCollectionChanged
    private void OnLoggingSessionsCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e)
    {
        // The host owns the UI-thread marshalling so this class stays dispatcher-free.
        _host.NotifyLoggingSessionsChanged();
    }
    #endregion
}
