// Generated by portomatic scaffold from upstream Daqifi.Desktop/ViewModels/NewProfileDeviceItem.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using Daqifi.Desktop.Device;

namespace Daqifi.Desktop.ViewModels;

/// <summary>
/// Wraps a connected device for the new-profile creation form so each item
/// carries its own IsSelected state and a nested channel list.
/// </summary>
// @port: Daqifi.Desktop.ViewModels.NewProfileDeviceItem
public partial class NewProfileDeviceItem : ObservableObject
{
    private bool _isSelected;

    // @port: Daqifi.Desktop.ViewModels.NewProfileDeviceItem.Device
    public IStreamingDevice Device
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.ViewModels.NewProfileDeviceItem.Name
    public string Name
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.ViewModels.NewProfileDeviceItem.SerialNo
    public string SerialNo
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.ViewModels.NewProfileDeviceItem.ChannelItems
    public ObservableCollection<NewProfileChannelItem> ChannelItems
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }
}
