// Generated by portomatic scaffold from upstream Daqifi.Desktop/ViewModels/NewProfileChannelItem.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.ViewModels;

/// <summary>
/// Wraps a channel for the new-profile creation form so each channel row
/// carries its own IsSelected state independent of the underlying channel.
/// </summary>
// @port: Daqifi.Desktop.ViewModels.NewProfileChannelItem
public partial class NewProfileChannelItem : ObservableObject
{
    private bool _isSelected;

    // @port: Daqifi.Desktop.ViewModels.NewProfileChannelItem.Channel
    public IChannel Channel
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.ViewModels.NewProfileChannelItem.Name
    public string Name
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }
}
