// Generated by portomatic scaffold from upstream Daqifi.Desktop/ViewModels/PlotViewModel.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Daqifi.Desktop.Channel;
using OxyPlot;
using OxyPlot.Series;
using System.IO;
using System.Linq;

namespace Daqifi.Desktop.ViewModels;

// @port: Daqifi.Desktop.ViewModels.PlotViewModel
public class PlotViewModel
{
    public IEventLogger EventLogger;

    // @port: Daqifi.Desktop.ViewModels.PlotViewModel.PlotModel
    public PlotModel PlotModel
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    public Dictionary<string, List<DataPoint>> SessionPoints;

    // @port: Daqifi.Desktop.ViewModels.PlotViewModel.ClearPlot
    public void ClearPlot() => throw new NotImplementedException();

    // @port: Daqifi.Desktop.ViewModels.PlotViewModel.AddChannel
    public void AddChannel(string channelName, ChannelType type, string color) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.ViewModels.PlotViewModel.SavePlot
    private void SavePlot(object o) => throw new NotImplementedException();
}
