// Generated by portomatic scaffold from upstream Daqifi.Desktop/ViewModels/SettingsViewModel.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using CommunityToolkit.Mvvm.ComponentModel;
using Daqifi.Desktop.Models;

namespace Daqifi.Desktop.ViewModels;

// @port: Daqifi.Desktop.ViewModels.SettingsViewModel
public partial class SettingsViewModel : ObservableObject
{
    private readonly DaqifiSettings _settings = DaqifiSettings.Instance;

    // @port: Daqifi.Desktop.ViewModels.SettingsViewModel.CsvDelimiter
    public string CsvDelimiter
    {
        get => _settings.CsvDelimiter;
        set
        {
            if (_settings.CsvDelimiter == value) return;
            _settings.CsvDelimiter = value;
            OnPropertyChanged();
            OnPropertyChanged(nameof(IsCommaDelimiter));
            OnPropertyChanged(nameof(IsSemicolonDelimiter));
        }
    }

    // @port: Daqifi.Desktop.ViewModels.SettingsViewModel.IsCommaDelimiter
    public bool IsCommaDelimiter
    {
        get => CsvDelimiter == ",";
        set
        {
            if (value) CsvDelimiter = ",";
        }
    }

    // @port: Daqifi.Desktop.ViewModels.SettingsViewModel.IsSemicolonDelimiter
    public bool IsSemicolonDelimiter
    {
        get => CsvDelimiter == ";";
        set
        {
            if (value) CsvDelimiter = ";";
        }
    }
}
