// Generated by portomatic scaffold from upstream Daqifi.Desktop/View/DebugWindow.xaml.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Avalonia.Controls;
using Avalonia.Interactivity;
using Daqifi.Desktop.ViewModels;

namespace Daqifi.Desktop.View;

/// <summary>
/// Interaction logic for DebugWindow.xaml
/// </summary>
// MahApps MetroWindow → Avalonia Window (dialog_service dialect).
// @port: Daqifi.Desktop.View.DebugWindow
public partial class DebugWindow : Window
{
    /// <summary>
    /// Required by compiled bindings, not called by the app: with <c>x:CompileBindings="True"</c> on
    /// the root, a view with no public parameterless constructor is <c>AVLN3000</c>, a build error
    /// (issue #327). The one real construction site is <see cref="DaqifiViewModel"/>'s
    /// <c>OpenDebugWindow</c>, through the overload below.
    /// </summary>
    public DebugWindow()
    {
        InitializeComponent();
    }

    public DebugWindow(DaqifiViewModel viewModel) : this()
    {
        DataContext = viewModel;
    }

    // @port: Daqifi.Desktop.View.DebugWindow.CloseButton_Click
    private void CloseButton_Click(object sender, RoutedEventArgs e)
    {
        Close();
    }
}
