// Generated by portomatic scaffold from upstream Daqifi.Desktop/View/DebugWindow.xaml.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Avalonia.Controls;
using Avalonia.Interactivity;
using Daqifi.Desktop.ViewModels;

namespace Daqifi.Desktop.View;

/// <summary>
/// Interaction logic for DebugWindow.xaml
/// </summary>
// MahApps MetroWindow → Avalonia Window (dialog_service dialect).
// @port: Daqifi.Desktop.View.DebugWindow
public partial class DebugWindow : Window
{
    public DebugWindow(DaqifiViewModel viewModel)
    {
        InitializeComponent();
        DataContext = viewModel;
    }

    // @port: Daqifi.Desktop.View.DebugWindow.CloseButton_Click
    private void CloseButton_Click(object sender, RoutedEventArgs e)
    {
        Close();
    }
}
