// Generated by portomatic scaffold from upstream Daqifi.Desktop/ConnectionManager.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Daqifi.Desktop.Channel;
using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.Device;
using Daqifi.Desktop.Device.SerialDevice;
using Daqifi.Desktop.Logger;
using Daqifi.Desktop.Services.DeviceWatcher;
using System.ComponentModel;
using System.IO.Ports;
using CommunityToolkit.Mvvm.ComponentModel;
using Avalonia.Threading;
using CoreDeviceErrorEventArgs = Daqifi.Core.Device.DeviceErrorEventArgs;
using CoreSendFailedEventArgs = Daqifi.Core.Communication.Producers.MessageSendFailedEventArgs<string>;
using DeviceErrorSource = Daqifi.Core.Device.DeviceErrorSource;
using DeviceIdentity = Daqifi.Core.Device.DeviceIdentity;

namespace Daqifi.Desktop;

// @port: Daqifi.Desktop.ConnectionManager
public partial class ConnectionManager : ObservableObject
{
    #region Constants
    /// <summary>
    /// Longest SCPI verb written to the log when a send fails. Real verbs are far shorter; the cap
    /// only exists so a malformed payload cannot turn one failure into a wall of log.
    /// </summary>
    private const int MAX_LOGGED_COMMAND_LENGTH = 64;
    #endregion

    #region Private Variables
    // The ONE watcher instance the device_watcher mechanism allows; the backend behind it is
    // chosen per platform (WMI on Windows, serial-port polling on macOS/Linux, no-op elsewhere).
    // Rooted by the singleton and never stopped, matching the lifetime the WMI watcher it replaces
    // already had: it must observe removals for as long as the app can hold a device, which is the
    // whole process lifetime.
    private readonly IDeviceWatcher _deviceWatcher;

    /// <summary>
    /// The logger's own view of what it is holding, and how one entry is released. Null in the
    /// singleton, which resolves <see cref="LoggingManager"/> lazily through
    /// <see cref="SubscribedChannels"/> and <see cref="UnsubscribeChannel"/>; set by the test
    /// constructor.
    /// </summary>
    /// <remarks>
    /// The indirection exists because <see cref="LoggingManager"/> is itself a singleton whose
    /// constructor resolves an EF Core context factory out of <c>App.ServiceProvider</c> — i.e. it
    /// cannot be constructed at all without a running Avalonia application. Teardown is the one
    /// behaviour on this class worth pinning with a test, so it gets the seams that make that
    /// possible, and production keeps the direct singleton calls it always had.
    /// </remarks>
    private readonly Func<IReadOnlyList<IChannel>>? _subscribedChannels;

    /// <inheritdoc cref="_subscribedChannels" />
    private readonly Action<IChannel>? _unsubscribeChannel;

    /// <summary>
    /// How teardown reaches the UI thread. Null in the singleton, which uses
    /// <see cref="PostToUiThread"/>; set by the test constructor to run inline.
    /// </summary>
    /// <remarks>
    /// <see cref="Dispatcher"/><c>.UIThread</c> outside a running Avalonia application binds to
    /// whichever thread touched it first and queues everything else until something pumps it —
    /// which in a test host is never. Injecting the marshal is what makes the teardown assertions
    /// deterministic instead of dependent on the test runner's thread scheduling. The marshalling
    /// itself is Avalonia plumbing shared with every other producer in this class; what these tests
    /// are for is what happens once the teardown runs.
    /// </remarks>
    private readonly Action<Action>? _postToUiThread;
    #endregion

    #region Properties
    [ObservableProperty]
    private DAQiFiConnectionStatus _connectionStatus = DAQiFiConnectionStatus.Disconnected;

    [ObservableProperty]
    private List<IStreamingDevice> _connectedDevices;

    [ObservableProperty]
    private bool _isDisconnected = true;

    [ObservableProperty]
    private bool _notifyConnection;

    // @port: Daqifi.Desktop.ConnectionManager.ConnectionStatusString
    public string ConnectionStatusString { get; set; } = "Disconnected";

    /// <summary>
    /// Why the most recent unexpected teardown happened, phrased for the user and naming the
    /// device — e.g. <c>"Nq1-0123 disconnected (connection lost)."</c>. Set immediately before
    /// <see cref="NotifyConnection"/> is raised, and cleared by the handler that shows it.
    /// </summary>
    /// <remarks>
    /// Empty means "no specific reason", and the notification falls back to its generic wording.
    /// Written and read on the UI thread only: every producer marshals through
    /// <see cref="PostToUiThread"/> first, and the single consumer is
    /// <c>DaqifiViewModel</c>'s <c>NotifyConnection</c> handler.
    /// </remarks>
    // @port: Daqifi.Desktop.ConnectionManager.LastDisconnectReason
    public string LastDisconnectReason { get; set; } = string.Empty;

    /// <summary>
    /// Callback for handling duplicate device situations.
    /// Should return the user's choice on how to handle the duplicate.
    /// </summary>
    // @port: Daqifi.Desktop.ConnectionManager.DuplicateDeviceHandler
    // Dialect divergence: Avalonia dialogs are async-only (no WPF ShowDialog nested message
    // pump), so the handler is Task-returning and Connect awaits it — same async-dialogs
    // dialect as IMessageBoxService.ShowAsync.
    public Func<DuplicateDeviceCheckResult, Task<DuplicateDeviceAction>> DuplicateDeviceHandler { get; set; }

    /// <summary>
    /// Tracks the device currently undergoing firmware update. Non-null for the whole update (PIC32 +
    /// WiFi + the post-flash serial reconnect), so it doubles as the app-global "firmware update in
    /// progress" gate: while it is set, the connection dialog suspends its serial/WiFi discovery and
    /// <see cref="Connect"/> refuses USB connects, so nothing races Core's post-flash reconnect for the
    /// COM port (issue #738). Changing it raises <see cref="FirmwareUpdateInProgressChanged"/> so an
    /// already-open connection dialog can react immediately.
    /// </summary>
    // @port: Daqifi.Desktop.ConnectionManager.DeviceBeingUpdated
    public IStreamingDevice? DeviceBeingUpdated
    {
        get => _deviceBeingUpdated;
        set
        {
            if (ReferenceEquals(_deviceBeingUpdated, value)) { return; }

            var previous = _deviceBeingUpdated;
            var wasInProgress = _deviceBeingUpdated != null;
            _deviceBeingUpdated = value;

            // Only raise when the in-progress state actually flips (set from null / cleared to null),
            // not on a device-to-device change (which never happens today, but keeps the signal clean).
            if (wasInProgress != (value != null))
            {
                FirmwareUpdateInProgressChanged?.Invoke(this, EventArgs.Empty);
            }

            // When the update ends, reconcile the device whose teardown we suppressed during the flash.
            // On a successful flash Core reconnected it (IsConnected == true) and there's nothing to do;
            // but on a failed reconnect (e.g. a JumpingToApp timeout) it is still in ConnectedDevices with
            // a dead transport, so without this it would show as connected forever and block a clean
            // reconnect. Tear it down now, matching the normal disconnect path (issue #738 follow-up).
            if (previous != null && value == null)
            {
                ReconcileDeviceAfterUpdate(previous);
            }
        }
    }

    private IStreamingDevice? _deviceBeingUpdated;

    /// <summary>
    /// After a firmware update ends, tears down the just-updated device iff Core's post-flash reconnect
    /// left it disconnected. A successful update reconnects the device (no-op here); a failed one leaves
    /// a stale entry the desktop's teardown paths deliberately skipped during the flash, so reconcile it
    /// exactly as a normal disconnect would (unsubscribe channels, Disconnect). Teardown ONLY — see the
    /// note below on why the port does not raise the generic disconnect alarm here.
    /// </summary>
    // @port: Daqifi.Desktop.ConnectionManager.ReconcileDeviceAfterUpdate
    private void ReconcileDeviceAfterUpdate(IStreamingDevice device)
    {
        // @port-divergence: upstream marshals via UiThreadHelper.InvokeOnUiThread and, after the
        // teardown, sets a SCOPED LastDisconnectReason ("… did not reconnect after the firmware update.
        // Power-cycle …") which its NotifyConnection handler surfaces as that specific message. The port
        // has no LastDisconnectReason — its NotifyConnection handler shows a FIXED generic "Device
        // disconnected unexpectedly." So raising NotifyConnection here would pop that alarming,
        // contradictory dialog right after the firmware coordinator already showed the correct outcome
        // dialog (e.g. the JumpingToApp "firmware installed, power-cycle" message) — two conflicting
        // dialogs for one event. Instead do teardown ONLY: Unsubscribe + Disconnect clean up the stale
        // entry (the device-list UI updates from the resulting ConnectedDevices change), and all user
        // messaging is left to the firmware coordinator, which owns the success/failure dialog. Marshal
        // with the port's Dispatcher.UIThread.Post (non-blocking; this setter can fire from the firmware
        // task's continuation thread).
        Dispatcher.UIThread.Post(() =>
        {
            // Post is deferred, so a NEW firmware update for this device may have started between the
            // clear that queued this and now (rapid consecutive updates). If so, defer to that update
            // rather than tearing down a device that is being flashed again — the same #738 invariant
            // the WMI teardown path (CheckIfSerialDeviceWasRemoved) guards. Also nothing to do if it
            // reconnected cleanly or was already removed by another path.
            if (IsDeviceBeingUpdated(device) || !ConnectedDevices.Contains(device) || device.IsConnected)
            {
                return;
            }

            foreach (var channel in device.DataChannels)
            {
                LoggingManager.Instance.Unsubscribe(channel);
            }

            Disconnect(device);
        });
    }

    /// <summary>
    /// True while a firmware update is in progress (<see cref="DeviceBeingUpdated"/> is set). The
    /// connection dialog gates its discovery on this, and <see cref="Connect"/> refuses USB connects
    /// while it is true, so a user-initiated connect or a discovery probe cannot steal the COM port
    /// during Core's post-flash serial reconnect window (issue #738).
    /// </summary>
    // @port: Daqifi.Desktop.ConnectionManager.IsFirmwareUpdateInProgress
    public bool IsFirmwareUpdateInProgress => _deviceBeingUpdated != null;

    /// <summary>
    /// Raised when <see cref="IsFirmwareUpdateInProgress"/> flips. The connection dialog subscribes so a
    /// dialog that is already open when a flash starts stops its serial/WiFi discovery immediately (and
    /// resumes it when the flash ends) — the push half of the coordination; the pull half is the guards
    /// in the dialog's <c>Start*Discovery</c> and in <see cref="Connect"/>.
    /// </summary>
    // @port: Daqifi.Desktop.ConnectionManager.FirmwareUpdateInProgressChanged
    public event EventHandler? FirmwareUpdateInProgressChanged;

    #endregion

    // @port: Daqifi.Desktop.ConnectionManager.OnConnectionStatusChanged
    partial void OnConnectionStatusChanged(DAQiFiConnectionStatus value)
    {
        UpdateStatusString();
        IsDisconnected = value != DAQiFiConnectionStatus.Connected;
    }

    #region Singleton Constructor / Initalization
    private static readonly ConnectionManager instance = new();

    private ConnectionManager()
    {
        ConnectedDevices = new List<IStreamingDevice>();

        // Upstream constructed the WMI watcher inline here, which threw PlatformNotSupportedException
        // on every non-Windows head and left USB-removal detection dead (issue #90). The backend is
        // now chosen per platform behind IDeviceWatcher; macOS and Linux get a real, working one.
        //
        // The catch stays load-bearing: this runs from a static field initializer, so an escaping
        // exception would surface as a fatal TypeInitializationException at first access of Instance.
        // Backend selection is inside it for that reason. What changes is that the degradation no
        // longer ends here — it is recorded and shown to the user (see the property below).
        IDeviceWatcher? watcher = null;
        try
        {
            watcher = DeviceWatcherFactory.Create();
            watcher.DeviceRemoved += (sender, eventArgs) => CheckIfSerialDeviceWasRemoved();
            watcher.Start();
            _deviceWatcher = watcher;

            // Which backend a machine picked is the first thing to check when a support report says
            // "unplugging did nothing", so record it rather than leaving it to be inferred.
            AppLogger.Instance.Information(
                "USB hotplug detection backend: " + _deviceWatcher.GetType().Name);
        }
        catch (Exception ex)
        {
            // Release whatever the failed backend managed to allocate before its Start() threw —
            // WmiDeviceWatcher, for one, assigns its ManagementEventWatcher and hooks its event
            // before the Start() call that can throw — then install the backend that is guaranteed
            // inert, so every later use of the field is unconditional.
            DisposeQuietly(watcher);
            _deviceWatcher = new NoOpDeviceWatcher();

            // Only a platform that actually has USB serial has something to lose here: a mobile
            // head has no serial transport, so a watcher that never runs is not a user-facing
            // degradation there and must not raise a notification the user cannot act on.
            if (DeviceWatcherFactory.PlatformSupportsSerialHotplug)
            {
                HotplugDetectionUnavailableMessage = HotplugUnavailableUserMessage;
            }

            AppLogger.Instance.Error(ex, "Failed to start the USB hotplug watcher: " + ex.Message);
        }
    }

    /// <summary>
    /// Disposes a half-built watcher during singleton construction. The catch is empty on purpose
    /// and for the same reason the surrounding one exists: this runs from a static field
    /// initializer, so a cleanup failure escaping here would become a fatal
    /// <see cref="TypeInitializationException"/> at first access of <see cref="Instance"/> — a far
    /// worse outcome than an undisposed watcher that was already failing.
    /// </summary>
    private static void DisposeQuietly(IDeviceWatcher? watcher)
    {
        if (watcher == null)
        {
            return;
        }

        try
        {
            watcher.Dispose();
        }
        catch
        {
            // Intentionally ignored — see the summary above.
        }
    }

    /// <summary>
    /// Test-only constructor: an isolated manager with its own <see cref="ConnectedDevices"/> list,
    /// an inert device watcher, channel release routed somewhere a test can observe, and its UI
    /// marshal run inline.
    /// </summary>
    /// <remarks>
    /// Three things about the singleton make it untestable, and this constructor replaces exactly
    /// those three. Its device watcher is a real one — on macOS and Linux a serial-port poller that
    /// starts a background timer inside a static field initializer; its teardown path calls
    /// <c>LoggingManager.Instance</c>, whose constructor needs a running Avalonia application; and
    /// its UI marshal queues onto a dispatcher nothing pumps outside the app. See
    /// <see cref="_unsubscribeChannel"/> and <see cref="_postToUiThread"/>. Nothing else differs:
    /// the teardown, the firmware-update carve-out, the subscription bookkeeping and the
    /// notification are all the production code.
    /// </remarks>
    internal ConnectionManager(
        IDeviceWatcher watcher,
        Func<IReadOnlyList<IChannel>> subscribedChannels,
        Action<IChannel> unsubscribeChannel,
        Action<Action> postToUiThread)
    {
        ArgumentNullException.ThrowIfNull(watcher);
        ArgumentNullException.ThrowIfNull(subscribedChannels);
        ArgumentNullException.ThrowIfNull(unsubscribeChannel);
        ArgumentNullException.ThrowIfNull(postToUiThread);

        ConnectedDevices = [];
        _deviceWatcher = watcher;
        _subscribedChannels = subscribedChannels;
        _unsubscribeChannel = unsubscribeChannel;
        _postToUiThread = postToUiThread;

        // The same state the singleton is in until the connection dialog installs one; Connect
        // null-checks it and rejects duplicates when it is unset. Assigned explicitly only so this
        // constructor does not add a CS8618 to the repo's warning count.
        DuplicateDeviceHandler = null!;
    }

    // @port: Daqifi.Desktop.ConnectionManager.Instance
    public static ConnectionManager Instance => instance;

    /// <summary>
    /// Releases one channel of a device being torn down, so it stops counting as active and stops
    /// feeding the logger. Resolves <see cref="LoggingManager"/> lazily — see
    /// <see cref="_unsubscribeChannel"/> for why that indirection exists.
    /// </summary>
    private void UnsubscribeChannel(IChannel channel)
    {
        if (_unsubscribeChannel != null)
        {
            _unsubscribeChannel(channel);
            return;
        }

        LoggingManager.Instance.Unsubscribe(channel);
    }

    /// <summary>
    /// Everything the logger is currently holding, as the immutable copy-on-write snapshot
    /// <see cref="LoggingManager.SubscribedChannels"/> publishes. See
    /// <see cref="_subscribedChannels"/> for why this is indirect.
    /// </summary>
    private IReadOnlyList<IChannel> SubscribedChannels() =>
        _subscribedChannels != null
            ? _subscribedChannels()
            : LoggingManager.Instance.SubscribedChannels;

    /// <summary>
    /// Marshals teardown onto the UI thread — see <see cref="_postToUiThread"/> for why this is
    /// indirect rather than a direct <see cref="PostToUiThread"/> call.
    /// </summary>
    private void MarshalToUiThread(Action action) => (_postToUiThread ?? PostToUiThread)(action);

    /// <summary>
    /// Wording shown to the user when USB hotplug-removal detection is not running. Says what the
    /// user will actually see happen, not which watcher failed.
    /// </summary>
    private const string HotplugUnavailableUserMessage =
        "Automatic USB disconnect detection is not available on this system. " +
        "If you unplug a connected device, the app will keep showing it as connected until you " +
        "disconnect it yourself.";

    /// <summary>
    /// Null when USB hotplug-removal detection is working, or when the platform has no serial
    /// hardware to detect (the mobile heads, which are WiFi/TCP only). Non-null when this platform
    /// DOES have USB serial but the watcher is not running — the user needs to know that unplugging
    /// a device will go unnoticed rather than being left to infer it (issue #90).
    /// </summary>
    public string? HotplugDetectionUnavailableMessage { get; }

    #endregion

    // @port: Daqifi.Desktop.ConnectionManager.Connect
    public async Task Connect(IStreamingDevice device)
    {
        try
        {
            // Never let a user-initiated USB connect (or a discovery-driven one) open the COM port
            // while a firmware update is running: the device being flashed re-enumerates its USB-CDC
            // port mid-update, and Core's own JumpingToApp step reconnects it directly (not through
            // this method). A competing open here would steal the port out from under that reconnect
            // and strand the update in a JumpingToApp timeout even though the flash succeeded — the
            // exact failure in issue #738. WiFi connects are unaffected (different device path).
            // Core's reconnect calls the Core device's Connect() directly, so this gate can't block it.
            if (IsFirmwareUpdateInProgress && device.ConnectionType == ConnectionType.Usb)
            {
                AppLogger.Instance.Warning(
                    $"Refusing to connect USB device {device.Name} while a firmware update is in progress " +
                    "(the device reconnects itself after the flash).");
                ConnectionStatus = DAQiFiConnectionStatus.Error;
                return;
            }

            ConnectionStatus = DAQiFiConnectionStatus.Connecting;

            // Check for duplicate device before connecting
            var duplicateResult = CheckForDuplicateDevice(device);
            if (duplicateResult.IsDuplicate)
            {
                if (DuplicateDeviceHandler != null)
                {
                    var action = await DuplicateDeviceHandler(duplicateResult);
                    switch (action)
                    {
                        case DuplicateDeviceAction.KeepExisting:
                            ConnectionStatus = DAQiFiConnectionStatus.AlreadyConnected;
                            return;
                        case DuplicateDeviceAction.Cancel:
                            ConnectionStatus = DAQiFiConnectionStatus.Disconnected;
                            return;
                        case DuplicateDeviceAction.SwitchToNew:
                            // Disconnect the existing device and continue with connection
                            Disconnect(duplicateResult.ExistingDevice);
                            break;
                    }
                }
                else
                {
                    // No handler set, default behavior is to reject the duplicate
                    ConnectionStatus = duplicateResult.ExistingDevice != null ? DAQiFiConnectionStatus.AlreadyConnected : DAQiFiConnectionStatus.Error;
                    return;
                }
            }
            
            var isConnected = await Task.Run(() => device.Connect());
            if (!isConnected)
            {
                ConnectionStatus = DAQiFiConnectionStatus.Error;
                return;
            }
            
            // Check again after connection (in case serial number wasn't available before connect)
            var postConnectDuplicateResult = CheckForDuplicateDevice(device);
            if (postConnectDuplicateResult.IsDuplicate)
            {
                // Disconnect the device we just connected since it's a duplicate
                device.Disconnect();
                ConnectionStatus = postConnectDuplicateResult.ExistingDevice != null ? DAQiFiConnectionStatus.AlreadyConnected : DAQiFiConnectionStatus.Error;
                return;
            }
            
            // A transport that dies between device.Connect() returning and the loss handler going
            // live below is UNOBSERVABLE: there is no subscriber yet, and even with one the handler
            // would find the device not yet in ConnectedDevices and return. Subscribing earlier
            // therefore does not close this window — re-reading the device's own state does. Without
            // it, accepting a wrapper whose transport is already gone puts exactly the stale entry
            // into ConnectedDevices that this class now exists to remove, and reports it as a
            // successful connect. Release the transport Connect() opened rather than leaking its
            // handle for the process lifetime.
            if (!device.IsConnected)
            {
                AppLogger.Instance.Warning(
                    $"Device {device.DeviceDisplayName} connected but its transport was already gone " +
                    "before it could be accepted; reporting the connect as failed.");
                device.Disconnect();
                ConnectionStatus = DAQiFiConnectionStatus.Error;
                return;
            }

            ConnectedDevices.Add(device);

            // Only now: these events bridge to the Core device, which does not exist until
            // device.Connect() above has created it, and the teardown handler must not fire for a
            // device that has not been accepted into ConnectedDevices yet.
            SubscribeDeviceEvents(device);

            await Task.Delay(1000);

            // The device can be torn down DURING that settle, and only since this PR: the loss
            // handler goes live at the SubscribeDeviceEvents call above, and it runs on the UI
            // thread while this continuation is suspended. If it did, the connect did not leave a
            // usable connection — publishing "Connected" here would put the shell back into a
            // connected state for a device that is gone, and SetDeviceContext below would tag every
            // later Sentry event with dead hardware. Treat it as an aborted connect.
            //
            // Error rather than Disconnected because that is the status every other failure in this
            // method reports, and it is what keeps the connection dialog open
            // (ConnectionDialogViewModel:534) — reconnecting is exactly what the user does next. The
            // accurate, device-naming message still comes from the teardown's own notification.
            if (!ConnectedDevices.Contains(device))
            {
                AppLogger.Instance.Warning(
                    $"Device {device.DeviceDisplayName} dropped while its connection was settling; " +
                    "reporting the connect as failed rather than connected.");
                ConnectionStatus = DAQiFiConnectionStatus.Error;
                return;
            }

            OnPropertyChanged("ConnectedDevices");
            ConnectionStatus = DAQiFiConnectionStatus.Connected;

            var connectionType = device.ConnectionType == ConnectionType.Usb ? "usb" : "wifi";
            AppLogger.Instance.SetDeviceContext(
                device.DevicePartNumber,
                device.DeviceSerialNo,
                device.DeviceVersion,
                connectionType,
                ActiveChannelCount(device));
            AppLogger.Instance.AddBreadcrumb("device", $"Device connected: {device.Name} (S/N: {device.DeviceSerialNo}) via {connectionType}");
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Error(ex, "Failed to Connect in Connection");
            ConnectionStatus = DAQiFiConnectionStatus.Error;
        }
    }

    // @port: Daqifi.Desktop.ConnectionManager.Disconnect
    public void Disconnect(IStreamingDevice device)
    {
        var connectionType = device.ConnectionType == ConnectionType.Usb ? "usb" : "wifi";
        try
        {
            // Before the device's own teardown, while the Core device these events bridge to is
            // still alive to detach from.
            UnsubscribeDeviceEvents(device);
            device.Disconnect();
            ConnectedDevices.Remove(device);
            OnPropertyChanged("ConnectedDevices");

            AppLogger.Instance.AddBreadcrumb("device", $"Device disconnected: {device.Name} (S/N: {device.DeviceSerialNo}) via {connectionType}");

            if (ConnectedDevices.Count == 0)
            {
                AppLogger.Instance.ClearDeviceContext();
            }
            else
            {
                var remaining = ConnectedDevices[^1];
                var remainingType = remaining.ConnectionType == ConnectionType.Usb ? "usb" : "wifi";
                AppLogger.Instance.SetDeviceContext(
                    remaining.DevicePartNumber,
                    remaining.DeviceSerialNo,
                    remaining.DeviceVersion,
                    remainingType,
                    ActiveChannelCount(remaining));
            }
        }
        catch (Exception ex)
        {
            AppLogger.Instance.AddBreadcrumb("device", $"Device disconnect failed: {device.Name} (S/N: {device.DeviceSerialNo}) via {connectionType}", Common.Loggers.BreadcrumbLevel.Error);
            AppLogger.Instance.Error(ex, "Failed in Disconnect");
        }
    }

    // Downstream-only (mobile support): the mobile shell connects a device
    // directly over WiFi/TCP (DaqifiStreamingDevice.Connect) rather than through
    // Connect() above — which also drives serial duplicate-detection and a 1 s
    // settle that the mobile flow doesn't want. These let the mobile shell publish
    // the already-connected device into the shared ConnectedDevices list so the
    // projected pane VMs that observe it (DeviceLogsViewModel and future mobile
    // panes) see it and are notified. No upstream counterpart — the WPF app always
    // routes through Connect().
    public void RegisterConnectedDevice(IStreamingDevice device)
    {
        if (device is null || ConnectedDevices.Contains(device)) { return; }
        ConnectedDevices.Add(device);
        OnPropertyChanged(nameof(ConnectedDevices));

        // Diagnostics only — the mobile shell owns its own drop teardown. See
        // SubscribeDeviceDiagnostics for why ConnectionLost is deliberately not wired here.
        SubscribeDeviceDiagnostics(device);

        // Same enrichment Connect() applies. This is the path MOBILE connects through, and
        // without it every Sentry event from Android arrived with no device model, serial or
        // firmware attached — the desktop's crash reports carry all three, so mobile reports
        // were strictly harder to act on for no reason other than which method was called.
        EnrichTelemetry(() =>
        {
            var connectionType = device.ConnectionType == ConnectionType.Usb ? "usb" : "wifi";
            AppLogger.Instance.SetDeviceContext(
                device.DevicePartNumber,
                device.DeviceSerialNo,
                device.DeviceVersion,
                connectionType,
                ActiveChannelCount(device));
            AppLogger.Instance.AddBreadcrumb(
                "device", $"Device connected: {device.Name} (S/N: {device.DeviceSerialNo}) via {connectionType}");
        });
    }

    /// <summary>
    /// Runs Sentry enrichment so nothing it throws can escape into the device flow. Telemetry is
    /// not load-bearing: an exception here unwinds into UsbDeviceConnector's catch, which tears
    /// the device down and reports a SUCCESSFUL connect as a failure (audit #ec1ca58).
    /// <para>
    /// The catch is silent on purpose. The likeliest failure is AppLogger.Instance itself failing
    /// to construct (issue #127) — reporting that through AppLogger would throw again, which is
    /// exactly the trap this guard exists to avoid.
    /// </para>
    /// </summary>
    private static void EnrichTelemetry(Action enrich)
    {
        try { enrich(); }
        catch { /* telemetry must never break a connect or a teardown */ }
    }

    /// <summary>
    /// The channel count reported to Sentry as <c>daqifi.active_channels</c>. Single definition
    /// on purpose: the tag is set from several places (connect, unregister, stream start), and
    /// if they disagreed the tag would silently mean different things depending on which fired
    /// last. Counts every active channel on the device, not just the analog ones a given screen
    /// happens to be streaming.
    /// </summary>
    internal static int ActiveChannelCount(IStreamingDevice device)
    {
        // Never let telemetry break teardown. DataChannels is a plain List<IChannel> that Core's
        // background events rebuild wholesale (Clear + AddRange in RefreshChannels), so counting
        // it from the UI thread can throw "collection was modified". That throw would land after
        // the device was removed but before the context was set, stranding precisely the stale
        // tags this call exists to clear — and it would escape into callers, only some of which
        // wrap the unregister in a best-effort catch. A wrong channel count on one event is not
        // worth any of that.
        // Catch broadly on purpose. "Collection was modified" is only the tidiest way this
        // fails: List<T> writes _items, _size and _version without a barrier, so a read racing
        // AddRange's Grow can index past the end (IndexOutOfRangeException), and one landing
        // inside Clear's Array.Clear can hand the predicate a null channel (NullReferenceException)
        // — on ARM, which is every Android install. Narrowing to InvalidOperationException would
        // let those escape RegisterConnectedDevice into UsbDeviceConnector's outer catch, which
        // tears the device down and reports a SUCCESSFUL connect as a failure (audit #ec1ca58).
        try
        {
            return device.DataChannels?.Count(c => c.IsActive) ?? 0;
        }
        catch (Exception)
        {
            return 0;
        }
    }

    public void UnregisterConnectedDevice(IStreamingDevice device)
    {
        if (device is null || !ConnectedDevices.Remove(device)) { return; }
        OnPropertyChanged(nameof(ConnectedDevices));

        // Mirror of RegisterConnectedDevice. Runs before the caller's own device.Disconnect(),
        // while the Core device these events bridge to is still alive to detach from.
        UnsubscribeDeviceDiagnostics(device);

        EnrichTelemetry(() =>
        {
            AppLogger.Instance.AddBreadcrumb("device", $"Device unregistered: {device.Name}");

            // Mirror Disconnect()'s teardown. Sentry scope tags are global, so leaving them set
            // would tag every later event with a device that is no longer connected — mobile
            // tears down through here rather than Disconnect(), so a crash after a drop would
            // have named the dead device's model and serial. Wrong context is worse than none.
            if (ConnectedDevices.Count == 0)
            {
                AppLogger.Instance.ClearDeviceContext();
            }
            else
            {
                var remaining = ConnectedDevices[^1];
                AppLogger.Instance.SetDeviceContext(
                    remaining.DevicePartNumber,
                    remaining.DeviceSerialNo,
                    remaining.DeviceVersion,
                    remaining.ConnectionType == ConnectionType.Usb ? "usb" : "wifi",
                    ActiveChannelCount(remaining));
            }
        });
    }

    // @port: Daqifi.Desktop.ConnectionManager.Reboot
    public void Reboot(IStreamingDevice device)
    {
        try
        {
            UnsubscribeDeviceEvents(device);
            device.Reboot();
            ConnectedDevices.Remove(device);
            OnPropertyChanged("ConnectedDevices");
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Error(ex, "Failed in Reboot");
        }
    }

    // @port: Daqifi.Desktop.ConnectionManager.UpdateStatusString
    public void UpdateStatusString()
    {
        ConnectionStatusString = ConnectionStatus switch
        {
            DAQiFiConnectionStatus.Disconnected => "Disconnected",
            DAQiFiConnectionStatus.Connecting => "Connecting",
            DAQiFiConnectionStatus.Connected => "Connected",
            DAQiFiConnectionStatus.Error => "Error",
            DAQiFiConnectionStatus.AlreadyConnected => "AlreadyConnected",
            _ => "Error"
        };
    }

    #region Device Event Wiring
    /// <summary>
    /// Attaches every per-device event this class listens to. Kept as a single method with an exact
    /// mirror in <see cref="UnsubscribeDeviceEvents"/> so a newly wired event cannot be attached at
    /// connect and forgotten at teardown. Runs once the device has connected and been accepted into
    /// <see cref="ConnectedDevices"/>, which is also when the Core device behind these events exists.
    /// </summary>
    /// <remarks>
    /// Detach-then-attach rather than plain attach: <see cref="Connect"/> can be called twice on one
    /// device instance (a reconnect of a device the app never explicitly disconnected), and a second
    /// <c>+=</c> on the same handler would double every teardown and every log line. The detach is a
    /// no-op when nothing is attached.
    /// </remarks>
    // Internal rather than private so the teardown tests can put a device into the same wired
    // state Connect() leaves it in without paying Connect()'s one-second settle per case; one test
    // still goes through Connect() itself to pin that this is what it calls.
    // @port: Daqifi.Desktop.ConnectionManager.SubscribeDeviceEvents
    internal void SubscribeDeviceEvents(IStreamingDevice device)
    {
        UnsubscribeDeviceEvents(device);

        device.ConnectionLost += OnDeviceConnectionLost;
        device.ErrorOccurred += OnDeviceErrorOccurred;
        device.SendFailed += OnDeviceSendFailed;
    }

    /// <summary>
    /// Detaches everything <see cref="SubscribeDeviceEvents"/> attached. Called from both teardown
    /// paths (<see cref="Disconnect(IStreamingDevice)"/> and <see cref="Reboot"/>) before the
    /// device's own teardown runs, while the underlying Core device is still alive to detach from.
    /// </summary>
    // @port: Daqifi.Desktop.ConnectionManager.UnsubscribeDeviceEvents
    internal void UnsubscribeDeviceEvents(IStreamingDevice device)
    {
        device.ConnectionLost -= OnDeviceConnectionLost;
        device.ErrorOccurred -= OnDeviceErrorOccurred;
        device.SendFailed -= OnDeviceSendFailed;
    }

    /// <summary>
    /// The diagnostics half of <see cref="SubscribeDeviceEvents"/>, for a device that reached
    /// <see cref="ConnectedDevices"/> through <see cref="RegisterConnectedDevice"/> — i.e. the
    /// mobile shell, which connects the device itself and owns its own teardown.
    /// </summary>
    /// <remarks>
    /// Deliberately excludes <see cref="IDevice.ConnectionLost"/>. Mobile already tears a dropped
    /// device down from its own <c>IsConnected</c> watcher
    /// (<c>MobileShellViewModel.HandleConnectionLost</c>), which does more than this class can — it
    /// also returns the shell to its device-list state. Subscribing the teardown handler here as
    /// well would mean two teardowns racing for one drop, for no gain. Gap B (the background
    /// failures being invisible) is not shell-specific, so those two events are wired on every
    /// platform.
    /// </remarks>
    private void SubscribeDeviceDiagnostics(IStreamingDevice device)
    {
        device.ErrorOccurred -= OnDeviceErrorOccurred;
        device.SendFailed -= OnDeviceSendFailed;

        device.ErrorOccurred += OnDeviceErrorOccurred;
        device.SendFailed += OnDeviceSendFailed;
    }

    /// <summary>Detaches what <see cref="SubscribeDeviceDiagnostics"/> attached.</summary>
    private void UnsubscribeDeviceDiagnostics(IStreamingDevice device)
    {
        device.ErrorOccurred -= OnDeviceErrorOccurred;
        device.SendFailed -= OnDeviceSendFailed;
    }

    /// <summary>
    /// Handles a device's <see cref="IDevice.ConnectionLost"/> event — Core detected a spontaneous
    /// transport drop (reboot, unplug, WiFi/TCP timeout) that this class would otherwise never
    /// learn about. Unsubscribes the device's channels, tears the connection down via
    /// <see cref="Disconnect(IStreamingDevice)"/>, and surfaces a notification naming the device
    /// and the reason.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This runs <em>alongside</em> <see cref="_deviceWatcher"/>, not instead of it. The watcher is
    /// what gives this port working USB hotplug detection on macOS and Linux, and it stays. The two
    /// paths are redundant rather than conflicting: both converge on
    /// <see cref="Disconnect(IStreamingDevice)"/>, both skip a device under firmware update, and
    /// whichever arrives second finds the device already gone from <see cref="ConnectedDevices"/>
    /// and returns. What this adds is the transports the watcher cannot see — every WiFi/TCP
    /// device, which <see cref="CheckIfSerialDeviceWasRemoved"/> filters out by construction.
    /// </para>
    /// </remarks>
    // @port: Daqifi.Desktop.ConnectionManager.OnDeviceConnectionLost
    private void OnDeviceConnectionLost(object? sender, ConnectionLostEventArgs e)
    {
        if (sender is not IStreamingDevice device)
        {
            return;
        }

        // Core raises this from its transport/reader thread. ConnectedDevices is mutated on the UI
        // thread by Connect/Disconnect, and NotifyConnection's change notification runs
        // DaqifiViewModel.UpdateUi synchronously — so everything below has to be marshalled, for
        // the same reasons CheckIfSerialDeviceWasRemoved marshals its own removal.
        MarshalToUiThread(() =>
        {
            // The device being flashed drops its transport when it reboots mid-update — an expected
            // part of the flash that Core reconnects itself. Tearing it down here would dispose the
            // Core device out from under Core's JumpingToApp reconnect and time the update out
            // (issue #738). ReconcileDeviceAfterUpdate handles a genuinely-failed reconnect.
            if (IsDeviceBeingUpdated(device))
            {
                return;
            }

            // Already torn down via another path — an explicit user disconnect, or the device
            // watcher's serial-removal sweep, racing this event.
            if (!ConnectedDevices.Contains(device))
            {
                return;
            }

            TearDownDroppedDevice(device, $"{device.DeviceDisplayName} disconnected ({e.Reason}).");
        });
    }

    /// <summary>
    /// The teardown both spontaneous-drop paths share: release the device's channels, disconnect
    /// and remove it, then raise the user-visible notification with a reason that names it.
    /// </summary>
    /// <remarks>
    /// Channels are released BEFORE <see cref="Disconnect(IStreamingDevice)"/> because
    /// <c>AbstractStreamingDevice.Disconnect</c> clears <c>DataChannels</c> — after it there is
    /// nothing left to enumerate, and the channels would stay in <c>LoggingManager</c> marked
    /// active for the process lifetime, still counting toward <c>CanToggleLogging</c> and still
    /// listed as live inputs. The list is snapshotted for the same reason
    /// <see cref="ActiveChannelCount"/> guards itself: Core's background events rebuild
    /// <c>DataChannels</c> wholesale.
    /// </remarks>
    /// <param name="device">The device whose connection went away.</param>
    /// <param name="reason">User-facing sentence naming the device and what happened.</param>
    private void TearDownDroppedDevice(IStreamingDevice device, string reason)
    {
        foreach (var channel in ChannelsToRelease(device))
        {
            UnsubscribeChannel(channel);
        }

        Disconnect(device);

        LastDisconnectReason = reason;
        NotifyConnection = true;
    }

    /// <summary>
    /// The channels teardown has to release: the entries the logger is actually still holding for
    /// <paramref name="device"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Asks the LOGGER what it is holding rather than asking the device what it owns, because only
    /// the first question can be answered atomically. <c>DataChannels</c> is a plain <c>List</c>
    /// that Core's background events rebuild wholesale (<c>Clear</c> then <c>AddRange</c>), so a
    /// copy of it can legitimately come back short — or empty — without throwing anything, and
    /// every channel missed that way stays in the logger marked active for the process lifetime,
    /// still counting toward <c>CanToggleLogging</c>. That is the leak this whole class now exists
    /// to close, reintroduced through a race. <c>SubscribedChannels</c> has no such window: it is
    /// published copy-on-write, so a reader always gets a complete, immutable list.
    /// </para>
    /// <para>
    /// Matching is by serial number, ordinally — serials are opaque identifiers, and it is the same
    /// discriminator <c>LoggingManager.Unsubscribe</c> resolves by. A device with no serial number
    /// cannot be matched that way (a blank serial would sweep up every other unidentified device's
    /// channels), so that case alone falls back to the device's own list, best-effort and guarded:
    /// this runs inside an action posted to the dispatcher, and an escaping exception would take the
    /// whole teardown with it and leave the device connected, with nothing to catch it.
    /// </para>
    /// </remarks>
    private List<IChannel> ChannelsToRelease(IStreamingDevice device)
    {
        try
        {
            var serialNumber = device.DeviceSerialNo;
            if (!string.IsNullOrWhiteSpace(serialNumber))
            {
                return SubscribedChannels()
                    .Where(c => string.Equals(c.DeviceSerialNo, serialNumber, StringComparison.Ordinal))
                    .ToList();
            }

            return device.DataChannels?.ToList() ?? [];
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Warning(
                ex,
                $"Could not determine which channels belong to {device.DeviceDisplayName} while " +
                "tearing it down after a dropped connection; disconnecting it anyway.");
            return [];
        }
    }

    /// <summary>
    /// Reports a failure Core caught on one of a device's background threads. Without it a read
    /// loop that could not read and a decoder that could not decode both present to the user as a
    /// device that has simply stopped sending.
    /// </summary>
    /// <remarks>
    /// Observability only: Core does not tear the connection down for these, and neither does this
    /// handler. A genuinely dead link arrives separately as <see cref="IDevice.ConnectionLost"/>,
    /// which is where teardown and the user-facing notification live. No dispatcher hop either —
    /// nothing here touches bound state, and Core raises from a background thread.
    /// </remarks>
    // @port: Daqifi.Desktop.ConnectionManager.OnDeviceErrorOccurred
    private void OnDeviceErrorOccurred(object? sender, CoreDeviceErrorEventArgs e)
    {
        // Core already collapses repeats per (source, exception type) and reports how many it
        // swallowed, so this reports the count instead of adding a second throttle on top.
        var suppressed = e.SuppressedCount > 0
            ? $"; {e.SuppressedCount} further like failure(s) suppressed by Core's throttle"
            : string.Empty;
        var message =
            $"Device {DescribeDevice(sender)} reported a background failure from {e.Source} " +
            $"({e.Error.GetType().Name}: {e.Error.Message}){suppressed}.";

        if (IsAppBug(e.Source))
        {
            AppLogger.Instance.Error(e.Error, message);
            return;
        }

        AppLogger.Instance.Warning(e.Error, message);
    }

    /// <summary>
    /// Decides whether a background device failure is an app bug (log at Error, which captures to
    /// Sentry) or an environmental condition (log at Warning, which does not).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Routing environmental conditions to Error has burned the upstream app three times: the noise
    /// buries real bugs and the volume tracks how often users unplug things. So the sources that
    /// describe the link are all Warnings:
    /// </para>
    /// <list type="bullet">
    /// <item><description>
    /// <c>MessageConsumer</c> — a failed transport read, parse, or subscriber dispatch. The
    /// dominant cause by far is a link that is dying or gone, which Core independently escalates to
    /// <c>ConnectionStatus.Lost</c>; every unplug would otherwise file a Sentry event. Core does not
    /// separate the subscriber-dispatch subcase (which would be an app bug), so that one is
    /// knowingly under-reported here rather than paying for it with a flood — it is still written to
    /// the app log with its stack trace.
    /// </description></item>
    /// <item><description>
    /// <c>StreamDecode</c> — one malformed streaming frame. Core drops the frame and the stream
    /// survives, so this is firmware or link noise, not an app fault.
    /// </description></item>
    /// <item><description>
    /// <c>Reconnect</c> — Core exhausted its reconnect attempts. Terminal, but the cause is a device
    /// that is unplugged, powered off, or off the network, and the user already gets the
    /// <see cref="IDevice.ConnectionLost"/> teardown and its notification.
    /// </description></item>
    /// </list>
    /// <para>
    /// <c>StatusNotification</c> is an app bug and is the one place this table diverges from
    /// upstream's. Upstream enumerates the Core 1.4.0 set, where that member did not exist, and its
    /// default arm silently routes it to Warning. Core 1.7.0 raises it for exactly one thing: a
    /// <c>StatusChanged</c> subscriber that threw while being notified of a connection transition.
    /// Every subscriber to that event is this app's own code, and the usual way one throws is a
    /// cross-thread mutation of bound state from Core's transport thread — a real defect in this
    /// repo's code, on the drop path, which is precisely where it is hardest to notice and most
    /// expensive to miss.
    /// </para>
    /// <para>
    /// <c>Unknown</c> is an app bug for the mirror-image reason: no Core path raises it, so seeing
    /// one means Core hit a failure it could not classify — expected volume zero, and worth a look.
    /// A source value this build does not recognise is a different thing (the app is behind Core,
    /// not the device misbehaving) and stays a Warning.
    /// </para>
    /// </remarks>
    // @port: Daqifi.Desktop.ConnectionManager.IsAppBug
    internal static bool IsAppBug(DeviceErrorSource source) => source switch
    {
        DeviceErrorSource.Unknown => true,
        DeviceErrorSource.StatusNotification => true,
        DeviceErrorSource.MessageConsumer => false,
        DeviceErrorSource.StreamDecode => false,
        DeviceErrorSource.Reconnect => false,
        _ => false
    };

    /// <summary>
    /// Reports a command that never reached the device. Sending is fire-and-forget, so without this
    /// a failed write is indistinguishable from a delivered one and the app's idea of device state
    /// can silently diverge from the device's.
    /// </summary>
    /// <remarks>
    /// Always a Warning: a write fails because the port closed, the device went away, or the device
    /// stopped draining its receive buffer (<c>IsTimeout</c>) — all conditions of the link, not app
    /// bugs. The distinction is still logged because "busy device" and "gone device" are diagnosed
    /// differently.
    /// </remarks>
    // @port: Daqifi.Desktop.ConnectionManager.OnDeviceSendFailed
    private void OnDeviceSendFailed(object? sender, CoreSendFailedEventArgs e)
    {
        var outcome = e.IsTimeout
            ? "timed out on the way to"
            : "failed to reach";
        AppLogger.Instance.Warning(
            e.Error,
            $"Command '{DescribeCommand(e.Message?.Data)}' {outcome} device {DescribeDevice(sender)} " +
            $"and was not delivered ({e.Error.GetType().Name}: {e.Error.Message}).");
    }

    /// <summary>
    /// Names the device a background failure came from, the way the user sees it in the UI.
    /// </summary>
    // @port: Daqifi.Desktop.ConnectionManager.DescribeDevice
    private static string DescribeDevice(object? sender) =>
        sender is IStreamingDevice device ? device.DeviceDisplayName : "(unknown)";

    /// <summary>
    /// Reduces a SCPI command to its verb — everything before the first space — for logging.
    /// </summary>
    /// <remarks>
    /// Arguments are dropped deliberately: <c>SYSTem:COMMunicate:LAN:PASs "..."</c> carries the
    /// user's WiFi password in plaintext, and the app log must never contain it. The verb alone
    /// answers the question a send failure raises — which command was lost.
    /// </remarks>
    // @port: Daqifi.Desktop.ConnectionManager.DescribeCommand
    internal static string DescribeCommand(string? data)
    {
        if (string.IsNullOrWhiteSpace(data))
        {
            return "(empty)";
        }

        var trimmed = data.Trim();
        var firstSpace = trimmed.IndexOf(' ');
        var verb = firstSpace < 0 ? trimmed : trimmed[..firstSpace];

        // A malformed or oversized payload must not turn one failure into a wall of log.
        return verb.Length <= MAX_LOGGED_COMMAND_LENGTH ? verb : verb[..MAX_LOGGED_COMMAND_LENGTH] + "...";
    }
    #endregion

    /// <summary>
    /// True when <paramref name="device"/> is the device currently undergoing a firmware update. During
    /// an update the device's serial transport drops and re-enumerates as an expected part of the flash,
    /// and Core owns the reconnect — so the desktop's disconnect-detection paths must leave that device's
    /// connection untouched rather than disposing the Core device Core is reconnecting (issue #738).
    /// </summary>
    /// <remarks>
    /// The firmware flow always drives the exact connected instance, so reference equality is the primary
    /// (and normally sufficient) match. The fallback compares the serial number — a stable hardware
    /// identity — never the display <c>Name</c>, which is a mutable, non-unique user label and could make
    /// an unrelated same-named device's disconnect be wrongly skipped, leaving a zombie connection.
    /// </remarks>
    // @port: Daqifi.Desktop.ConnectionManager.IsDeviceBeingUpdated
    private bool IsDeviceBeingUpdated(IStreamingDevice device)
    {
        var updating = DeviceBeingUpdated;
        if (updating == null)
        {
            return false;
        }

        if (ReferenceEquals(updating, device))
        {
            return true;
        }

        return !string.IsNullOrWhiteSpace(updating.DeviceSerialNo)
            && string.Equals(updating.DeviceSerialNo, device.DeviceSerialNo, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Marshals a UI-state change onto the UI thread from a watcher callback, without letting a
    /// dispatcher that is shutting down escape back into the caller.
    /// </summary>
    /// <remarks>
    /// <see cref="Dispatcher.Post"/> can throw once the dispatcher is going away, and this runs on
    /// the watcher's own thread. On Windows that thread belongs to WMI, which invokes subscribers
    /// with no protective catch, so an escaping exception would abort the removal before the worker
    /// that performs it is even created. Same reasoning, and the same shape, as
    /// <c>BootloaderWatcher</c>'s UI marshal: if the dispatcher is gone the update is simply
    /// dropped, which is the right outcome at shutdown.
    /// </remarks>
    private static void PostToUiThread(Action action)
    {
        if (Dispatcher.UIThread.CheckAccess())
        {
            action();
            return;
        }

        try
        {
            Dispatcher.UIThread.Post(action);
        }
        catch (Exception)
        {
            // Dispatcher unavailable / shutting down — drop the UI update.
        }
    }

    // @port: Daqifi.Desktop.ConnectionManager.CheckIfSerialDeviceWasRemoved
    private void CheckIfSerialDeviceWasRemoved()
    {
        // Every backend raises the removal event from a thread-pool thread — WMI's EventArrived and
        // the poller's timer callback alike — so nothing here may touch UI-bound state directly.
        // NotifyConnection's change notification runs DaqifiViewModel.UpdateUi synchronously, and
        // that mutates the notification collection the UI is bound to; done off-thread it can throw
        // straight back into the watcher, which would swallow the removal before the worker below is
        // even started. Post rather than Invoke: the reset and the notification raised at the end of
        // this method then run in the order they were queued, and a host with no dispatcher pumping
        // (a headless harness) cannot block the watcher thread. PostToUiThread also keeps a
        // shutting-down dispatcher from throwing back into the watcher.
        PostToUiThread(() => NotifyConnection = false);

        var bw = new BackgroundWorker();
        bw.DoWork += delegate
        {
            HashSet<string> availableSerialPorts;
            try
            {
                availableSerialPorts = new HashSet<string>(
                    SerialPort.GetPortNames(),
                    StringComparer.OrdinalIgnoreCase);
            }
            catch (Exception ex)
            {
                AppLogger.Instance.Error(ex, "Failed to enumerate serial ports after device change.");
                return;
            }

            // ConnectedDevices is a plain List mutated on the UI thread by Connect/Disconnect, so
            // snapshot it there rather than enumerating it from this worker: a concurrent connect
            // would otherwise throw "collection was modified" into BackgroundWorker's swallowing
            // catch and lose the removal entirely. Port enumeration above stays off-thread, which is
            // the part that is actually slow.
            var connectedSerialDevices = Dispatcher.UIThread.Invoke(
                () => ConnectedDevices.OfType<SerialStreamingDevice>().ToList());

            var devicesToRemove = connectedSerialDevices
                .Where(device =>
                    string.IsNullOrWhiteSpace(device.Port?.PortName) ||
                    !availableSerialPorts.Contains(device.Port.PortName))
                .Cast<IStreamingDevice>()
                .ToList();

            foreach (var serialDevice in devicesToRemove)
            {
                Dispatcher.UIThread.Invoke(delegate
                {
                    // The device being flashed drops off the COM port when it reboots mid-update — an
                    // expected part of the flash that Core reconnects itself. Tearing it down here would
                    // dispose the Core device out from under Core's JumpingToApp reconnect and time the
                    // update out (issue #738), so skip it entirely. The reconcile after the update ends
                    // (see ReconcileDeviceAfterUpdate) handles a genuinely-failed reconnect.
                    if (IsDeviceBeingUpdated(serialDevice))
                    {
                        return;
                    }

                    // Core's own port-presence poll reports the same unplug as ConnectionLost,
                    // usually within three to four seconds, so this and OnDeviceConnectionLost race
                    // for one removal. Whichever loses finds the device already gone from
                    // ConnectedDevices and returns; add the same guard here so the losing side is
                    // this one too, not a second Disconnect on a device already torn down.
                    if (!ConnectedDevices.Contains(serialDevice))
                    {
                        return;
                    }

                    // The firmware-update case is handled by the early-return above, so this is the
                    // ordinary spontaneous-disconnect teardown — the same one the ConnectionLost
                    // path runs, so the two cannot drift apart.
                    TearDownDroppedDevice(
                        serialDevice, $"{serialDevice.DeviceDisplayName} was unplugged.");
                });
            }
        };

        bw.RunWorkerAsync();
    }

    /// <summary>
    /// Checks if a device is already connected by comparing serial numbers.
    /// </summary>
    /// <param name="newDevice">The device to check for duplicates</param>
    /// <returns>A result indicating if the device is a duplicate and which existing device it matches</returns>
    // @port: Daqifi.Desktop.ConnectionManager.CheckForDuplicateDevice
    private DuplicateDeviceCheckResult CheckForDuplicateDevice(IStreamingDevice newDevice)
    {
        // Match on Core's transport-independent DeviceIdentity (issue #752): it compares the serial
        // number first and falls back to the MAC address when the serial is blank — the WiFi path knows
        // a device's MAC before its serial arrives with the first status message, a case the previous
        // serial-only comparison could not detect at all. A serial mismatch is decisive, so the weaker
        // MAC discriminator can never merge two genuinely different units.
        var candidateIdentity = DeviceIdentity.Create(newDevice.DeviceSerialNo, newDevice.MacAddress);

        // With no discriminator at all there is nothing to compare against, so duplicates are undetectable.
        if (candidateIdentity.IsEmpty)
        {
            AppLogger.Instance.Information(
                $"Device {newDevice.Name} has no serial number or MAC address - cannot check for duplicates");
            return new DuplicateDeviceCheckResult { IsDuplicate = false };
        }

        var existingDevice = ConnectedDevices.FirstOrDefault(d =>
            DeviceIdentity.Create(d.DeviceSerialNo, d.MacAddress).Matches(candidateIdentity));

        if (existingDevice != null)
        {
            var newDeviceInterface = newDevice.ConnectionType == ConnectionType.Usb ? "USB" : "WiFi";
            var existingDeviceInterface = existingDevice.ConnectionType == ConnectionType.Usb ? "USB" : "WiFi";
            
            AppLogger.Instance.Information(
                $"Duplicate device detected ({candidateIdentity}): Device already connected via " +
                $"{existingDeviceInterface}, attempted to add via {newDeviceInterface}");
            
            return new DuplicateDeviceCheckResult 
            { 
                IsDuplicate = true, 
                ExistingDevice = existingDevice,
                NewDevice = newDevice,
                NewDeviceInterface = newDeviceInterface,
                ExistingDeviceInterface = existingDeviceInterface
            };
        }

        return new DuplicateDeviceCheckResult { IsDuplicate = false };
    }
}

/// <summary>
/// Result of checking for duplicate devices
/// </summary>
// @port: Daqifi.Desktop.DuplicateDeviceCheckResult
public class DuplicateDeviceCheckResult
{
    // @port: Daqifi.Desktop.DuplicateDeviceCheckResult.IsDuplicate
    public bool IsDuplicate { get; set; }
    // @port: Daqifi.Desktop.DuplicateDeviceCheckResult.ExistingDevice
    public IStreamingDevice ExistingDevice { get; set; }
    // @port: Daqifi.Desktop.DuplicateDeviceCheckResult.NewDevice
    public IStreamingDevice NewDevice { get; set; }
    // @port: Daqifi.Desktop.DuplicateDeviceCheckResult.NewDeviceInterface
    public string NewDeviceInterface { get; set; }
    // @port: Daqifi.Desktop.DuplicateDeviceCheckResult.ExistingDeviceInterface
    public string ExistingDeviceInterface { get; set; }
}

/// <summary>
/// Actions that can be taken when a duplicate device is detected
/// </summary>
// @port: Daqifi.Desktop.DuplicateDeviceAction
public enum DuplicateDeviceAction
{
    KeepExisting,
    SwitchToNew,
    Cancel
}

// @port: Daqifi.Desktop.DAQiFiConnectionStatus
public enum DAQiFiConnectionStatus
{
    Disconnected,
    Connecting,
    Connected,
    Error,
    AlreadyConnected
}
