// Generated by portomatic scaffold from upstream Daqifi.Desktop/MainWindow.xaml.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.ViewModels;
using System;
using System.Reflection;
using Avalonia.Controls;

namespace Daqifi.Desktop;

/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
// @port: Daqifi.Desktop.MainWindow
public partial class MainWindow : Window
{
    private readonly AppLogger _appLogger = AppLogger.Instance;

    public MainWindow()
    {
        try
        {
            InitializeComponent();

            var version = Assembly.GetExecutingAssembly().GetName().Version;
            Title = $"DAQiFi v{version.Major}.{version.Minor}.{version.Build}";

            Closing += (sender, e) =>
            {
                if (DataContext is DaqifiViewModel viewModel)
                {
                    viewModel.Dispose();
                }
            };
        }
        catch (Exception ex)
        {
            _appLogger.Error(ex, "Error in MainWindow");
        }

        DataContext = new DaqifiViewModel();
    }
}
