// Generated by portomatic scaffold from upstream Daqifi.Desktop/MainWindow.xaml.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop;

/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
// @port: Daqifi.Desktop.MainWindow
public partial class MainWindow
{
    private AppLogger _appLogger;
}
