// Generated by portomatic scaffold from upstream Daqifi.Desktop/View/Prototype/LoggedDataPanePrototype.xaml.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Avalonia;
using Avalonia.Controls;
using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.Logger;
using Microsoft.EntityFrameworkCore;
using Avalonia.Controls;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Daqifi.Desktop.View.Prototype;

/// <summary>
/// Interaction logic for LoggedDataPanePrototype.xaml
/// </summary>
// @port: Daqifi.Desktop.View.Prototype.LoggedDataPanePrototype
public partial class LoggedDataPanePrototype : UserControl
{
    public LoggedDataPanePrototype()
    {
        InitializeComponent();
    }

    private AppLogger _logger;

    private IDbContextFactory<LoggingContext> _loggingContext;

    private CancellationTokenSource? _renameSessionCts;

    // @port: Daqifi.Desktop.View.Prototype.LoggedDataPanePrototype.OnConfirmOverlayIsVisibleChanged
    private void OnConfirmOverlayIsVisibleChanged(object sender, AvaloniaPropertyChangedEventArgs e) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.View.Prototype.LoggedDataPanePrototype.OnSessionNameChanged
    private void OnSessionNameChanged(object sender, TextChangedEventArgs e) => throw new NotImplementedException();
}
