// Generated by portomatic scaffold from upstream Daqifi.Desktop/View/Prototype/LoggedDataPanePrototype.xaml.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Avalonia;
using Avalonia.Controls;
using Avalonia.Threading;
using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.Logger;
using Daqifi.Desktop.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Daqifi.Desktop.View.Prototype;

/// <summary>
/// Interaction logic for LoggedDataPanePrototype.xaml
/// </summary>
// @port: Daqifi.Desktop.View.Prototype.LoggedDataPanePrototype
public partial class LoggedDataPanePrototype : UserControl
{
    private readonly AppLogger _logger = AppLogger.Instance;
    private readonly IDbContextFactory<LoggingContext> _loggingContext;
    private CancellationTokenSource? _renameSessionCts;

    public LoggedDataPanePrototype()
    {
        InitializeComponent();

        // WPF-only UIA hack dropped: upstream disabled VirtualizingStackPanel virtualization on
        // SessionList under the UI-test harness so off-screen rows appeared in the UIA tree.
        // Avalonia's headless automation drives the ItemsControl directly, so no analog is needed;
        // production virtualization behavior is unchanged.

        _loggingContext = App.ServiceProvider.GetRequiredService<IDbContextFactory<LoggingContext>>();
        Unloaded += (_, _) =>
        {
            _renameSessionCts?.Cancel();
            _renameSessionCts?.Dispose();
            _renameSessionCts = null;
        };
    }

    /// <summary>
    /// Moves keyboard focus to the Cancel button when the confirm overlay becomes visible,
    /// so Enter/Space activates the safe option by default. The TabNavigation="Cycle" on
    /// the overlay grid then traps subsequent Tab navigation inside the dialog.
    /// </summary>
    // @port: Daqifi.Desktop.View.Prototype.LoggedDataPanePrototype.OnConfirmOverlayIsVisibleChanged
    private void OnConfirmOverlayIsVisibleChanged(object? sender, AvaloniaPropertyChangedEventArgs e)
    {
        if (e.NewValue is true)
        {
            // Defer until the visual tree has finished switching states; calling Focus
            // directly inside the change handler can race the visibility transition.
            // FindControl: null-tolerant until the pane's axaml port names the button.
            Dispatcher.UIThread.Post(
                () => this.FindControl<Button>("ConfirmCancelButton")?.Focus(),
                DispatcherPriority.Input);
        }
    }

    // @port: Daqifi.Desktop.View.Prototype.LoggedDataPanePrototype.OnSessionNameChanged
    private async void OnSessionNameChanged(object? sender, TextChangedEventArgs e)
    {
        if ((DataContext as DaqifiViewModel)?.SelectedLoggingSession is not LoggingSession session ||
            sender is not TextBox textBox)
        {
            return;
        }

        // Treat blank input as "reset to default" so the DB and the Name getter
        // (which renders whitespace as "Session {ID}") stay consistent on reload.
        var trimmed = textBox.Text?.Trim();
        var newName = string.IsNullOrEmpty(trimmed) ? null : trimmed;
        session.Name = newName;

        _renameSessionCts?.Cancel();
        _renameSessionCts?.Dispose();

        var renameCts = new CancellationTokenSource();
        _renameSessionCts = renameCts;

        try
        {
            await Task.Delay(TimeSpan.FromMilliseconds(250), renameCts.Token);

            await using var context = await _loggingContext.CreateDbContextAsync(renameCts.Token);
            var sessionToUpdate = await context.Sessions.FindAsync([session.ID], renameCts.Token);
            if (sessionToUpdate != null)
            {
                sessionToUpdate.Name = newName;
                await context.SaveChangesAsync(renameCts.Token);
            }
        }
        catch (OperationCanceledException)
        {
        }
        catch (Exception ex)
        {
            _logger.Error(ex, $"Failed to update logging session name for session {session.ID}.");
        }
        finally
        {
            if (ReferenceEquals(_renameSessionCts, renameCts))
            {
                _renameSessionCts = null;
            }

            renameCts.Dispose();
        }
    }
}
