// Generated by portomatic scaffold from upstream Daqifi.Desktop/Channel/AbstractChannel.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.Device;
using NCalc;
using System.ComponentModel.DataAnnotations.Schema;
using Brush = Avalonia.Media.IBrush;
using CommunityToolkit.Mvvm.ComponentModel;
using ChannelDirection = Daqifi.Core.Channel.ChannelDirection;
using ChannelType = Daqifi.Core.Channel.ChannelType;

namespace Daqifi.Desktop.Channel;

// @port: Daqifi.Desktop.Channel.AbstractChannel
public abstract partial class AbstractChannel : ObservableObject, IChannel
{
    #region Private Data
    private string _scaledExpression;
    private DataSample _activeSample;
    private bool _suppressDigitalOutputCommand;
    protected IStreamingDevice _owner;
    #endregion

    #region Properties
    // @port: Daqifi.Desktop.Channel.AbstractChannel.ID
    public int ID { get; set; }

    /// <summary>
    /// Gets or sets the channel name. Implemented by derived classes to delegate to core.
    /// </summary>
    // @port: Daqifi.Desktop.Channel.AbstractChannel.Name
    public abstract string Name { get; set; }

    [ObservableProperty]
    private double _outputValue;

    /// <summary>
    /// Gets or sets the channel direction. Implemented by derived classes to delegate to core.
    /// </summary>
    // @port: Daqifi.Desktop.Channel.AbstractChannel.Direction
    public abstract ChannelDirection Direction { get; set; }

    [ObservableProperty]
    private Brush _channelColorBrush;

    [ObservableProperty]
    private bool _isOutput;

    [ObservableProperty]
    private bool _hasAdc;

    [ObservableProperty]
    private bool _isDigitalOn;

    /// <summary>
    /// Whether this channel's hardware supports PWM output. Only digital channels can be
    /// PWM-capable; <see cref="DigitalChannel"/> overrides with Core's board-mask answer.
    /// </summary>
    // @port: Daqifi.Desktop.Channel.AbstractChannel.IsPwmCapable
    public virtual bool IsPwmCapable => false;

    /// <summary>
    /// Whether PWM output is enabled. No-op on channel types without PWM support;
    /// <see cref="DigitalChannel"/> overrides to command the device through Core.
    /// </summary>
    // @port: Daqifi.Desktop.Channel.AbstractChannel.IsPwmEnabled
    public virtual bool IsPwmEnabled
    {
        get => false;
        set { }
    }

    /// <summary>
    /// The PWM duty cycle in whole percent. No-op on channel types without PWM support;
    /// <see cref="DigitalChannel"/> overrides with Core-backed bookkeeping.
    /// </summary>
    // @port: Daqifi.Desktop.Channel.AbstractChannel.PwmDutyCyclePercent
    public virtual int PwmDutyCyclePercent
    {
        get => 0;
        set { }
    }

    [ObservableProperty]
    private bool _isScalingActive;

    [ObservableProperty]
    private bool _hasValidExpression;

    /// <summary>
    /// Gets the channel index. Implemented by derived classes to delegate to core.
    /// </summary>
    // @port: Daqifi.Desktop.Channel.AbstractChannel.Index
    public abstract int Index { get; }

    // @port: Daqifi.Desktop.Channel.AbstractChannel.DeviceName
    public string DeviceName { get; set; }

    // @port: Daqifi.Desktop.Channel.AbstractChannel.DeviceSerialNo
    public string DeviceSerialNo { get; set; }

    // @port: Daqifi.Desktop.Channel.AbstractChannel.Type
    public abstract ChannelType Type { get; }

    [NotMapped]
    // @port: Daqifi.Desktop.Channel.AbstractChannel.IsBidirectional
    public bool IsBidirectional { get; set; }

    [NotMapped]
    // @port: Daqifi.Desktop.Channel.AbstractChannel.IsActive
    public abstract bool IsActive { get; set; }

    [NotMapped]
    // @port: Daqifi.Desktop.Channel.AbstractChannel.IsDigital
    public abstract bool IsDigital { get; }

    [NotMapped]
    // @port: Daqifi.Desktop.Channel.AbstractChannel.IsAnalog
    public abstract bool IsAnalog { get; }

    [NotMapped]
    // @port: Daqifi.Desktop.Channel.AbstractChannel.TypeString
    public string TypeString
    {
        get
        {
            var typeString = "";

            if (IsDigital) { typeString = "Digital "; }
            if (IsAnalog) {typeString = "Analog "; }

            typeString += Direction switch
            {
                ChannelDirection.Input => "Input",
                ChannelDirection.Output => "Output",
                _ => "Unknown"
            };

            return typeString;
        }
    }

    [NotMapped]
    // @port: Daqifi.Desktop.Channel.AbstractChannel.ScaleExpression
    public string ScaleExpression
    {
        get => _scaledExpression;
        set
        {
            _scaledExpression = value;

            if (string.IsNullOrWhiteSpace(_scaledExpression))
            {
                HasValidExpression = false;
                Expression = null;
                return;
            }

            Expression = new Expression(_scaledExpression)
            {
                Parameters = { ["x"] = 1 }
            };

            try
            {
                Expression.Evaluate();
                HasValidExpression = true;
            }
            catch (Exception)
            {
                HasValidExpression = false;
                Expression = null;
            }
            OnPropertyChanged();
        }
    }

    // @port: Daqifi.Desktop.Channel.AbstractChannel.Expression
    public Expression Expression { get; set; }

    [ObservableProperty]
    private bool _isVisible = true;

    // @port: Daqifi.Desktop.Channel.AbstractChannel.ActiveSample
    public DataSample ActiveSample
    {
        get => _activeSample;
        set
        {
            _activeSample = value;
            if (Expression != null && HasValidExpression && IsScalingActive && _activeSample != null)
            {
                try
                {
                    Expression.Parameters["x"] = _activeSample.Value;
                    var scaledValue = Convert.ToDouble(Expression.Evaluate());

                    if (double.IsFinite(scaledValue))
                    {
                        _activeSample.Value = scaledValue;
                    }
                    else
                    {
                        // A finite input can still yield a non-finite result WITHOUT throwing:
                        // a float divide-by-zero gives +/-Infinity and 0.0/0.0 gives NaN. Keep
                        // the raw value and disable scaling (mirroring the catch below) so
                        // Infinity/NaN never reaches the live plot or exported data.
                        AppLogger.Instance.Warning(
                            $"Expression produced a non-finite result for channel {Name}; scaling disabled.");
                        HasValidExpression = false;
                    }
                }
                catch (Exception ex)
                {
                    AppLogger.Instance.Warning($"Expression evaluation failed for channel {Name}: {ex.Message}");
                    HasValidExpression = false;
                }
            }

            if (_activeSample != null)
            {
                NotifyChannelUpdated(this, _activeSample);
            }
            OnPropertyChanged();
        }
    }
    #endregion

    // @port: Daqifi.Desktop.Channel.AbstractChannel.OnOutputValueChanged
    partial void OnOutputValueChanged(double value)
    {
        if (Direction == ChannelDirection.Output)
        {
            _owner?.SetChannelOutputValue(this, value);
        }
    }

    // @port: Daqifi.Desktop.Channel.AbstractChannel.OnIsOutputChanged
    partial void OnIsOutputChanged(bool value)
    {
        Direction = value ? ChannelDirection.Output : ChannelDirection.Input;
        OnPropertyChanged(nameof(TypeString));
    }

    // @port: Daqifi.Desktop.Channel.AbstractChannel.OnChannelColorBrushChanged
    partial void OnChannelColorBrushChanged(Brush value)
    {
        // Upstream froze the incoming WPF brush here; Avalonia has no Freezable —
        // ChannelColorManager hands out ImmutableSolidColorBrush instances instead.
    }

    // @port: Daqifi.Desktop.Channel.AbstractChannel.OnIsDigitalOnChanged
    partial void OnIsDigitalOnChanged(bool value)
    {
        if (_suppressDigitalOutputCommand)
        {
            return;
        }

        _owner?.SetChannelOutputValue(this, value ? 1 : 0);
    }

    /// <summary>
    /// Sets <see cref="IsDigitalOn"/> from already-known device/Core state — hydration,
    /// not a user action — so the change notifies the UI without re-issuing the output
    /// command that a user-driven change sends.
    /// </summary>
    // @port: Daqifi.Desktop.Channel.AbstractChannel.HydrateIsDigitalOn
    protected void HydrateIsDigitalOn(bool value)
    {
        _suppressDigitalOutputCommand = true;
        try
        {
            IsDigitalOn = value;
        }
        finally
        {
            _suppressDigitalOutputCommand = false;
        }
    }

    #region Events/Handlers
    public event OnChannelUpdatedHandler OnChannelUpdated;

    // @port: Daqifi.Desktop.Channel.AbstractChannel.NotifyChannelUpdated
    public void NotifyChannelUpdated(object sender, DataSample e)
    {
        OnChannelUpdated?.Invoke(sender, e);
    }
    #endregion

    #region Object overrides
    // @port: Daqifi.Desktop.Channel.AbstractChannel.Equals
    public override bool Equals(object obj)
    {
        if (obj is not AbstractChannel channel) { return false; }

        return channel.Name == Name;
    }

    // @port: Daqifi.Desktop.Channel.AbstractChannel.GetHashCode
    public override int GetHashCode()
    {
        return Name?.GetHashCode() ?? 0;
    }
    #endregion

    #region IColorable overrides
    // @port: Daqifi.Desktop.Channel.AbstractChannel.SetColor
    public void SetColor(Brush color)
    {
        ChannelColorBrush = color;
    }
    #endregion
}
