// Generated by portomatic scaffold from upstream Daqifi.Desktop/Channel/Channel.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.Channel;

// @port: Daqifi.Desktop.Channel.Channel
public class Channel : IChannel
{
    // @port: Daqifi.Desktop.Channel.Channel.ID
    public int ID
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.Name
    public string Name
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.Index
    public int Index
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.OutputValue
    public double OutputValue
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.Type
    public ChannelType Type
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.Direction
    public ChannelDirection Direction
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.TypeString
    public string TypeString
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.ScaleExpression
    public string ScaleExpression
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.ChannelColorBrush
    public System.Windows.Media.Brush ChannelColorBrush
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsBidirectional
    public bool IsBidirectional
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsOutput
    public bool IsOutput
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.HasAdc
    public bool HasAdc
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsActive
    public bool IsActive
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsDigital
    public bool IsDigital
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsAnalog
    public bool IsAnalog
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsDigitalOn
    public bool IsDigitalOn
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsPwmCapable
    public bool IsPwmCapable
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsPwmEnabled
    public bool IsPwmEnabled
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.PwmDutyCyclePercent
    public int PwmDutyCyclePercent
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsScalingActive
    public bool IsScalingActive
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.HasValidExpression
    public bool HasValidExpression
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.ActiveSample
    public DataSample ActiveSample
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.IsVisible
    public bool IsVisible
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.DeviceName
    public string DeviceName
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.DeviceSerialNo
    public string DeviceSerialNo
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.Channel.NotifyChannelUpdated
    public void NotifyChannelUpdated(object sender, DataSample e) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Channel.Channel.SetColor
    public void SetColor(System.Windows.Media.Brush color) => throw new NotImplementedException();
}
