// Generated by portomatic scaffold from upstream Daqifi.Desktop/Channel/DataSample.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.Channel;

// @port: Daqifi.Desktop.Channel.DataSample
public class DataSample
{
    // @port: Daqifi.Desktop.Channel.DataSample.ID
    public int ID
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.LoggingSessionID
    public int LoggingSessionID
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.Value
    public double Value
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.TimestampTicks
    public long TimestampTicks
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.DeviceName
    public string DeviceName
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.ChannelName
    public string ChannelName
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.DeviceSerialNo
    public string DeviceSerialNo
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.Color
    public string Color
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.Type
    public ChannelType Type
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.FirmwareDeltaMs
    public double? FirmwareDeltaMs
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.LoggingSession
    public LoggingSession LoggingSession
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Channel.DataSample.ToString
    public string ToString() => throw new NotImplementedException();
}
