// Generated by portomatic scaffold from upstream Daqifi.Desktop/Channel/DataSample.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using Avalonia.Media;
using ChannelType = Daqifi.Core.Channel.ChannelType;
using Daqifi.Desktop.Device;
using Daqifi.Desktop.Logger;

namespace Daqifi.Desktop.Channel;

// @port: Daqifi.Desktop.Channel.DataSample
public class DataSample : Daqifi.Core.Channel.IDataSample
{
    #region Properties
    // @port: Daqifi.Desktop.Channel.DataSample.ID
    public int ID { get; init; }

    // @port: Daqifi.Desktop.Channel.DataSample.LoggingSessionID
    public int LoggingSessionID { get; set; }

    // @port: Daqifi.Desktop.Channel.DataSample.Value
    public double Value { get; set; }

    // @port: Daqifi.Desktop.Channel.DataSample.TimestampTicks
    public long TimestampTicks { get; init; }

    // @port: Daqifi.Desktop.Channel.DataSample.DeviceName
    public string DeviceName { get; init; }

    // @port: Daqifi.Desktop.Channel.DataSample.ChannelName
    public string ChannelName { get; init; }

    // @port: Daqifi.Desktop.Channel.DataSample.DeviceSerialNo
    public string DeviceSerialNo { get; init; }

    // @port: Daqifi.Desktop.Channel.DataSample.Color
    public string Color { get; init; }

    // @port: Daqifi.Desktop.Channel.DataSample.Type
    public ChannelType Type { get; init; }

    /// <summary>
    /// Firmware-derived time since the previous message, in milliseconds.
    /// Computed from the hardware timer (<c>msg_time_stamp</c>) via <c>TimestampProcessor</c>,
    /// so it is immune to TCP jitter and reflects actual sample timing.
    /// Null when firmware delta is not available (e.g. SD card imports).
    /// </summary>
    [NotMapped]
    // @port: Daqifi.Desktop.Channel.DataSample.FirmwareDeltaMs
    public double? FirmwareDeltaMs { get; init; }

    [Required]
    // @port: Daqifi.Desktop.Channel.DataSample.LoggingSession
    public LoggingSession LoggingSession { get; set; }

    /// <summary>
    /// The Core channel this sample was decoded onto, or <see langword="null"/> for samples that
    /// did not come from a live stream (an SD card import, or a row rehydrated from the database).
    /// </summary>
    /// <remarks>
    /// Carried so a consumer can hand the sample to a Core aggregator that keys channels the way
    /// Core does — by <c>(type, channel number)</c> — rather than by the display name.
    /// <para>
    /// Deliberately <c>internal</c> and <c>[NotMapped]</c>: this type is an EF entity, and a public
    /// property here would join the mapped model and demand a migration for something that is
    /// in-memory plumbing.
    /// </para>
    /// </remarks>
    [NotMapped]
    internal Daqifi.Core.Channel.IChannel? CoreChannel { get; init; }
    #endregion

    #region Daqifi.Core.Channel.IDataSample
    // Explicit implementations throughout: an implicit one would add public properties to an EF
    // entity and pull them into the mapped model. `Value` is the exception — the entity already
    // declares it with a matching signature, so it satisfies the interface as it stands.

    /// <inheritdoc />
    DateTime Daqifi.Core.Channel.IDataSample.Timestamp => new(TimestampTicks);

    /// <summary>
    /// Always <see langword="null"/>: the raw ADC count is consumed by the decode path that
    /// produced <see cref="Value"/> and is not retained on this type.
    /// </summary>
    int? Daqifi.Core.Channel.IDataSample.RawValue => null;

    /// <summary>
    /// Always <see langword="null"/>: only the rollover-adjusted <see cref="TimestampTicks"/> is
    /// retained, not the device's verbatim counter.
    /// </summary>
    uint? Daqifi.Core.Channel.IDataSample.DeviceTimestamp => null;

    // Scaling is left at the interface default (null), which makes IDataSample.ScaledValue return
    // Value unchanged. That is the correct answer here: any scaling the user configured has ALREADY
    // been applied to Value by AbstractChannel.ActiveSample, so reporting a Core ChannelScaling as
    // well would claim a second, unapplied conversion.
    #endregion

    #region Constructors
    public DataSample() { }

    /// <summary>
    /// Initializes a new <see cref="DataSample"/> from a live streaming device message.
    /// </summary>
    /// <param name="streamingDevice">The device that produced the sample.</param>
    /// <param name="channel">The channel the sample belongs to.</param>
    /// <param name="timestamp">The calculated system timestamp for the sample.</param>
    /// <param name="value">The scaled sample value (volts for analog, 0/1 for digital).</param>
    /// <param name="firmwareDeltaMs">
    /// Firmware-measured time since the previous message, in milliseconds.
    /// Null for the first message in a session or when firmware timing is unavailable.
    /// </param>
    public DataSample(
        IDevice streamingDevice, IChannel channel, DateTime timestamp, double value, double? firmwareDeltaMs = null)
    {
        DeviceName = streamingDevice.Name;
        DeviceSerialNo=channel.DeviceSerialNo;
        ChannelName = channel.Name;
        Type = channel.Type;
        // WPF Brush.ToString(culture) yields "#AARRGGBB"; Avalonia IBrush has no culture
        // overload — read the color off the solid brush to keep the same persisted format.
        Color = channel.ChannelColorBrush is ISolidColorBrush solid
            ? solid.Color.ToString()
            : channel.ChannelColorBrush.ToString();
        Value = value;
        TimestampTicks = timestamp.Ticks;
        FirmwareDeltaMs = firmwareDeltaMs;
        CoreChannel = channel switch
        {
            AnalogChannel analog => analog.CoreChannel,
            DigitalChannel digital => digital.CoreChannel,
            _ => null
        };
    }
    #endregion

    #region Object overrides
    // @port: Daqifi.Desktop.Channel.DataSample.ToString
    public override string ToString()
    {
        return ID.ToString(CultureInfo.InvariantCulture);
    }
    #endregion
}
