// Generated by portomatic scaffold from upstream Daqifi.Desktop/DialogService/DialogService.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Microsoft.Extensions.DependencyInjection;

namespace Daqifi.Desktop.DialogService;

// @port: Daqifi.Desktop.DialogService.DialogService
public class DialogService : IDialogService
{
    private readonly HashSet<Control> _views = [];

    static DialogService()
    {
        // WPF's UIPropertyMetadata change callback → Avalonia class handler.
        IsRegisteredViewProperty.Changed.AddClassHandler<Control>(IsRegisteredViewPropertyChanged);
    }


    #region IDialogService Members

    /// <summary>
    /// Registers a View.
    /// </summary>
    /// <param name="view">The registered View.</param>
    // @port: Daqifi.Desktop.DialogService.DialogService.Register
    public void Register(Control view)
    {
        // Get owner window
        var owner = GetOwner(view);
        if (owner == null)
        {
            // Perform a late register when the View hasn't been loaded yet.
            // This will happen if e.g. the View is contained in a Frame.
            view.Loaded += LateRegister;
            return;
        }

        // Register for owner window closing, since we then should unregister View reference,
        // preventing memory leaks
        owner.Closed += OwnerClosed;

        _views.Add(view);
    }


    /// <summary>
    /// Unregisters a View.
    /// </summary>
    /// <param name="view">The unregistered View.</param>
    // @port: Daqifi.Desktop.DialogService.DialogService.Unregister
    public void Unregister(Control view)
    {
        _views.Remove(view);
    }


    /// <summary>
    /// Shows a dialog.
    /// </summary>
    /// <param name="ownerViewModel">
    /// A ViewModel that represents the owner window of the dialog.
    /// </param>
    /// <param name="viewModel">The ViewModel of the new dialog.</param>
    /// <typeparam name="T">The type of the dialog to show.</typeparam>
    /// <returns>
    /// A nullable value of type bool that signifies how a window was closed by the user.
    /// </returns>
    // @port: Daqifi.Desktop.DialogService.DialogService.ShowDialog<T>
    public Task<bool?> ShowDialogAsync<T>(object ownerViewModel, object viewModel) where T : Window
    {
        return ShowDialogAsync(ownerViewModel, viewModel, typeof(T));
    }
    #endregion


    #region Attached properties

    /// <summary>
    /// Attached property describing whether a Control is acting as a View in MVVM.
    /// </summary>
    public static readonly AttachedProperty<bool> IsRegisteredViewProperty =
        AvaloniaProperty.RegisterAttached<DialogService, Control, bool>("IsRegisteredView");


    /// <summary>
    /// Gets value describing whether Control is acting as View in MVVM.
    /// </summary>
    // @port: Daqifi.Desktop.DialogService.DialogService.GetIsRegisteredView
    public static bool GetIsRegisteredView(Control target)
    {
        return target.GetValue(IsRegisteredViewProperty);
    }


    /// <summary>
    /// Sets value describing whether Control is acting as View in MVVM.
    /// </summary>
    // @port: Daqifi.Desktop.DialogService.DialogService.SetIsRegisteredView
    public static void SetIsRegisteredView(Control target, bool value)
    {
        target.SetValue(IsRegisteredViewProperty, value);
    }


    /// <summary>
    /// Is responsible for handling IsRegisteredViewProperty changes, i.e. whether
    /// Control is acting as View in MVVM or not.
    /// </summary>
    private static void IsRegisteredViewPropertyChanged(Control target, AvaloniaPropertyChangedEventArgs e)
    {
        // The visual designer will run this code when setting the attached property, however at
        // that point the app container has not been built, so resolving the service would throw.
        if (Design.IsDesignMode) return;

        if (e.NewValue is bool newValue)
        {
            // The ONE app container (App.Initialize builds it before the first registered view is
            // constructed) — so this and every view model resolve the same singleton, which is what
            // makes the view registered here findable by FindOwnerWindow later.
            var dialogService = App.ServiceProvider.GetRequiredService<IDialogService>();
            if (newValue)
            {
                dialogService.Register(target);
            }
            else
            {
                dialogService.Unregister(target);
            }
        }
    }

    #endregion

    /// <summary>
    /// Shows a dialog. Avalonia dialogs are async and take the owner in
    /// ShowDialog (there is no Window.Owner setter).
    /// </summary>
    /// <param name="ownerViewModel">
    /// A ViewModel that represents the owner window of the dialog.
    /// </param>
    /// <param name="viewModel">The ViewModel of the new dialog.</param>
    /// <param name="dialogType">The type of the dialog.</param>
    /// <returns>
    /// A nullable value of type bool that signifies how a window was closed by the user.
    /// </returns>
    private async Task<bool?> ShowDialogAsync(object ownerViewModel, object viewModel, Type dialogType)
    {
        // Create dialog and set properties
        var dialog = (Window)Activator.CreateInstance(dialogType);
        dialog.DataContext = viewModel;
        dialog.WindowStartupLocation = WindowStartupLocation.CenterOwner;

        // Show dialog
        return await dialog.ShowDialog<bool?>(FindOwnerWindow(ownerViewModel));
    }

    /// <summary>
    /// Finds window corresponding to specified ViewModel.
    /// </summary>
    // @port: Daqifi.Desktop.DialogService.DialogService.FindOwnerWindow
    private Window FindOwnerWindow(object ownerViewModel)
    {
        var view = _views.SingleOrDefault(v => ReferenceEquals(v.DataContext, ownerViewModel));
        if (view == null)
        {
            throw new ArgumentException("Viewmodel is not referenced by any registered View.");
        }

        // Get owner window
        var owner = view as Window ?? TopLevel.GetTopLevel(view) as Window;

        // Make sure owner window was found
        if (owner == null)
        {
            throw new InvalidOperationException("View is not contained within a Window.");
        }

        return owner;
    }


    /// <summary>
    /// Callback for late View register. It wasn't possible to do a instant register since the
    /// View wasn't at that point part of the logical nor visual tree.
    /// </summary>
    private void LateRegister(object? sender, RoutedEventArgs e)
    {
        var view = sender as Control;
        if (view != null)
        {
            // Unregister loaded event
            view.Loaded -= LateRegister;

            // Register the view
            Register(view);
        }
    }


    /// <summary>
    /// Handles owner window closed, View service should then unregister all Views acting
    /// within the closed window.
    /// </summary>
    private void OwnerClosed(object? sender, EventArgs e)
    {
        var owner = sender as Window;
        if (owner != null)
        {
            // Find Views acting within closed window
            IEnumerable<Control> windowViews =
                from view in _views
                where TopLevel.GetTopLevel(view) == owner
                select view;

            // Unregister Views in window
            foreach (var view in windowViews.ToArray())
            {
                Unregister(view);
            }
        }
    }


    /// <summary>
    /// Gets the owning Window of a view.
    /// </summary>
    /// <param name="view">The view.</param>
    /// <returns>The owning Window if found; otherwise null.</returns>
    private Window GetOwner(Control view)
    {
        return view as Window ?? TopLevel.GetTopLevel(view) as Window;
    }

}
