// Generated by portomatic scaffold from upstream Daqifi.Desktop/DialogService/IDialogService.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.DialogService;

/// <summary>
/// Abstracts ViewModels from Views
/// </summary>
// @port: Daqifi.Desktop.DialogService.IDialogService
public interface IDialogService
{
    // @port: Daqifi.Desktop.DialogService.IDialogService.Views
    ReadOnlyCollection<FrameworkElement> Views { get; set; }

    // @port: Daqifi.Desktop.DialogService.IDialogService.Register
    void Register(FrameworkElement view);

    // @port: Daqifi.Desktop.DialogService.IDialogService.Unregister
    void Unregister(FrameworkElement view);

    // @port: Daqifi.Desktop.DialogService.IDialogService.ShowDialog
    bool? ShowDialog(object ownerViewModel, object viewModel);

    // @port: Daqifi.Desktop.DialogService.IDialogService.ShowDialog
    bool? ShowDialog(object ownerViewModel, object viewModel);

    // @port: Daqifi.Desktop.DialogService.IDialogService.ShowMessageBox
    MessageBoxResult ShowMessageBox(object ownerViewModel, string messageBoxText, string caption, MessageBoxButton button, MessageBoxImage icon);
}
