// Generated by portomatic scaffold from upstream Daqifi.Desktop/Loggers/DatabaseMigrator.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.IO;
using Daqifi.Desktop.Common.Loggers;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace Daqifi.Desktop.Logger;

/// <summary>
/// Handles database migration at application startup, including upgrade path
/// for existing databases created by <c>EnsureCreated()</c>.
/// </summary>
// @port: Daqifi.Desktop.Logger.DatabaseMigrator
public static class DatabaseMigrator
{
    #region Constants
    private const string INITIAL_MIGRATION_ID = "20250812090000_InitialSQLiteMigration";
    private const string EF_PRODUCT_VERSION = "10.0.7";

    // SQLite primary result codes that mean the FILE'S CONTENT is unusable as a database.
    // These two, and only these two, justify moving the file aside:
    //   SQLITE_CORRUPT (11) "database disk image is malformed" — a valid header, damaged pages.
    //   SQLITE_NOTADB  (26) "file is not a database" — the header itself is wrong or truncated.
    // Deliberately NOT included, because each describes the ENVIRONMENT rather than the file, and
    // quarantining on one would move a perfectly healthy database aside over a transient fault:
    //   SQLITE_BUSY (5) / SQLITE_LOCKED (6) — a second instance holds it.
    //   SQLITE_CANTOPEN (14) — permission denied, missing directory, or the path is a directory.
    //   SQLITE_READONLY (8) — the file or its directory is not writable.
    // Codes verified against Microsoft.Data.Sqlite 10.0.10 by damaging real database files: a
    // text file, a truncated header and a clobbered magic string all report 26; a database whose
    // pages past the header are overwritten reports 11; a directory in the file's place reports 14.
    // A ZERO-BYTE file reports nothing at all — SQLite treats it as a valid empty database, which
    // is why "the file exists but has no content" is not a corruption case and is not one here.
    private const int SQLITE_CORRUPT = 11;
    private const int SQLITE_NOTADB = 26;
    #endregion

    #region Public Properties
    /// <summary>
    /// Where an unreadable <c>DAQiFiDatabase.db</c> was moved to on this run, or <c>null</c> when
    /// the database opened normally (the overwhelmingly common case). Parked as static state so the
    /// UI can tell the user their logged sessions were left behind — <see cref="PrepareMigration"/>
    /// runs before any window exists, so there is nothing to show a dialog on at the time.
    /// </summary>
    public static string? QuarantinedDatabasePath { get; private set; }
    #endregion

    #region Public Methods
    /// <summary>
    /// Seeds migration history for existing databases and checks whether
    /// there are pending migrations. Call this before <see cref="ApplyMigrations"/>
    /// to determine if a status UI should be shown.
    /// </summary>
    /// <remarks>
    /// Every read here assumed the file at <paramref name="databasePath"/>, if it exists, IS a
    /// SQLite database. Nothing had ever checked. A damaged <c>DAQiFiDatabase.db</c> therefore threw
    /// <see cref="SqliteException"/> out of <c>SeedMigrationHistoryIfNeeded</c>'s first
    /// <c>sqlite_master</c> query, straight out of <c>App.Initialize</c> and
    /// <c>OnFrameworkInitializationCompleted</c>, killing the process before a window existed — and
    /// the next launch found the same file and did the same thing. It now recovers instead.
    /// </remarks>
    /// <param name="contextFactory">The DbContext factory registered in DI.</param>
    /// <param name="databasePath">Full path to the SQLite database file.</param>
    /// <returns><c>true</c> if there are pending migrations to apply.</returns>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.PrepareMigration
    public static bool PrepareMigration(IDbContextFactory<LoggingContext> contextFactory, string databasePath)
    {
        try
        {
            return SeedHistoryAndCheckPending(contextFactory, databasePath);
        }
        catch (Exception ex) when (FindContentCorruption(ex) is { } corruption)
        {
            AppLogger.Instance.Error(ex, "Reading the database to check for pending migrations failed: the file is corrupt");
            if (QuarantineDatabase(databasePath, corruption) is null)
            {
                throw;
            }

            // Against the file that was just created in its place. A second corruption here would
            // mean the fresh database is damaged too, which is a real bug, so it is left to throw.
            return SeedHistoryAndCheckPending(contextFactory, databasePath);
        }
    }

    /// <summary>
    /// Applies pending EF Core migrations with backup and rollback support.
    /// Call <see cref="PrepareMigration"/> first to seed history and check
    /// whether migrations are needed.
    /// </summary>
    /// <param name="contextFactory">The DbContext factory registered in DI.</param>
    /// <param name="databasePath">Full path to the SQLite database file.</param>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.ApplyMigrations
    public static void ApplyMigrations(IDbContextFactory<LoggingContext> contextFactory, string databasePath)
    {
        var backupPath = BackupDatabase(databasePath);
        CheckpointWal(databasePath);

        try
        {
            RunMigrations(contextFactory);
        }
        catch (Exception ex) when (FindContentCorruption(ex) is { } corruption)
        {
            // Corruption the pending-migration read did not reach. That read only touches the schema
            // catalog and __EFMigrationsHistory; damage confined to pages the migration itself
            // rewrites surfaces here for the first time. Restoring the backup would restore the same
            // damage — it was copied from this very file — so rebuild rather than roll back.
            AppLogger.Instance.Error(ex, "Database migration failed: the database file is corrupt");
            if (QuarantineDatabase(databasePath, corruption) is null)
            {
                RestoreBackup(backupPath, databasePath);
                throw;
            }

            CleanupBackup(backupPath);
            RunMigrations(contextFactory);
            AppLogger.Instance.AddBreadcrumb("database", "Corrupt database quarantined; a new one was migrated in its place");
            return;
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Error(ex, "Database migration failed");
            RestoreBackup(backupPath, databasePath);
            throw;
        }

        CleanupBackup(backupPath);
        AppLogger.Instance.AddBreadcrumb("database", "Database migration completed successfully");
    }

    /// <summary>
    /// Migrates for a host that has no migration UI to drive — the mobile heads, which cannot show
    /// <c>MigrationStatusWindow</c> and so never call <see cref="PrepareMigration"/>. Gets the same
    /// corruption recovery: quarantine the unreadable file and migrate a fresh one in its place.
    /// </summary>
    /// <param name="contextFactory">The DbContext factory registered in DI.</param>
    /// <param name="databasePath">Full path to the SQLite database file.</param>
    public static void MigrateWithCorruptionRecovery(IDbContextFactory<LoggingContext> contextFactory, string databasePath)
    {
        try
        {
            RunMigrations(contextFactory);
        }
        catch (Exception ex) when (FindContentCorruption(ex) is { } corruption)
        {
            AppLogger.Instance.Error(ex, "Database migration failed: the database file is corrupt");
            if (QuarantineDatabase(databasePath, corruption) is null)
            {
                throw;
            }

            RunMigrations(contextFactory);
        }
    }

    /// <summary>
    /// The one user-facing sentence describing this run's quarantine, or <c>null</c> when there was
    /// none. Lives here so the desktop notification list and the mobile notifications overlay say
    /// the same thing.
    /// </summary>
    public static string? DescribeQuarantineForUser() => QuarantinedDatabasePath is { } path
        ? $"The logged-data database could not be read and was moved to '{path}'. A new, empty one "
          + "is in use — previously logged sessions are not in it, and the old file has not been deleted."
        : null;
    #endregion

    #region Private Methods
    /// <summary>The pre-migration read, factored out so the recovery path can repeat it verbatim.</summary>
    private static bool SeedHistoryAndCheckPending(IDbContextFactory<LoggingContext> contextFactory, string databasePath)
    {
        SeedMigrationHistoryIfNeeded(databasePath);
        SqliteConnection.ClearAllPools();
        return HasPendingMigrations(contextFactory);
    }

    /// <summary>The migration itself, factored out for the same reason.</summary>
    private static void RunMigrations(IDbContextFactory<LoggingContext> contextFactory)
    {
        using var context = contextFactory.CreateDbContext();
        context.Database.Migrate();
    }

    /// <summary>
    /// Searches an exception and its inner chain for SQLite saying the database FILE'S CONTENT is
    /// unusable, which is the only kind of failure a quarantine is a valid answer to.
    /// </summary>
    /// <remarks>
    /// Asking the operation that actually failed, rather than probing up front, is deliberate. A
    /// cheap pre-flight query (<c>SELECT COUNT(*) FROM sqlite_master</c>) validates the header and
    /// the schema catalog and nothing else — measured: a database whose pages past page 1 are
    /// overwritten passes it and then throws <c>SQLITE_CORRUPT</c> on the very next table read, so
    /// a probe-first design would have left that file in place and crashed startup anyway. The
    /// thorough pre-flight, <c>PRAGMA integrity_check</c>, walks the whole file, and this runs on
    /// every launch of an app whose database routinely holds millions of samples. Catching the real
    /// failure costs nothing on a healthy launch and covers exactly the reads that happen.
    /// <para>
    /// The chain walk matters because EF Core wraps provider exceptions; the corruption is often the
    /// inner one.
    /// </para>
    /// </remarks>
    private static SqliteException? FindContentCorruption(Exception? exception)
    {
        for (var current = exception; current is not null; current = current.InnerException)
        {
            if (current is SqliteException sqlite && sqlite.SqliteErrorCode is SQLITE_CORRUPT or SQLITE_NOTADB)
            {
                return sqlite;
            }
        }

        return null;
    }

    /// <summary>
    /// Moves a proven-unreadable database file aside so the caller can create a fresh one, and
    /// records where it went.
    /// </summary>
    /// <remarks>
    /// The damaged file is RENAMED, never deleted: it is the user's logged data, and a corrupt
    /// SQLite file is frequently still partly recoverable with <c>sqlite3 .recover</c>.
    /// </remarks>
    /// <param name="databasePath">Full path to the SQLite database file.</param>
    /// <param name="fault">The exception proving the file is unreadable, for the log.</param>
    /// <returns>The path the file was moved to, or <c>null</c> if nothing was moved.</returns>
    private static string? QuarantineDatabase(string databasePath, Exception fault)
    {
        if (!File.Exists(databasePath))
        {
            // Corruption reported for a path with no file at it: nothing to move, and creating a
            // quarantine name for it would say something untrue.
            return null;
        }

        // Drop any pooled handle on the file first, or the move fails on Windows.
        SqliteConnection.ClearAllPools();

        // Millisecond precision and overwrite:false together guarantee a previous quarantine is
        // never clobbered — the whole point is that nothing the user might still recover gets
        // destroyed. A same-millisecond collision instead fails the move, which is logged below and
        // leaves the file untouched.
        var quarantinePath = $"{databasePath}.corrupt-{DateTime.UtcNow:yyyyMMdd-HHmmssfff}";

        // Order matters, and the sidecars go FIRST. A stale -wal is not inert: SQLite replays a
        // journal whose header still checksums, so one left beside the replacement database would
        // write the old file's pages into it — one corrupt file traded for another. Moving the
        // database first and only then failing on a sidecar produces exactly that state, so if a
        // sidecar cannot be moved this stops before touching the database and leaves the directory
        // as it was: the app still refuses to start, but loudly, with nothing half-done.
        //
        // Nothing is ever deleted. A -wal can hold the only committed copy of the user's last
        // samples, so it is moved beside its database or not at all.
        if (!TryRelocateSidecar(databasePath + "-wal", quarantinePath + "-wal")
            || !TryRelocateSidecar(databasePath + "-shm", quarantinePath + "-shm"))
        {
            return null;
        }

        try
        {
            File.Move(databasePath, quarantinePath, overwrite: false);
        }
        catch (Exception ex)
        {
            // The sidecars (if any) are already at the quarantine name and the database is still in
            // place — no replacement is created, so nothing can be replayed into one. The next
            // launch retries and finds nothing left to move.
            AppLogger.Instance.Error(ex,
                $"Database at '{databasePath}' is unreadable and could not be moved aside to '{quarantinePath}'");
            return null;
        }

        QuarantinedDatabasePath = quarantinePath;
        AppLogger.Instance.Error(fault,
            $"Database at '{databasePath}' could not be read and was moved to '{quarantinePath}'. " +
            "A new, empty database will be created; previously logged sessions are not in it.");

        return quarantinePath;
    }

    /// <summary>
    /// Moves a <c>-wal</c>/<c>-shm</c> sidecar to sit beside its quarantined database.
    /// </summary>
    /// <returns>
    /// <c>true</c> when the sidecar is absent or was moved — i.e. when it is safe to create a
    /// replacement database at the original path.
    /// </returns>
    private static bool TryRelocateSidecar(string sidecarPath, string destinationPath)
    {
        if (!File.Exists(sidecarPath))
        {
            return true;
        }

        try
        {
            File.Move(sidecarPath, destinationPath, overwrite: false);
            return true;
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Error(ex,
                $"Could not move '{sidecarPath}' aside, so the database it belongs to is being left in place " +
                "rather than replaced next to a journal SQLite could replay into the replacement");
            return false;
        }
    }

    /// <summary>
    /// Checks whether there are any pending migrations to apply.
    /// </summary>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.HasPendingMigrations
    private static bool HasPendingMigrations(IDbContextFactory<LoggingContext> contextFactory)
    {
        using var context = contextFactory.CreateDbContext();
        var pending = context.Database.GetPendingMigrations();
        return pending.Any();
    }

    /// <summary>
    /// Creates a backup copy of the SQLite database file before applying migrations.
    /// </summary>
    /// <returns>The backup file path, or null if no backup was created.</returns>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.BackupDatabase
    private static string BackupDatabase(string databasePath)
    {
        try
        {
            if (!File.Exists(databasePath))
            {
                return null;
            }

            var backupPath = databasePath + ".migration-backup";
            File.Copy(databasePath, backupPath, overwrite: true);
            return backupPath;
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Error(ex, "Failed to back up database before migration");
            return null;
        }
    }

    /// <summary>
    /// Removes the backup file after a successful migration.
    /// </summary>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.CleanupBackup
    private static void CleanupBackup(string backupPath)
    {
        try
        {
            if (!string.IsNullOrEmpty(backupPath) && File.Exists(backupPath))
            {
                File.Delete(backupPath);
            }
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Error(ex, "Failed to delete migration backup file");
        }
    }

    /// <summary>
    /// Flushes the WAL journal into the main database file using PRAGMA wal_checkpoint.
    /// This is safer than deleting WAL/SHM files directly, which could cause data loss
    /// if uncommitted transactions exist.
    /// </summary>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.CheckpointWal
    private static void CheckpointWal(string databasePath)
    {
        try
        {
            var connectionString = $"Data source={databasePath}";
            using var connection = new SqliteConnection(connectionString);
            connection.Open();

            using var command = connection.CreateCommand();
            command.CommandText = "PRAGMA wal_checkpoint(TRUNCATE);";
            command.ExecuteNonQuery();

            connection.Close();
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Error(ex, "Failed to checkpoint WAL — migration will proceed anyway");
        }
    }

    /// <summary>
    /// Restores the database from backup after a failed migration.
    /// </summary>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.RestoreBackup
    private static void RestoreBackup(string backupPath, string databasePath)
    {
        try
        {
            if (!string.IsNullOrEmpty(backupPath) && File.Exists(backupPath))
            {
                SqliteConnection.ClearAllPools();
                File.Copy(backupPath, databasePath, overwrite: true);
                AppLogger.Instance.Error(null, "Database restored from backup after migration failure");
            }
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Error(ex, "Failed to restore database from backup — manual recovery may be needed");
        }
    }

    /// <summary>
    /// For databases created by <c>EnsureCreated()</c>, the <c>__EFMigrationsHistory</c>
    /// table does not exist. This method creates it and seeds the initial migration entry
    /// so that <c>Migrate()</c> only applies subsequent migrations.
    /// Uses a raw <see cref="SqliteConnection"/> to avoid EF connection pooling locks.
    /// </summary>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.SeedMigrationHistoryIfNeeded
    private static void SeedMigrationHistoryIfNeeded(string databasePath)
    {
        if (!File.Exists(databasePath))
        {
            return;
        }

        var connectionString = $"Data source={databasePath}";
        using var connection = new SqliteConnection(connectionString);
        connection.Open();

        if (HasMigrationHistoryTable(connection))
        {
            connection.Close();
            return;
        }

        if (!HasExistingTables(connection))
        {
            connection.Close();
            return;
        }

        using var command = connection.CreateCommand();
        command.CommandText =
            "CREATE TABLE IF NOT EXISTS \"__EFMigrationsHistory\" " +
            "(\"MigrationId\" TEXT NOT NULL PRIMARY KEY, \"ProductVersion\" TEXT NOT NULL); " +
            "INSERT OR IGNORE INTO \"__EFMigrationsHistory\" " +
            $"VALUES ('{INITIAL_MIGRATION_ID}', '{EF_PRODUCT_VERSION}');";
        command.ExecuteNonQuery();

        connection.Close();
    }

    /// <summary>
    /// Checks whether the <c>__EFMigrationsHistory</c> table exists in the database.
    /// </summary>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.HasMigrationHistoryTable
    private static bool HasMigrationHistoryTable(SqliteConnection connection)
    {
        using var command = connection.CreateCommand();
        command.CommandText =
            "SELECT COUNT(*) FROM sqlite_master " +
            "WHERE type='table' AND name='__EFMigrationsHistory'";
        var result = command.ExecuteScalar();
        return result is long count && count > 0;
    }

    /// <summary>
    /// Checks whether the database has existing application tables (created by <c>EnsureCreated()</c>).
    /// </summary>
    // @port: Daqifi.Desktop.Logger.DatabaseMigrator.HasExistingTables
    private static bool HasExistingTables(SqliteConnection connection)
    {
        using var command = connection.CreateCommand();
        command.CommandText =
            "SELECT COUNT(*) FROM sqlite_master " +
            "WHERE type='table' AND name='Samples'";
        var result = command.ExecuteScalar();
        return result is long count && count > 0;
    }
    #endregion
}
