// Generated by portomatic scaffold from upstream Daqifi.Desktop/Loggers/ILogger.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Daqifi.Desktop.Channel;
using Daqifi.Desktop.Device;

namespace Daqifi.Desktop.Logger;

// @port: Daqifi.Desktop.Logger.ILogger
public interface ILogger
{
    // @port: Daqifi.Desktop.Logger.ILogger.Log
    void Log(DataSample dataSample);

    // @port: Daqifi.Desktop.Logger.ILogger.Log
    void Log(DeviceMessage dataSample);
}