// Generated by portomatic scaffold from upstream Daqifi.Desktop/Loggers/LoggingManager.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Daqifi.Desktop.Channel;
using Daqifi.Desktop.Device;
using Daqifi.Desktop.Models;
using Daqifi.Desktop.Common.Loggers;
using System.IO;
using System.Xml.Linq;
using System.Collections.ObjectModel;
using Daqifi.Desktop.UpdateVersion;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using CommunityToolkit.Mvvm.ComponentModel;
using Avalonia.Threading;

namespace Daqifi.Desktop.Logger;

// @port: Daqifi.Desktop.Logger.LoggingManager
public partial class LoggingManager : ObservableObject
{
    #region Private Variables
    // @port: Daqifi.Desktop.Logger.LoggingManager.Instance
    private readonly AppLogger AppLogger = AppLogger.Instance;
    // Use the shared, elevation-aware data directory (AppDataPaths) so the profiles XML is
    // written to a location the process can actually write (per-user when un-elevated),
    // instead of failing on the admin-owned %ProgramData% file.
    private static string ProfileAppDirectory = Daqifi.Desktop.Common.AppDataPaths.DataDirectory;
    // Path.Combine, not upstream's `ProfileAppDirectory + "\\..."` — see the same fix in
    // DaqifiSettings. On macOS/Linux the backslash is a legal filename character, so the
    // concatenation silently writes `DAQiFi\DAQifiProfilesConfiguration.xml` beside the data
    // directory rather than inside it. Identical result on Windows.
    private static readonly string ProfileSettingsXmlPath = Path.Combine(ProfileAppDirectory, "DAQifiProfilesConfiguration.xml");
    private readonly IDbContextFactory<LoggingContext> _loggingContext;

    /// <summary>
    /// Serializes writers of <see cref="SubscribedChannels"/>. Readers never take it -- they read a
    /// published snapshot -- so it is never held while calling into a logger or raising a
    /// notification, and it cannot nest inside any other lock.
    /// </summary>
    private readonly object _subscribedChannelsSync = new();

    private bool _hasActiveApplicationSession;
    private bool _hasActiveApplicationSamples;
    #endregion

    #region Properties
    // @port: Daqifi.Desktop.Logger.LoggingManager.Loggers
    public List<ILogger> Loggers { get; }

    private IReadOnlyList<IChannel> _subscribedChannels = Array.Empty<IChannel>();

    /// <summary>
    /// Gets the channels currently subscribed for logging.
    /// </summary>
    /// <remarks>
    /// The returned list is a <b>snapshot that is never mutated</b>: every change goes through
    /// <see cref="Subscribe"/>, <see cref="Unsubscribe"/> or <see cref="ClearChannelList"/>, each of
    /// which publishes a brand-new list rather than changing this one in place (copy-on-write). That
    /// is what makes the property safe to read from a non-UI thread -- <see cref="PlotLogger"/>
    /// resolves channel visibility from the device transport thread while the UI thread subscribes
    /// and unsubscribes, and <see cref="List{T}"/> does not tolerate a read that overlaps an
    /// Add/Remove/Clear (it throws <see cref="InvalidOperationException"/> mid-enumeration, or
    /// observes a torn state). Exposed as <see cref="IReadOnlyList{T}"/>, and those three methods are
    /// the only way in, so the guarantee is a property of the API rather than of caller discipline.
    /// Written under <see cref="_subscribedChannelsSync"/> and published with <see cref="Volatile"/>
    /// so a reader on another core cannot observe a partially constructed list -- an explicit property
    /// rather than [ObservableProperty] for exactly that reason (the generated accessors do a plain
    /// field read/write).
    /// </remarks>
    public IReadOnlyList<IChannel> SubscribedChannels => Volatile.Read(ref _subscribedChannels);

    [ObservableProperty]
    private bool _active;

    [ObservableProperty]
    private LoggingMode _currentMode;

    [ObservableProperty]
    private LoggingSession _session;

    [ObservableProperty]
    private ObservableCollection<LoggingSession> _loggingSessions = [];
    #endregion

    // @port: Daqifi.Desktop.Logger.LoggingManager.OnActiveChanged
    partial void OnActiveChanged(bool oldValue, bool newValue)
    {
        if (!newValue && oldValue) // Was active, now stopping
        {
            if (_hasActiveApplicationSession && Session != null)
            {
                if (_hasActiveApplicationSamples)
                {
                    if (!LoggingSessions.Any(s => s.ID == Session.ID))
                    {
                        LoggingSessions.Add(Session);
                    }

                    // Finalize the session by recording its sample count so the
                    // list view never has to count rows. Runs on a background
                    // thread because COUNT(*) on a multi-million-row session
                    // would otherwise block the UI thread that toggled Active.
                    // The list row updates automatically when SampleCount is
                    // set, since LoggingSession is INotifyPropertyChanged.
                    var sessionToFinalize = Session;
                    _ = Task.Run(() => PersistSessionSampleCount(sessionToFinalize));
                }
                else
                {
                    DeleteLoggingSessionIfPresent(Session.ID);
                }
            }

            _hasActiveApplicationSession = false;
            _hasActiveApplicationSamples = false;
        }
        else if (newValue && !oldValue) // Was inactive, now starting
        {
            foreach (var channel in SubscribedChannels.ToList())
            {
                channel.OnChannelUpdated -= HandleChannelUpdate;
            }

            // Clear loggers
            foreach (var logger in Loggers)
            {
                if (logger is PlotLogger plotLogger)
                {
                    plotLogger.ClearPlot();
                }
                else if (logger is DatabaseLogger dbLogger)
                {
                    dbLogger.ClearPlot();
                }
            }

            if (CurrentMode != LoggingMode.Stream)
            {
                _hasActiveApplicationSession = false;
                _hasActiveApplicationSamples = false;
                return;
            }

            using (var context = _loggingContext.CreateDbContext())
            {
                // Pick an ID that cannot collide with any existing row in any
                // related table. Sessions.ID is manually assigned (not IDENTITY),
                // so reusing the max+1 across only the Sessions table can hand
                // out an ID that is still referenced by orphan rows in
                // SessionDeviceMetadata or Samples (e.g., from a prior crash, or
                // a delete that ran without SQLite foreign keys enabled). The
                // composite PK on SessionDeviceMetadata then rejects the insert
                // with UNIQUE constraint failed and the toggle appears to do
                // nothing on the second attempt.
                //
                // This runs synchronously on the UI thread (IsLogging is a
                // UI-bound toggle), so the cost matters as the database grows.
                // Folding the three MAXes into a single SQL statement keeps the
                // round-trip count at one. Each inner MAX hits an index — Sessions.ID
                // is the PK, SessionDeviceMetadata.LoggingSessionID is the leading
                // column of the composite PK, and Samples has IX_Samples_SessionTime
                // on (LoggingSessionID, TimestampTicks) — so SQLite resolves each
                // MAX as an index seek rather than a table scan.
                const string nextSessionIdSql = @"
                    SELECT MAX(id) AS Value FROM (
                        SELECT MAX(ID) AS id FROM Sessions
                        UNION ALL SELECT MAX(LoggingSessionID) AS id FROM SessionDeviceMetadata
                        UNION ALL SELECT MAX(LoggingSessionID) AS id FROM Samples
                    )";
                var maxKnownId = context.Database.SqlQueryRaw<int?>(nextSessionIdSql)
                    .AsEnumerable()
                    .FirstOrDefault() ?? -1;
                var newId = maxKnownId + 1;
                var name = $"Session_{newId}";
                Session = new LoggingSession(newId, name);
                context.Sessions.Add(Session);

                // Capture per-device metadata (sampling frequency, name) for the
                // devices that own the subscribed channels, so the session UI can
                // display configuration without re-deriving it from sample data.
                // Failures here must not block session creation — the session is
                // still usable without metadata; the legend just won't show
                // sampling frequency.
                try
                {
                    foreach (var metadata in BuildDeviceMetadataForSession(newId))
                    {
                        // EF Core's relationship fix-up automatically attaches
                        // this row to Session.DeviceMetadata because the FK
                        // matches the tracked Session. Adding to the nav
                        // collection explicitly would insert the same CLR
                        // reference a second time, making FrequencyDisplay show
                        // duplicate entries until the next reload.
                        context.SessionDeviceMetadata.Add(metadata);
                    }
                }
                catch (Exception ex)
                {
                    AppLogger.Error(ex, $"Failed to capture device metadata for session {newId}; continuing without it.");
                }

                context.SaveChanges();
            }

            _hasActiveApplicationSession = true;
            _hasActiveApplicationSamples = false;

            // Resubscribe channels
            foreach (var channel in SubscribedChannels.ToList())
            {
                channel.OnChannelUpdated += HandleChannelUpdate;
            }
        }
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.OnCurrentModeChanged
    partial void OnCurrentModeChanged(LoggingMode value)
    {
        // If switching to SD card mode, stop streaming
        if (value == LoggingMode.SdCard && Active)
        {
            Active = false; // Setting Active will trigger OnActiveChanged
        }
    }

    #region Singleton Constructor / Initalization
    private static readonly LoggingManager instance = new();

    private LoggingManager()
    {
        Loggers = [];
        // _subscribedChannels starts empty via its field initializer; it has no setter (copy-on-write).
        _loggingContext = App.ServiceProvider.GetRequiredService<IDbContextFactory<LoggingContext>>();
    }

    public static LoggingManager Instance => instance;

    #endregion

    #region Profile Subscription

    #region Profile feature Properties

    [ObservableProperty] private ObservableCollection<Profile> _subscribedProfiles = [];

    [ObservableProperty]
    private Profile _selectedProfile;

    [ObservableProperty]
    private bool _flag;

    [ObservableProperty]
    private ObservableCollection<ProfileChannel> _selectedProfileChannels = [];

    [ObservableProperty]
    private ObservableCollection<ProfileDevice> _selectedProfileDevices = [];
    #endregion

    // @port: Daqifi.Desktop.Logger.LoggingManager.SubscribeProfile
    public void SubscribeProfile(Profile profile)
    {
        try
        {
            if (SubscribedProfiles.Contains(profile)) { return; }
            AddAndRemoveProfileXml(profile, true);
            SubscribedProfiles.Add(profile);
        }
        catch (Exception ex)
        {
            AppLogger.Error(ex, "Error Subscribe Profile");
        }
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.callPropertyChange
    public void callPropertyChange()
    {
        OnPropertyChanged("SelectedProfileChannels");
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.UpdateProfileInXml
    public void UpdateProfileInXml(Profile profile)
    {
        try
        {
            if (!File.Exists(ProfileSettingsXmlPath))
            {
                AppLogger.Error("Profile settings XML file does not exist.");
                return;
            }
            var doc = XDocument.Load(ProfileSettingsXmlPath);
            var profileToUpdate = doc.Descendants("Profile")
                .FirstOrDefault(p => (Guid)p.Element("ProfileID") == profile.ProfileId);
            if (profileToUpdate != null)
            {
                profileToUpdate.Element("Name")?.SetValue(profile.Name);
                profileToUpdate.Element("CreatedOn")?.SetValue(profile.CreatedOn);
                var devicesElement = profileToUpdate.Element("Devices");
                devicesElement?.RemoveAll();
                foreach (var device in profile.Devices)
                {
                    var deviceElement = new XElement("Device",
                        new XElement("DeviceName", device.DeviceName),
                        new XElement("DevicePartNumber", device.DevicePartName),
                        new XElement("MACAddress", device.MacAddress),
                        new XElement("DeviceSerialNo", device.DeviceSerialNo),
                        new XElement("SamplingFrequency", device.SamplingFrequency)
                    );

                    var activeChannels = device.Channels
                        .Where(channel => channel.IsChannelActive)
                        .Select(channel => new XElement("Channel",
                            new XElement("Name", channel.Name),
                            new XElement("Type", channel.Type),
                            new XElement("IsActive", channel.IsChannelActive)
                        )).ToList();

                    if (activeChannels.Any())
                    {
                        deviceElement.Add(new XElement("Channels", activeChannels));
                    }

                    devicesElement?.Add(deviceElement);
                }
                doc.Save(ProfileSettingsXmlPath);
            }
            else
            {
                AppLogger.Error($"Profile with ID {profile.ProfileId} not found for updating.");
            }
        }
        catch (Exception ex)
        {
            AppLogger.Error(ex, "Error updating profile in XML");
        }
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.AddAndRemoveProfileXml
    public void AddAndRemoveProfileXml(Profile profile, bool AddProfileFlag)
    {
        try
        {
            if (!Directory.Exists(ProfileAppDirectory))
            {
                Directory.CreateDirectory(ProfileAppDirectory);
            }
            if (!File.Exists(ProfileSettingsXmlPath))
            {
                var newDoc = new XDocument(
                    new XElement("Profiles")
                );
                newDoc.Save(ProfileSettingsXmlPath);
            }
            var doc = XDocument.Load(ProfileSettingsXmlPath);
            if (profile != null)
            {
                if (AddProfileFlag)
                {
                    var newProfile = new XElement("Profile",
                        new XElement("Name", profile.Name),
                        new XElement("ProfileID", profile.ProfileId),
                        new XElement("CreatedOn", profile.CreatedOn),
                        new XElement("Devices",
                            from device in profile.Devices
                            select new XElement("Device",
                                new XElement("DeviceName", device.DeviceName),
                                new XElement("DevicePartNumber", device.DevicePartName),
                                new XElement("MACAddress", device.MacAddress),
                                new XElement("DeviceSerialNo", device.DeviceSerialNo),
                                new XElement("Channels",
                                    from channel in device.Channels
                                    where channel.IsChannelActive
                                    select new XElement("Channel",
                                        new XElement("Name", channel.Name),
                                        new XElement("Type", channel.Type),
                                        new XElement("IsActive", channel.IsChannelActive)
                                    )
                                ),
                                new XElement("SamplingFrequency", device.SamplingFrequency)
                            )
                        )
                    );

                    doc.Root?.Add(newProfile);
                }
                else
                {
                    var profileToRemove = doc.Descendants("Profile")
                        .FirstOrDefault(p => (Guid)p.Element("ProfileID") == profile.ProfileId);
                    profileToRemove?.Remove();
                    SubscribedProfiles.Remove(profile);
                }
            }
            doc.Save(ProfileSettingsXmlPath);
        }
        catch (Exception ex)
        {
            AppLogger.Error(ex, "Error Setting Selected profile");
        }
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.LoadProfilesFromXml
    public List<Profile> LoadProfilesFromXml()
    {
        SubscribedProfiles.Clear();

        try
        {
            // Check if the profile settings file exists
            if (File.Exists(ProfileSettingsXmlPath))
            {
                // Load the XML document
                var doc = XDocument.Load(ProfileSettingsXmlPath);

                // Parse the XML and retrieve the profiles
                var loadedProfiles = doc.Descendants("Profile").Select(p => new Profile
                {
                    Name = (string)p.Element("Name"),
                    ProfileId = (Guid)p.Element("ProfileID"),
                    CreatedOn = (DateTime)p.Element("CreatedOn"),
                    Devices = new ObservableCollection<ProfileDevice>(p.Element("Devices")?.Elements("Device").Select(d => new ProfileDevice
                    {
                        DeviceName = (string)d.Element("DeviceName"),
                        DevicePartName = (string)d.Element("DevicePartNumber"),
                        MacAddress = (string)d.Element("MACAddress"),
                        DeviceSerialNo = (string)d.Element("DeviceSerialNo"),
                        SamplingFrequency = (int)d.Element("SamplingFrequency"),
                        // The writer omits <Channels> when the device has no active channels
                        // (see UpdateProfileInXml / AddAndRemoveProfileXml). Default to an empty
                        // list so downstream code can call .Where/.Select without a null check.
                        Channels = d.Element("Channels")?.Elements("Channel").Select(c => new ProfileChannel
                        {
                            Name = (string)c.Element("Name"),
                            Type = (string)c.Element("Type"),
                            IsChannelActive = (bool)c.Element("IsActive"),
                            SerialNo = (string)d.Element("DeviceSerialNo")
                        }).ToList() ?? []
                    }).ToList())
                }).ToList();

                // Add each profile to the existing collection
                foreach (var profile in loadedProfiles)
                {
                    SubscribedProfiles.Add(profile);
                }

                return loadedProfiles;
            }
        }
        catch (Exception ex)
        {
            AppLogger.Error(ex, "Error Loading Profiles from XML");
        }

        return SubscribedProfiles.ToList();
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.UnsubscribeProfile
    public void UnsubscribeProfile(Profile profile)
    {
        try
        {
            var subscribedProfile = SubscribedProfiles.FirstOrDefault(x => x.ProfileId == profile.ProfileId);
            if (subscribedProfile == null)
            {
                return;
            }

            AddAndRemoveProfileXml(subscribedProfile, false);
            ClearChannelList();
        }
        catch (Exception ex)
        {
            AppLogger.Error(ex, "Error Unsubscribe Profile");
        }
    }
    #endregion

    #region Channel Subscription
    // @port: Daqifi.Desktop.Logger.LoggingManager.Subscribe
    public void Subscribe(IChannel channel)
    {
        lock (_subscribedChannelsSync)
        {
            var current = _subscribedChannels;

            if (current.Any(x => x.DeviceSerialNo == channel.DeviceSerialNo && x.Name == channel.Name))
            {
                return;
            }

            channel.IsActive = true;

            // Only attach streaming handlers if in Stream mode
            if (CurrentMode == LoggingMode.Stream)
            {
                channel.OnChannelUpdated += HandleChannelUpdate;
            }

            // Copy-on-write: publish a new immutable snapshot (AsReadOnly wraps the fresh list so a
            // caller cannot downcast the published value back to List and mutate it) instead of
            // Add-ing to the one a reader on the transport thread may be enumerating right now. See
            // SubscribedChannels' remarks.
            List<IChannel> updated = [.. current, channel];
            Volatile.Write(ref _subscribedChannels, updated.AsReadOnly());
        }

        // Raised outside the lock so a binding handler can never re-enter under it.
        OnPropertyChanged(nameof(SubscribedChannels));
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.Unsubscribe
    public void Unsubscribe(IChannel channel)
    {
        lock (_subscribedChannelsSync)
        {
            var current = _subscribedChannels;

            var subscribedChannel = current.FirstOrDefault(
                x => x.DeviceSerialNo == channel.DeviceSerialNo && x.Name == channel.Name && x.IsActive);

            if (subscribedChannel == null)
            {
                return;
            }

            subscribedChannel.IsActive = false;

            // Remove event handler if it's attached
            subscribedChannel.OnChannelUpdated -= HandleChannelUpdate;

            // Copy-on-write -- see SubscribedChannels' remarks. AsReadOnly so the published snapshot
            // cannot be downcast to List and mutated outside the lock.
            var updated = new List<IChannel>(current);
            updated.Remove(subscribedChannel);
            Volatile.Write(ref _subscribedChannels, updated.AsReadOnly());
        }

        // Raised outside the lock so a binding handler can never re-enter under it.
        OnPropertyChanged(nameof(SubscribedChannels));
    }
    #endregion

    /// <summary>
    /// Builds <see cref="SessionDeviceMetadata"/> rows for every device that has
    /// at least one subscribed channel at the start of a logging session.
    /// </summary>
    /// <param name="sessionId">The id of the session being created.</param>
    /// <returns>One materialized metadata entry per distinct device serial number.</returns>
    /// <remarks>
    /// Snapshots <see cref="SubscribedChannels"/> and
    /// <see cref="ConnectionManager.ConnectedDevices"/> up front so the result is
    /// computed against stable copies — these collections can otherwise mutate
    /// concurrently (e.g., from device-connection background threads) and throw
    /// during enumeration. Returns a fully materialized list rather than yielding
    /// lazily so the caller is never iterating against the live collections.
    /// Uses <see cref="StringComparer.Ordinal"/> for serial-number deduplication
    /// because device serials are opaque identifiers, not culture-sensitive text.
    /// </remarks>
    // @port: Daqifi.Desktop.Logger.LoggingManager.BuildDeviceMetadataForSession
    private List<SessionDeviceMetadata> BuildDeviceMetadataForSession(int sessionId)
    {
        var result = new List<SessionDeviceMetadata>();

        // Snapshot inputs before iterating to avoid concurrent-modification
        // exceptions on the underlying mutable lists.
        var subscribedChannelsSnapshot = SubscribedChannels?.ToList() ?? new List<IChannel>();
        var connectedDevicesSnapshot = ConnectionManager.Instance.ConnectedDevices?.ToList()
            ?? new List<IStreamingDevice>();

        var subscribedSerials = subscribedChannelsSnapshot
            .Select(c => c.DeviceSerialNo)
            .Where(s => !string.IsNullOrEmpty(s))
            .ToHashSet(StringComparer.Ordinal);

        if (subscribedSerials.Count == 0)
        {
            return result;
        }

        var emittedSerials = new HashSet<string>(StringComparer.Ordinal);

        foreach (var device in connectedDevicesSnapshot)
        {
            if (device == null || string.IsNullOrEmpty(device.DeviceSerialNo))
            {
                continue;
            }

            if (!subscribedSerials.Contains(device.DeviceSerialNo))
            {
                continue;
            }

            // Defensive: ConnectedDevices can briefly contain two entries with the
            // same serial (e.g., during USB re-enumeration). The composite primary
            // key on (LoggingSessionID, DeviceSerialNo) would otherwise reject the
            // second row and abort the session start.
            if (!emittedSerials.Add(device.DeviceSerialNo))
            {
                continue;
            }

            result.Add(new SessionDeviceMetadata
            {
                LoggingSessionID = sessionId,
                DeviceSerialNo = device.DeviceSerialNo,
                DeviceName = device.Name ?? string.Empty,
                SamplingFrequencyHz = device.StreamingFrequency
            });
        }

        return result;
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.HandleDeviceMessage
    public void HandleDeviceMessage(object sender, DeviceMessage sample)
    {
        if (!Active || CurrentMode != LoggingMode.Stream || !_hasActiveApplicationSession)
        {
            return;
        }

        sample.LoggingSessionID = Session.ID;

        //Log channel value to whatever loggers are being managed
        foreach (var logger in Loggers)
        {
            logger.Log(sample);
        }
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.HandleChannelUpdate
    public void HandleChannelUpdate(object sender, DataSample sample)
    {
        if (!Active || CurrentMode != LoggingMode.Stream || !_hasActiveApplicationSession)
        {
            return;
        }

        if (sample == null)
        {
            return;
        }

        _hasActiveApplicationSamples = true;
        sample.LoggingSessionID = Session.ID;

        // Log channel value to whatever loggers are being managed
        foreach (var logger in Loggers)
        {
            logger.Log(sample);
        }
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.AddLogger
    public void AddLogger(ILogger logger)
    {
        Loggers.Add(logger);
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.CheckApplicationVersion
    public async Task CheckApplicationVersion(VersionNotification versionNotification)
    {
        await versionNotification.CheckForUpdatesAsync();
        OnPropertyChanged("NotificationCount");
        OnPropertyChanged("VersionNumber");
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.LoadPersistedLoggingSessions
    public ObservableCollection<LoggingSession> LoadPersistedLoggingSessions()
    {
        using var context = _loggingContext.CreateDbContext();

        var emptySessions = context.Sessions
            .Where(session => !context.Samples.Any(sample => sample.LoggingSessionID == session.ID))
            .ToList();

        if (emptySessions.Count > 0)
        {
            context.Sessions.RemoveRange(emptySessions);
            context.SaveChanges();
        }

        // Sweep orphan SessionDeviceMetadata rows whose Sessions row is gone.
        // SQLite cascade delete only fires when PRAGMA foreign_keys=ON for the
        // active connection; if any prior delete ran without it, metadata for
        // long-gone sessions can linger and collide with future session IDs
        // (the composite PK rejects the new insert with UNIQUE constraint
        // failed on SessionDeviceMetadata). Clearing them at startup makes
        // the database self-heal on the next launch.
        try
        {
            context.Database.ExecuteSqlRaw(
                "DELETE FROM SessionDeviceMetadata WHERE LoggingSessionID NOT IN (SELECT ID FROM Sessions)");
        }
        catch (Exception ex)
        {
            AppLogger.Error(ex, "Failed to clean orphan SessionDeviceMetadata rows on startup.");
        }

        // One-time backfill: any session created before the SampleCount column
        // existed (or whose count was lost mid-run) gets counted in a single
        // GROUP BY query, then UPDATEd. Subsequent loads pay no cost.
        BackfillMissingSampleCounts(context);

        return new ObservableCollection<LoggingSession>(
            context.Sessions
                .AsNoTracking()
                .Include(session => session.DeviceMetadata)
                .Where(session => context.Samples.Any(sample => sample.LoggingSessionID == session.ID))
                .OrderBy(session => session.ID)
                .ToList());
    }

    /// <summary>
    /// PURE read of the persisted sessions-with-samples list — no purge, no orphan sweep,
    /// no backfill (unlike <see cref="LoadPersistedLoggingSessions"/>). Safe to call
    /// repeatedly and concurrently with a live writer: an in-flight SD-card import commits
    /// its <c>Sessions</c> row with zero samples first, so the empty-session purge in
    /// <see cref="LoadPersistedLoggingSessions"/> would DELETE that in-flight row and corrupt
    /// the import. This variant only SELECTs (the 0-sample import row is naturally excluded
    /// by the <c>Samples.Any</c> filter until it has data), so a refresh can never destroy it.
    /// Used by the mobile Storage pane, which re-reads on every visit.
    /// </summary>
    public ObservableCollection<LoggingSession> GetLoggingSessionsSnapshot()
    {
        using var context = _loggingContext.CreateDbContext();
        return new ObservableCollection<LoggingSession>(
            context.Sessions
                .AsNoTracking()
                .Include(session => session.DeviceMetadata)
                .Where(session => context.Samples.Any(sample => sample.LoggingSessionID == session.ID))
                .OrderBy(session => session.ID)
                .ToList());
    }

    /// <summary>
    /// Persists <see cref="LoggingSession.SampleCount"/> for the given session
    /// by running a single COUNT against the Samples table. Called when a
    /// session ends so the list view can surface the count without a query.
    /// </summary>
    // @port: Daqifi.Desktop.Logger.LoggingManager.PersistSessionSampleCount
    private void PersistSessionSampleCount(LoggingSession session)
    {
        try
        {
            // Wait for any buffered samples in DatabaseLogger to be flushed to
            // disk before counting. Without this, the COUNT can race the
            // background consumer and persist a permanent undercount, since
            // BackfillMissingSampleCounts only repairs null values.
            var dbLogger = Loggers?.OfType<DatabaseLogger>().FirstOrDefault();
            dbLogger?.WaitForIdle(TimeSpan.FromSeconds(10));

            using var context = _loggingContext.CreateDbContext();
            var count = context.Samples.LongCount(s => s.LoggingSessionID == session.ID);

            var tracked = context.Sessions.FirstOrDefault(s => s.ID == session.ID);
            if (tracked != null)
            {
                tracked.SampleCount = count;
                context.SaveChanges();
            }

            // Surface the finalized count so a session end is observable out-of-process
            // (the UI-test harness reads this line to learn the persisted sample count it
            // then cross-checks against an exported CSV). All buffered samples are already
            // flushed (WaitForIdle above), so this is the authoritative per-session total.
            AppLogger.Information($"Persisted sample count {count} for session {session.ID}");

            // Test-mode-only companion oracle for the CSV export harness: the number of
            // DISTINCT (timestamp, device, serial, channel) positions. The device occasionally
            // re-emits a frame with a duplicated timestamp tick mid-session, and the CSV
            // exporters intentionally collapse same-position duplicates into one cell
            // (last value wins) — so the raw sample count overstates the exported cell count
            // whenever a session contains such a frame. This DISTINCT can cost ~a second on
            // million-sample sessions, so it never runs in production.
            if (Daqifi.Desktop.Common.AppDataPaths.IsTestMode)
            {
                var distinctPositions = context.Samples
                    .Where(s => s.LoggingSessionID == session.ID)
                    .Select(s => new { s.TimestampTicks, s.DeviceName, s.DeviceSerialNo, s.ChannelName })
                    .Distinct()
                    .LongCount();
                AppLogger.Information(
                    $"Persisted distinct sample positions {distinctPositions} for session {session.ID}");
            }

            // Marshal the in-memory mutation onto the UI thread so the
            // PropertyChanged notification fires on the dispatcher and
            // bindings update safely (WPF Application.Current.Dispatcher -> Dispatcher.UIThread).
            if (!Dispatcher.UIThread.CheckAccess())
            {
                Dispatcher.UIThread.Invoke(() => session.SampleCount = count);
            }
            else
            {
                session.SampleCount = count;
            }
        }
        catch (Exception ex)
        {
            AppLogger.Error(ex, $"Failed to persist sample count for session {session?.ID}");
        }
    }

    /// <summary>
    /// Lazily backfills <see cref="LoggingSession.SampleCount"/> for any
    /// session whose count is null. Uses a single GROUP BY query covering all
    /// missing sessions at once, then issues UPDATEs in one transaction. Runs
    /// at most once per session over the lifetime of the database.
    /// </summary>
    // @port: Daqifi.Desktop.Logger.LoggingManager.BackfillMissingSampleCounts
    private void BackfillMissingSampleCounts(LoggingContext context)
    {
        try
        {
            var sessionsMissingCount = context.Sessions
                .Where(s => s.SampleCount == null)
                .Select(s => s.ID)
                .ToList();

            if (sessionsMissingCount.Count == 0) { return; }

            var countsBySession = context.Samples
                .Where(sample => sessionsMissingCount.Contains(sample.LoggingSessionID))
                .GroupBy(sample => sample.LoggingSessionID)
                .Select(g => new { SessionId = g.Key, Count = g.LongCount() })
                .ToDictionary(g => g.SessionId, g => g.Count);

            var trackedSessions = context.Sessions
                .Where(s => sessionsMissingCount.Contains(s.ID))
                .ToList();

            foreach (var tracked in trackedSessions)
            {
                tracked.SampleCount = countsBySession.TryGetValue(tracked.ID, out var c) ? c : 0;
            }

            context.SaveChanges();
        }
        catch (Exception ex)
        {
            AppLogger.Error(ex, "Failed to backfill SampleCount for legacy sessions");
        }
    }

    /// <summary>
    /// Reloads persisted logging sessions from storage and repopulates the current collection in place.
    /// </summary>
    // @port: Daqifi.Desktop.Logger.LoggingManager.ReloadPersistedLoggingSessions
    public void ReloadPersistedLoggingSessions()
    {
        var persistedSessions = LoadPersistedLoggingSessions();
        LoggingSessions.Clear();

        foreach (var session in persistedSessions)
        {
            LoggingSessions.Add(session);
        }
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.DeleteLoggingSessionIfPresent
    private void DeleteLoggingSessionIfPresent(int sessionId)
    {
        var existingSession = LoggingSessions.FirstOrDefault(session => session.ID == sessionId);
        if (existingSession != null)
        {
            LoggingSessions.Remove(existingSession);
        }

        try
        {
            using var context = _loggingContext.CreateDbContext();
            var connection = context.Database.GetDbConnection();
            connection.Open();

            using var transaction = connection.BeginTransaction();

            using (var cmd = connection.CreateCommand())
            {
                cmd.Transaction = transaction;
                cmd.CommandText = "DELETE FROM Samples WHERE LoggingSessionID = @id";
                var param = cmd.CreateParameter();
                param.ParameterName = "@id";
                param.Value = sessionId;
                cmd.Parameters.Add(param);
                cmd.ExecuteNonQuery();
            }

            using (var cmd = connection.CreateCommand())
            {
                cmd.Transaction = transaction;
                cmd.CommandText = "DELETE FROM SessionDeviceMetadata WHERE LoggingSessionID = @id";
                var param = cmd.CreateParameter();
                param.ParameterName = "@id";
                param.Value = sessionId;
                cmd.Parameters.Add(param);
                cmd.ExecuteNonQuery();
            }

            using (var cmd = connection.CreateCommand())
            {
                cmd.Transaction = transaction;
                cmd.CommandText = "DELETE FROM Sessions WHERE ID = @id";
                var param = cmd.CreateParameter();
                param.ParameterName = "@id";
                param.Value = sessionId;
                cmd.Parameters.Add(param);
                cmd.ExecuteNonQuery();
            }

            transaction.Commit();
        }
        catch (Exception ex)
        {
            AppLogger.Error(ex, $"Failed to delete logging session {sessionId}");
        }
    }

    // @port: Daqifi.Desktop.Logger.LoggingManager.ClearChannelList
    private void ClearChannelList()
    {
        lock (_subscribedChannelsSync)
        {
            foreach (var channel in _subscribedChannels)
            {
                channel.IsActive = false;
                channel.OnChannelUpdated -= HandleChannelUpdate;
            }

            // Copy-on-write -- see SubscribedChannels' remarks. Clear() would empty the very list a
            // reader on the transport thread may be enumerating; the empty array is immutable.
            Volatile.Write(ref _subscribedChannels, Array.Empty<IChannel>());
        }

        // Raised outside the lock so a binding handler can never re-enter under it.
        OnPropertyChanged(nameof(SubscribedChannels));
    }
}
