// Generated by portomatic scaffold from upstream Daqifi.Desktop/Loggers/LoggingContextDesignTimeFactory.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.Logger;

/// <summary>
/// Factory used by EF Core tooling (dotnet ef migrations) to create
/// a LoggingContext at design time without starting the WPF application.
/// </summary>
// @port: Daqifi.Desktop.Logger.LoggingContextDesignTimeFactory
public class LoggingContextDesignTimeFactory : IDesignTimeDbContextFactory<LoggingContext>
{
    // @port: Daqifi.Desktop.Logger.LoggingContextDesignTimeFactory.CreateDbContext
    public LoggingContext CreateDbContext(string[] args) => throw new NotImplementedException();
}
