// Generated by portomatic scaffold from upstream Daqifi.Desktop/Loggers/SessionDataRepository.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Daqifi.Desktop.Common.Loggers;
using Daqifi.Desktop.Helpers;
using Microsoft.EntityFrameworkCore;
using OxyPlot;
using System.Diagnostics;
using ChannelType = Daqifi.Core.Channel.ChannelType;

namespace Daqifi.Desktop.Logger;

/// <summary>
/// Channel identity and presentation info discovered from a session's sample rows.
/// </summary>
/// <param name="ChannelName">Channel identifier (e.g., "AI0").</param>
/// <param name="DeviceSerialNo">Serial number of the device that owns the channel.</param>
/// <param name="Type">Channel type used to pick the Y axis.</param>
/// <param name="Color">Series color stored with the samples.</param>
// @port: Daqifi.Desktop.Logger.SessionChannelInfo
internal record SessionChannelInfo
{
}

/// <summary>
/// Result of the fast Phase-1 session load: the channels discovered at the session's first
/// timestamp, an initial point batch for each of them, the session's first timestamp, and the
/// total sample count. <see cref="IsEmpty"/> is true for a session with no samples.
/// </summary>
/// <param name="Channels">Channels discovered at the first timestamp, naturally ordered and de-duplicated.</param>
/// <param name="Points">One point list per discovered channel, filled with up to the initial-load cap of samples.</param>
/// <param name="FirstTime">The session's earliest timestamp (the delta-time origin), or null for an empty session.</param>
/// <param name="TotalSampleCount">Count of every sample row in the session.</param>
// @port: Daqifi.Desktop.Logger.InitialSessionLoad
internal record InitialSessionLoad
{
    // @port: Daqifi.Desktop.Logger.InitialSessionLoad.IsEmpty
    public bool IsEmpty
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Logger.InitialSessionLoad.Empty
    public static InitialSessionLoad Empty
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }
}

/// <summary>
/// Owns the session read/delete path extracted from <see cref="DatabaseLogger"/> (issue #592): the
/// EF/ADO.NET queries that turn a session id into point lists (channel discovery, the fast initial
/// batch, the full-range sampled load, the single-timestamp value spread, per-device frequency) and
/// the transactional delete of a session's storage.
/// <para>
/// The database context factory and application logger are constructor-injected, so the repository
/// has no dependency on WPF or on desktop singletons (<c>App.ServiceProvider</c>,
/// <c>AppLogger.Instance</c>) and is unit-testable in isolation against a real temp-SQLite factory.
/// <see cref="DatabaseLogger"/> is the composition root: it builds the repository with the factory it
/// already receives and orchestrates plot construction around the point data the repository returns.
/// </para>
/// </summary>
// @port: Daqifi.Desktop.Logger.SessionDataRepository
public class SessionDataRepository
{
    internal int INITIAL_LOAD_POINTS;

    internal int SAMPLED_POINTS_PER_CHANNEL;

    private IDbContextFactory<LoggingContext> _loggingContext;

    private IAppLogger _appLogger;

    // @port: Daqifi.Desktop.Logger.SessionDataRepository.LoadInitialSession
    internal InitialSessionLoad LoadInitialSession(int sessionId) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Logger.SessionDataRepository.DeduplicateChannelInfo
    internal static List<SessionChannelInfo> DeduplicateChannelInfo(IEnumerable<SessionChannelInfo> rows) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Logger.SessionDataRepository.LoadSampledData
    public DateTime? LoadSampledData(int sessionId, int channelCount, Dictionary<(string deviceSerial, string channelName), List<DataPoint>> localPoints) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Logger.SessionDataRepository.LoadSingleTickValueSpread
    internal static Dictionary<(string deviceSerial, string channelName), List<DataPoint>> LoadSingleTickValueSpread(IDbContextFactory<LoggingContext> contextFactory, int sessionId, List<(string deviceSerial, string channelName)> channelKeys) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Logger.SessionDataRepository.LoadSessionDeviceFrequency
    public Dictionary<string, int> LoadSessionDeviceFrequency(int sessionId) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Logger.SessionDataRepository.DeleteSession
    public void DeleteSession(LoggingSession session) => throw new NotImplementedException();
}
