// Generated by portomatic scaffold from upstream Daqifi.Desktop/Device/Firmware/BootloaderDiscoveredEventArgs.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

namespace Daqifi.Desktop.Device.Firmware;

/// <summary>
/// Identifies a HID bootloader that discovery surfaced.
/// </summary>
// @port: Daqifi.Desktop.Device.Firmware.BootloaderDiscoveredEventArgs
public sealed class BootloaderDiscoveredEventArgs : EventArgs
{
    /// <summary>Creates the event args.</summary>
    public BootloaderDiscoveredEventArgs(string devicePath, string? deviceName)
    {
        DevicePath = string.IsNullOrWhiteSpace(devicePath)
            ? throw new ArgumentException("Device path cannot be empty.", nameof(devicePath))
            : devicePath;
        DeviceName = deviceName;
    }

    /// <summary>OS HID device path of the discovered bootloader.</summary>
    // @port: Daqifi.Desktop.Device.Firmware.BootloaderDiscoveredEventArgs.DevicePath
    public string DevicePath { get; }

    /// <summary>Friendly device name, when discovery could read it; otherwise null.</summary>
    // @port: Daqifi.Desktop.Device.Firmware.BootloaderDiscoveredEventArgs.DeviceName
    public string? DeviceName { get; }
}
