// Generated by portomatic scaffold from upstream Daqifi.Desktop/Device/Firmware/HidBootloaderDiscovery.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Daqifi.Core.Device.Discovery;
using Daqifi.Desktop.Common.Loggers;

namespace Daqifi.Desktop.Device.Firmware;

/// <summary>
/// Default <see cref="IBootloaderDiscovery"/> implementation: a continuous loop over Core's
/// <see cref="HidDeviceFinder"/> that forwards every matching HID bootloader as a
/// <see cref="BootloaderDiscoveredEventArgs"/>. Unlike the connection dialog's old one-shot discovery,
/// this keeps polling so additional hot-plugged bootloaders are surfaced too; the watcher holds each one
/// exclusively the moment it appears, so the finder's per-cycle open attempts on an already-held device
/// fail harmlessly (a refused exclusive open sends no I/O to the device).
/// </summary>
// @port: Daqifi.Desktop.Device.Firmware.HidBootloaderDiscovery
public class HidBootloaderDiscovery : IBootloaderDiscovery, IDisposable
{
    public static TimeSpan DefaultPollInterval;

    private IAppLogger _logger;

    private TimeSpan _pollInterval;

    private Func<HidDeviceFinder> _finderFactory;

    private object _sync;

    private HidDeviceFinder? _finder;

    private CancellationTokenSource? _cts;

    private Task? _loopTask;

    private bool _disposed;

    // @port: Daqifi.Desktop.Device.Firmware.HidBootloaderDiscovery.Start
    public void Start() => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Device.Firmware.HidBootloaderDiscovery.Stop
    public void Stop() => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Device.Firmware.HidBootloaderDiscovery.RunAsync
    private Task RunAsync(HidDeviceFinder finder, CancellationToken cancellationToken) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Device.Firmware.HidBootloaderDiscovery.OnDeviceDiscovered
    private void OnDeviceDiscovered(object? sender, DeviceDiscoveredEventArgs e) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Device.Firmware.HidBootloaderDiscovery.Dispose
    public void Dispose() => throw new NotImplementedException();
}
