// Generated by portomatic scaffold from upstream Daqifi.Desktop/Device/Firmware/IFirmwareUpdateHost.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;

namespace Daqifi.Desktop.Device.Firmware;

/// <summary>
/// Narrow seam the <see cref="FirmwareUpdateCoordinator"/> uses to read user input and push
/// progress/status/result state back to the host view model.
/// <para>
/// Implemented by <c>DaqifiViewModel</c> so its existing bound <c>[ObservableProperty]</c> fields
/// remain the binding source (firmware XAML is unchanged), while the firmware orchestration and
/// version-check logic live in the coordinator and are unit-testable against a lightweight fake.
/// Only firmware-relevant members are exposed here — the coordinator never reaches into desktop
/// singletons (<c>ConnectionManager.Instance</c> etc.) directly.
/// </para>
/// </summary>
// @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost
public interface IFirmwareUpdateHost
{
    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.SelectedDevice
    IStreamingDevice? SelectedDevice { get; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.ConnectedDevices
    IReadOnlyList<IStreamingDevice> ConnectedDevices { get; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.FirmwareFilePath
    string FirmwareFilePath { get; set; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.SelectedDeviceSupportsFirmwareUpdate
    bool SelectedDeviceSupportsFirmwareUpdate { set; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.IsFirmwareUploading
    bool IsFirmwareUploading { get; set; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.IsUploadComplete
    bool IsUploadComplete { set; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.HasErrorOccured
    bool HasErrorOccured { set; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.UploadFirmwareProgress
    int UploadFirmwareProgress { set; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.UploadWiFiProgress
    int UploadWiFiProgress { set; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.FirmwareUpdateStatusText
    string FirmwareUpdateStatusText { set; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.Notifications
    ObservableCollection<Notifications> Notifications { get; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.DeviceBeingUpdated
    IStreamingDevice? DeviceBeingUpdated { set; }

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.RefreshNotificationCount
    void RefreshNotificationCount();

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.ShowFirmwareError
    void ShowFirmwareError(string message);

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.ShowFirmwareUpdateSucceeded
    void ShowFirmwareUpdateSucceeded();

    // @port: Daqifi.Desktop.Device.Firmware.IFirmwareUpdateHost.QuiesceWifiFirmwareProbeAsync
    Task QuiesceWifiFirmwareProbeAsync(CancellationToken cancellationToken);
}
