// Generated by portomatic scaffold from upstream Daqifi.Desktop/Models/DaqifiSettings.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using Daqifi.Desktop.Common.Loggers;
using System.Collections.ObjectModel;
using System.IO;
using System.Xml.Linq;

namespace Daqifi.Desktop.Models;

// @port: Daqifi.Desktop.Models.DaqifiSettings
public class DaqifiSettings
{
    #region Private Data
    private string _csvDelimiter = ",";
    // Use the shared, elevation-aware data directory (AppDataPaths): machine-wide for
    // elevated production runs, per-user for un-elevated runs. Keeps settings writable
    // (and consistent with the database/logs) instead of failing on an admin-owned file.
    private static readonly string AppDirectory = Daqifi.Desktop.Common.AppDataPaths.DataDirectory;
    // Path.Combine, not upstream's `AppDirectory + "\\..."`. A backslash is a legal filename
    // character on macOS/Linux, so the concatenation does not fail there — it silently creates
    // a file literally named `DAQiFi\DAQifiConfiguration.xml` NEXT TO the data directory
    // instead of inside it, splitting settings away from the database and logs. Path.Combine
    // produces the identical string on Windows, so this is a no-op there.
    private static readonly string SettingsXmlPath = Path.Combine(AppDirectory, "DAQifiConfiguration.xml");
    #endregion

    #region Properties
    // @port: Daqifi.Desktop.Models.DaqifiSettings.CsvDelimiterOptions
    public ObservableCollection<string> CsvDelimiterOptions { get; } = [",", ";"];

    // @port: Daqifi.Desktop.Models.DaqifiSettings.CsvDelimiter
    public string CsvDelimiter
    {
        get => _csvDelimiter;
        set
        {
            _csvDelimiter = value;
            SaveSettings();
        }
    }
    #endregion

    #region Singleton Constructor / Initalization
    private static readonly DaqifiSettings _instance = new();

    private DaqifiSettings()
    {
        LoadDAQiFiSettings();
    }

    // @port: Daqifi.Desktop.Models.DaqifiSettings.Instance
    public static DaqifiSettings Instance => _instance;

    #endregion

    #region Settings Methods
    // @port: Daqifi.Desktop.Models.DaqifiSettings.LoadDAQiFiSettings
    private void LoadDAQiFiSettings()
    {
        try
        {
            if (!Directory.Exists(AppDirectory))
            {
                Directory.CreateDirectory(AppDirectory);
            }

            if (!File.Exists(SettingsXmlPath))
            {
                LoadDefaultValues();
            }

            var xml = XElement.Load(SettingsXmlPath);

            if (xml.Element("CsvDelimiter") != null)
            {
                _csvDelimiter = xml.Element("CsvDelimiter").Value;
            }
        }
        catch(Exception ex)
        {
            AppLogger.Instance.Error(ex, "Problem Loading DAQiFi Settings");
        }
    }

    // @port: Daqifi.Desktop.Models.DaqifiSettings.LoadDefaultValues
    private void LoadDefaultValues()
    {
        CsvDelimiter = ",";
        SaveSettings();
    }

    // @port: Daqifi.Desktop.Models.DaqifiSettings.SaveSettings
    private void SaveSettings()
    {
        try
        {
            var xml = new XElement("DAQifiSettings");
            xml.Add(new XElement("CsvDelimiter", CsvDelimiter));
            xml.Save(SettingsXmlPath);
        }
        catch (Exception ex)
        {
            AppLogger.Instance.Error(ex, "Problem Saving DAQiFi Settings");
        }
    }
    #endregion
}