// Generated by portomatic scaffold from upstream Daqifi.Desktop/Models/Notifications.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.Models;

// @port: Daqifi.Desktop.Models.Notifications
public class Notifications
{
    // @port: Daqifi.Desktop.Models.Notifications.IsFirmwareUpdate
    public bool IsFirmwareUpdate
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Models.Notifications.IsWifiFirmwareUpdate
    public bool IsWifiFirmwareUpdate
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Models.Notifications.DeviceSerialNo
    public string DeviceSerialNo
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Models.Notifications.Message
    public string Message
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Models.Notifications.Link
    public string Link
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }
}
