// Generated by portomatic scaffold from upstream Daqifi.Desktop/Converters/BoolToStatusColorConverter.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.Globalization;
using Avalonia.Data.Converters;
using Avalonia.Media;

namespace Daqifi.Desktop.Converters;

// @port: Daqifi.Desktop.Converters.BoolToStatusColorConverter
public class BoolToStatusColorConverter : IValueConverter
{
    // @port: Daqifi.Desktop.Converters.BoolToStatusColorConverter.Convert
    public object Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (value is bool isActive)
        {
            return new SolidColorBrush(isActive ? Colors.LightGreen : Colors.IndianRed);
        }
        return new SolidColorBrush(Colors.Gray);
    }

    // @port: Daqifi.Desktop.Converters.BoolToStatusColorConverter.ConvertBack
    public object ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }
}
