// Generated by portomatic scaffold from upstream Daqifi.Desktop/Converters/BrushColorMatchConverter.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System.Globalization;
using Avalonia.Data.Converters;
using Avalonia.Media;

namespace Daqifi.Desktop.Converters;

/// <summary>
/// Multi-value converter that compares two solid-color brushes by their underlying
/// <see cref="Color"/>. Two brushes constructed from the same hex still count as
/// different references, which breaks equality on the brush object — the Color value is the
/// semantically correct comparison. Matches on <see cref="ISolidColorBrush"/> so both
/// mutable SolidColorBrush and ImmutableSolidColorBrush (ChannelColorManager) compare.
/// WPF returned Visibility when the target was a Visibility property; Avalonia visibility
/// is a bool (IsVisible), so this always returns a boolean.
/// </summary>
// @port: Daqifi.Desktop.Converters.BrushColorMatchConverter
public class BrushColorMatchConverter : IMultiValueConverter
{
    // @port: Daqifi.Desktop.Converters.BrushColorMatchConverter.Convert
    public object Convert(IList<object?> values, Type targetType, object? parameter, CultureInfo culture)
    {
        var match = values.Count >= 2
            && values[0] is ISolidColorBrush a
            && values[1] is ISolidColorBrush b
            && a.Color == b.Color;

        return match;
    }
}
