// Generated by portomatic scaffold from upstream Daqifi.Desktop/Converters/InvertedBoolToVisibilityConverter.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.Converters;

// @port: Daqifi.Desktop.Converters.InvertedBoolToVisibilityConverter
public class InvertedBoolToVisibilityConverter : IValueConverter
{
    // @port: Daqifi.Desktop.Converters.InvertedBoolToVisibilityConverter.Convert
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Converters.InvertedBoolToVisibilityConverter.ConvertBack
    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) => throw new NotImplementedException();
}
