// Generated by portomatic scaffold from upstream Daqifi.Desktop.Common/Loggers/AppLogger.cs.
//
// This is a SKELETON. Method and property bodies throw NotImplementedException.
// The Patch Author agent fills in real bodies during /portomatic-apply.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Daqifi.Desktop.Common.Loggers;

// @port: Daqifi.Desktop.Common.Loggers.AppLogger
public class AppLogger : IAppLogger
{
    private Logger? _logger;

    private IDisposable? _sentryDisposable;

    private static bool IsTestMode;

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Instance
    public static AppLogger Instance
    {
        get => throw new NotImplementedException();
        set => throw new NotImplementedException();
    }

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.IsRunningInTestEnvironment
    private static bool IsRunningInTestEnvironment() => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Information
    public void Information(string message) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Warning
    public void Warning(string message) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Warning
    public void Warning(Exception ex, string message) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Error
    public void Error(string message) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Error
    public void Error(Exception ex, string message) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.AddBreadcrumb
    public void AddBreadcrumb(string category, string message, BreadcrumbLevel level) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.SetDeviceContext
    public void SetDeviceContext(string model, string serialNumber, string firmwareVersion, string connectionType, int activeChannels) => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.ClearDeviceContext
    public void ClearDeviceContext() => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Shutdown
    public void Shutdown() => throw new NotImplementedException();

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.MapBreadcrumbLevel
    private static Sentry.BreadcrumbLevel MapBreadcrumbLevel(BreadcrumbLevel level) => throw new NotImplementedException();
}
