// Generated by portomatic scaffold from upstream Daqifi.Desktop.Common/Loggers/AppLogger.cs.
//
// DO NOT manually delete the `// @port:` markers — they link symbols back to
// the correspondence map.

using NLog;
using NLog.Config;
using NLog.Targets;
using System.Configuration;
using System.IO;
using System.Reflection;

namespace Daqifi.Desktop.Common.Loggers;

// @port: Daqifi.Desktop.Common.Loggers.AppLogger
public class AppLogger : IAppLogger
{
    #region Private Data
    // Qualified: in the merged single assembly the `Daqifi.Desktop.Logger` namespace
    // (upstream Loggers files) shadows NLog.Logger from any Daqifi.Desktop.* scope.
    private readonly NLog.Logger? _logger;
    private IDisposable? _sentryDisposable;
    private static readonly bool IsTestMode = IsRunningInTestEnvironment();
    #endregion

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Instance
    public static AppLogger Instance { get; } = new();

    /// <summary>
    /// Finds the Sentry DSN from the first source that has one.
    /// </summary>
    /// <remarks>
    /// Upstream reads only <c>ConfigurationManager.AppSettings</c>, which is an App.config
    /// mechanism. This repo has no App.config on any head, and Android cannot have one, so
    /// that lookup returned nothing everywhere and Sentry was silently inert on desktop as
    /// well as mobile — the package was referenced and the manifest carried its meta-data,
    /// but <c>SentrySdk.Init</c> was never reached.
    /// <para>
    /// Order is deliberate: an explicit App.config or environment value should win over the
    /// compiled-in default, so a developer or CI run can redirect events away from the
    /// production project without editing the build.
    /// </para>
    /// </remarks>
    private static string? ResolveSentryDsn()
    {
        try
        {
            var configured = ConfigurationManager.AppSettings["SentryDsn"];
            if (!string.IsNullOrWhiteSpace(configured)) { return configured; }
        }
        catch
        {
            // No App.config, or a platform where the provider cannot initialise at all.
            // Not an error — it is the normal case on mobile.
        }

        var fromEnvironment = Environment.GetEnvironmentVariable("DAQIFI_SENTRY_DSN");
        if (!string.IsNullOrWhiteSpace(fromEnvironment)) { return fromEnvironment; }

        // Baked in at build time from the SentryDsn MSBuild property, so every head gets a
        // DSN without shipping a config file. Absent property -> no attribute -> disabled.
        return typeof(AppLogger).Assembly
            .GetCustomAttributes<AssemblyMetadataAttribute>()
            .FirstOrDefault(a => a.Key == "SentryDsn")?.Value;
    }

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.IsRunningInTestEnvironment
    private static bool IsRunningInTestEnvironment()
    {
        try
        {
            // Check if we're running under a test runner by looking for test assemblies
            var assemblies = AppDomain.CurrentDomain.GetAssemblies();
            var testAssemblies = new[] { "Microsoft.VisualStudio.TestPlatform", "nunit.framework", "xunit" };

            return assemblies.Any(a => testAssemblies.Any(t => a.FullName?.Contains(t) == true));
        }
        catch
        {
            // If anything goes wrong checking the assemblies, assume we're not in test mode
            return false;
        }
    }

    private AppLogger()
    {
        if (IsTestMode)
        {
            // In test mode, don't initialize real logging
            _logger = null;
            _sentryDisposable = null;
            return;
        }

        // Step 1. Create configuration object
        var config = new LoggingConfiguration();

        // Step 2. Create targets and add them to the configuration
        var fileTarget = new FileTarget();
        config.AddTarget("file", fileTarget);

        // Step 3. Set target properties
        fileTarget.CreateDirs = true;
        // Write logs alongside the rest of the app data (see AppDataPaths): machine-wide for
        // elevated production runs, per-user for un-elevated runs (test harness / non-admin
        // Debug). Keeping logs and the database in the same root avoids dropping logs when
        // the machine-wide store is admin-owned and the process is not elevated.
        fileTarget.FileName = Path.Combine(AppDataPaths.LogDirectory, "DAQifiAppLog.log");
        fileTarget.Layout = "${longdate} LEVEL=${level:upperCase=true}: ${message}${newline} (${stacktrace}) ${exception:format=tostring} ${newline}";
        fileTarget.KeepFileOpen = false;

        // Setup Archiving
        fileTarget.ArchiveFileName = Path.Combine(AppDataPaths.LogDirectory, "DAQifiAppLog.{#}.log");

        // Archive the log if it gets above 10MB
        fileTarget.ArchiveAboveSize = 10000000;
        fileTarget.ArchiveSuffixFormat = "{#}";

        // Keep a maximum of 5 archives
        fileTarget.MaxArchiveFiles = 5;

        // Step 4. Define rules
        var rule = new LoggingRule("*", LogLevel.Debug, fileTarget);
        config.LoggingRules.Add(rule);

        // Step 5. Activate the configuration
        LogManager.Configuration = config;

        _logger = LogManager.GetCurrentClassLogger();

        // Step 6. Initialize Sentry SDK — explicit CaptureException calls in Error() are the
        // sole capture path; SentryTarget is intentionally omitted to avoid double-reporting.
        var dsn = ResolveSentryDsn();
        var version = Assembly.GetEntryAssembly()?.GetName().Version?.ToString() ?? "0.0.0";

        if (string.IsNullOrWhiteSpace(dsn))
        {
            _logger.Warn("No Sentry DSN resolved — Sentry error reporting is disabled");
            return;
        }

        _sentryDisposable = SentrySdk.Init(options =>
        {
            options.Dsn = dsn;
            options.Release = version;
            options.AutoSessionTracking = true;
            options.IsGlobalModeEnabled = true;
            // Explicit, not relying on the SDK default: this app ships to app stores, where
            // "what is collected" is a declaration we have to make and stand behind. No
            // usernames, no email, no IP address attached to events. Sentry's server-side
            // setting scrubs IPs as well; both belt and braces.
            options.SendDefaultPii = false;
            // Persist envelopes to disk so an event survives having nowhere to send it.
            //
            // This is not a nicety on mobile: a DAQiFi is usually reached over its own soft-AP
            // (SSID "DAQiFi-xxxx", 192.168.1.1), and joining it takes the phone OFF the internet
            // for the whole session. Measured on a Galaxy A16 mid-stream: 100% packet loss to
            // 8.8.8.8. Without a cache directory the SDK holds events in memory only, so they
            // die with the process — a probe captured mid-stream never reached Sentry at all,
            // taking its breadcrumb trail with it, which is precisely the activity this app
            // exists for. With one, the same probe landed on disk and was delivered on the next
            // run once the phone was back on a routable network.
            options.CacheDirectoryPath = AppDataPaths.SentryCacheDirectory;
            // Explicit rather than implicit, and deliberately NOT raised above the SDK's own
            // default (measured: 1s in Sentry 6.8.0). This blocks Init on the UI thread at
            // startup, and the phone is offline for exactly the sessions that fill the cache,
            // so a longer window buys nothing but startup latency — on Android it walks toward
            // the 5s ANR threshold. A backlog that misses this window just goes out on the next
            // run; the envelopes are on disk, which is the whole point.
            options.InitCacheFlushTimeout = TimeSpan.FromSeconds(1);
            // The cache is bounded by MaxCacheItems (measured: 30 by default), so a phone that
            // stays offline discards oldest-first rather than growing without limit.
        });
    }

    #region Logger Methods
    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Information
    public void Information(string message)
    {
        _logger?.Info(message);
    }

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Warning
    public void Warning(string message)
    {
        _logger?.Warn(message);
    }

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Warning
    public void Warning(Exception ex, string message)
    {
        // Intentionally no SentrySdk.CaptureException here — the whole point of the
        // exception-aware warning is to keep stack traces in the local log for
        // expected user/environmental conditions without raising a Sentry event.
        _logger?.Warn(ex, message);
    }

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Error
    public void Error(string message)
    {
        _logger?.Error(message);
        SentrySdk.CaptureException(new Exception(message));
    }

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Error
    public void Error(Exception ex, string message)
    {
        _logger?.Error(ex, message);
        SentrySdk.CaptureException(ex, scope => scope.SetExtra("message", message));
    }

    /// <inheritdoc />
    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.AddBreadcrumb
    public void AddBreadcrumb(string category, string message, BreadcrumbLevel level = BreadcrumbLevel.Info)
    {
        SentrySdk.AddBreadcrumb(
            message: message,
            category: category,
            level: MapBreadcrumbLevel(level));
    }

    /// <inheritdoc />
    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.SetDeviceContext
    public void SetDeviceContext(string model, string serialNumber, string firmwareVersion, string connectionType, int activeChannels)
    {
        SentrySdk.ConfigureScope(scope =>
        {
            scope.SetTag("daqifi.device_model", model ?? "unknown");
            scope.SetTag("daqifi.serial_number", serialNumber ?? "unknown");
            scope.SetTag("daqifi.firmware_version", firmwareVersion ?? "unknown");
            scope.SetTag("daqifi.connection_type", connectionType);
            scope.SetTag("daqifi.active_channels", activeChannels.ToString(System.Globalization.CultureInfo.InvariantCulture));
        });
    }

    /// <inheritdoc />
    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.ClearDeviceContext
    public void ClearDeviceContext()
    {
        SentrySdk.ConfigureScope(scope =>
        {
            scope.UnsetTag("daqifi.device_model");
            scope.UnsetTag("daqifi.serial_number");
            scope.UnsetTag("daqifi.firmware_version");
            scope.UnsetTag("daqifi.connection_type");
            scope.UnsetTag("daqifi.active_channels");
        });
    }

    /// <inheritdoc />
    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.Shutdown
    public void Shutdown()
    {
        SentrySdk.FlushAsync(TimeSpan.FromSeconds(2)).GetAwaiter().GetResult();
        _sentryDisposable?.Dispose();
    }

    // @port: Daqifi.Desktop.Common.Loggers.AppLogger.MapBreadcrumbLevel
    private static Sentry.BreadcrumbLevel MapBreadcrumbLevel(BreadcrumbLevel level)
    {
        return level switch
        {
            BreadcrumbLevel.Debug => Sentry.BreadcrumbLevel.Debug,
            BreadcrumbLevel.Info => Sentry.BreadcrumbLevel.Info,
            BreadcrumbLevel.Warning => Sentry.BreadcrumbLevel.Warning,
            BreadcrumbLevel.Error => Sentry.BreadcrumbLevel.Error,
            BreadcrumbLevel.Critical => Sentry.BreadcrumbLevel.Error,
            _ => Sentry.BreadcrumbLevel.Info
        };
    }
    #endregion
}
